// Generated by ReScript, PLEASE EDIT WITH CARE


var config_capabilities = [
  "GraphVisualization",
  "EcosystemScanning",
  "EdgeManagement",
  "GroupManagement",
  "AspectAnnotation",
  "SlotBindingSystem",
  "ScenarioPlanning",
  "ExportMultiFormat",
  "ConstraintEvaluation",
  "HealthDashboard"
];

var config_icon = "railway";

var config = {
  id: "reposystem",
  name: "Reposystem",
  version: "0.1.0",
  description: "Railway yard for repository ecosystems. Visualises repo relationships, manages slots and providers, annotates aspects, and coordinates multi-repo changes with scenario planning.",
  capabilities: config_capabilities,
  icon: config_icon
};

function hasCapability(cap) {
  return config_capabilities.includes(cap);
}

function capabilityLabel(cap) {
  switch (cap) {
    case "GraphVisualization" :
        return "Graph Visualization";
    case "EcosystemScanning" :
        return "Ecosystem Scanning";
    case "EdgeManagement" :
        return "Edge Management";
    case "GroupManagement" :
        return "Group Management";
    case "AspectAnnotation" :
        return "Aspect Annotation";
    case "SlotBindingSystem" :
        return "Slot Binding System";
    case "ScenarioPlanning" :
        return "Scenario Planning";
    case "ExportMultiFormat" :
        return "Multi-Format Export";
    case "ConstraintEvaluation" :
        return "Constraint Evaluation";
    case "HealthDashboard" :
        return "Health Dashboard";
    
  }
}

function capabilityDescription(cap) {
  switch (cap) {
    case "GraphVisualization" :
        return "Force-directed, hierarchical, circular, and grid graph layouts with D3 rendering";
    case "EcosystemScanning" :
        return "Discover repos from local filesystem or forge APIs, build initial graph";
    case "EdgeManagement" :
        return "Create and remove typed, channelled relationships between repos with metadata";
    case "GroupManagement" :
        return "Organize repos into named groups for filtering and batch operations";
    case "AspectAnnotation" :
        return "Tag repos and edges with weighted aspect scores (security, reliability, etc.)";
    case "SlotBindingSystem" :
        return "Declare required capabilities as slots and bind provider repos to fulfil them";
    case "ScenarioPlanning" :
        return "Coordinate multi-repo changes with risk assessment and rollback planning";
    case "ExportMultiFormat" :
        return "Export ecosystem graph to JSON, YAML, TOML, and Graphviz DOT formats";
    case "ConstraintEvaluation" :
        return "Evaluate the ecosystem against governance rules and RSR policy";
    case "HealthDashboard" :
        return "Aggregate health metrics, slot coverage, aspect scores across the ecosystem";
    
  }
}

export {
  config ,
  hasCapability ,
  capabilityLabel ,
  capabilityDescription ,
}
/* No side effect */
