// Generated by ReScript, PLEASE EDIT WITH CARE

import * as View from "./View.res.js";
import * as Model from "./Model.res.js";
import * as Update from "./Update.res.js";
import * as Tea_app from "rescript-tea/src/tea_app.res.js";
import * as Tea_cmd from "rescript-tea/src/tea_cmd.res.js";
import * as Tea_sub from "rescript-tea/src/tea_sub.res.js";

function init() {
  var model = Model.init();
  return [
          model,
          Tea_cmd.msg("LoadAllData")
        ];
}

function subscriptions(_model) {
  return Tea_sub.none;
}

function main() {
  return Tea_app.standardProgram({
              init: init,
              update: Update.update,
              view: View.view,
              subscriptions: subscriptions
            }, document.getElementById("app"), undefined);
}

export {
  init ,
  subscriptions ,
  main ,
}
/* View Not a pure module */
