// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PanllBridge from "./modules/PanllBridge.res.js";

function init() {
  return {
          repos: [],
          edges: [],
          groups: [],
          aspects: [],
          slots: [],
          providers: [],
          bindings: [],
          plans: [],
          activeTab: "Dashboard",
          selectedItem: "NoSelection",
          searchQuery: "",
          graphNodes: [],
          graphLinks: [],
          loading: true,
          error: undefined,
          panll: PanllBridge.init,
          openForm: "NoForm"
        };
}

function tabToString(tab) {
  switch (tab) {
    case "Dashboard" :
        return "Dashboard";
    case "Repos" :
        return "Repos";
    case "Edges" :
        return "Edges";
    case "Groups" :
        return "Groups";
    case "Aspects" :
        return "Aspects";
    case "Slots" :
        return "Slots";
    case "Plans" :
        return "Plans";
    
  }
}

var allTabs = [
  "Dashboard",
  "Repos",
  "Edges",
  "Groups",
  "Aspects",
  "Slots",
  "Plans"
];

function buildGraphNodes(model) {
  var repoNodes = model.repos.map(function (r) {
        return {
                id: r.id,
                label: r.name,
                kind: "repo",
                x: Math.random() * 800.0,
                y: Math.random() * 600.0,
                vx: 0.0,
                vy: 0.0,
                fx: undefined,
                fy: undefined
              };
      });
  var slotNodes = model.slots.map(function (s) {
        return {
                id: s.id,
                label: s.name,
                kind: "slot",
                x: Math.random() * 800.0,
                y: Math.random() * 600.0,
                vx: 0.0,
                vy: 0.0,
                fx: undefined,
                fy: undefined
              };
      });
  var providerNodes = model.providers.map(function (p) {
        return {
                id: p.id,
                label: p.name,
                kind: "provider",
                x: Math.random() * 800.0,
                y: Math.random() * 600.0,
                vx: 0.0,
                vy: 0.0,
                fx: undefined,
                fy: undefined
              };
      });
  return [
            repoNodes,
            slotNodes,
            providerNodes
          ].flat();
}

function buildGraphLinks(model) {
  var edgeLinks = model.edges.map(function (e) {
        return {
                source: e.from,
                target: e.to,
                kind: "edge",
                label: e.label
              };
      });
  var bindingLinks = model.bindings.map(function (b) {
        return {
                source: b.consumer_id,
                target: b.provider_id,
                kind: "binding",
                label: "uses"
              };
      });
  return edgeLinks.concat(bindingLinks);
}

function withGraphData(model) {
  return {
          repos: model.repos,
          edges: model.edges,
          groups: model.groups,
          aspects: model.aspects,
          slots: model.slots,
          providers: model.providers,
          bindings: model.bindings,
          plans: model.plans,
          activeTab: model.activeTab,
          selectedItem: model.selectedItem,
          searchQuery: model.searchQuery,
          graphNodes: buildGraphNodes(model),
          graphLinks: buildGraphLinks(model),
          loading: model.loading,
          error: model.error,
          panll: model.panll,
          openForm: model.openForm
        };
}

export {
  init ,
  tabToString ,
  allTabs ,
  buildGraphNodes ,
  buildGraphLinks ,
  withGraphData ,
}
/* No side effect */
