// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_exn from "rescript/lib/es6/js_exn.js";
import * as Core from "@tauri-apps/api/core";

function isGossamerRuntime() {
  return typeof window !== 'undefined'
    && typeof window.__gossamer_invoke === 'function';
}
;

function gossamerInvoke(cmd, args) {
  return window.__gossamer_invoke(cmd, args);
}
;

function isTauriRuntime() {
  return typeof window !== 'undefined'
    && window.__TAURI_INTERNALS__ != null
    && !window.__TAURI_INTERNALS__.__BROWSER_SHIM__;
}
;

var _detectedRuntime = null;
function detectRuntime() {
  if (_detectedRuntime !== null) return _detectedRuntime;
  if (typeof window !== 'undefined' && typeof window.__gossamer_invoke === 'function') {
    _detectedRuntime = 'gossamer';
  } else if (typeof window !== 'undefined' && window.__TAURI_INTERNALS__ != null && !window.__TAURI_INTERNALS__.__BROWSER_SHIM__) {
    _detectedRuntime = 'tauri';
  } else {
    _detectedRuntime = 'browser';
  }
  return _detectedRuntime;
}
;

function detectRuntime$1() {
  var match = detectRuntime();
  switch (match) {
    case "gossamer" :
        return "Gossamer";
    case "tauri" :
        return "Tauri";
    default:
      return "BrowserOnly";
  }
}

function invoke(cmd, args) {
  if (isGossamerRuntime()) {
    return gossamerInvoke(cmd, args);
  } else if (isTauriRuntime()) {
    return Core.invoke(cmd, args);
  } else {
    return Promise.reject(Js_exn.raiseError("No desktop runtime — \"" + cmd + "\" requires Gossamer or Tauri"));
  }
}

function invokeNoArgs(cmd) {
  return invoke(cmd, undefined);
}

function hasDesktopRuntime() {
  if (isGossamerRuntime()) {
    return true;
  } else {
    return isTauriRuntime();
  }
}

function runtimeName() {
  var match = detectRuntime$1();
  switch (match) {
    case "Gossamer" :
        return "Gossamer";
    case "Tauri" :
        return "Tauri";
    case "BrowserOnly" :
        return "Browser";
    
  }
}

export {
  detectRuntime$1 as detectRuntime,
  invoke ,
  invokeNoArgs ,
  hasDesktopRuntime ,
  runtimeName ,
}
/*  Not a pure module */
