// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Model from "./Model.res.js";
import * as Tea_html from "rescript-tea/src/tea_html.res.js";
import * as Belt_List from "rescript/lib/es6/belt_List.js";
import * as Core__Option from "@rescript/core/src/Core__Option.res.js";

function matchesSearch(query, text) {
  if (query === "") {
    return true;
  } else {
    return text.toLowerCase().includes(query.toLowerCase());
  }
}

function tabIcon(tab) {
  switch (tab) {
    case "Dashboard" :
        return "~";
    case "Repos" :
        return "@";
    case "Edges" :
        return "->";
    case "Groups" :
        return "[]";
    case "Aspects" :
        return "#";
    case "Slots" :
        return "<>";
    case "Plans" :
        return "!";
    
  }
}

function tabCount(model, tab) {
  switch (tab) {
    case "Dashboard" :
        return "";
    case "Repos" :
        return model.repos.length.toString();
    case "Edges" :
        return model.edges.length.toString();
    case "Groups" :
        return model.groups.length.toString();
    case "Aspects" :
        return model.aspects.length.toString();
    case "Slots" :
        return model.slots.length.toString();
    case "Plans" :
        return model.plans.length.toString();
    
  }
}

function forgeToString(forge) {
  switch (forge) {
    case "gh" :
        return "GitHub";
    case "gl" :
        return "GitLab";
    case "bb" :
        return "Bitbucket";
    case "cb" :
        return "Codeberg";
    case "sr" :
        return "Sourcehut";
    case "local" :
        return "Local";
    
  }
}

function providerTypeToString(pt) {
  switch (pt) {
    case "local" :
        return "local";
    case "ecosystem" :
        return "ecosystem";
    case "external" :
        return "external";
    case "stub" :
        return "stub";
    
  }
}

function planStatusToString(status) {
  switch (status) {
    case "draft" :
        return "Draft";
    case "ready" :
        return "Ready";
    case "applied" :
        return "Applied";
    case "rolled_back" :
        return "Rolled Back";
    case "cancelled" :
        return "Cancelled";
    
  }
}

function formField(label_, fieldName, value_, placeholder_Opt) {
  var placeholder_ = placeholder_Opt !== undefined ? placeholder_Opt : "";
  return Tea_html.div(undefined, undefined, {
              hd: Tea_html.Attributes.$$class("form-field"),
              tl: /* [] */0
            }, {
              hd: Tea_html.label(undefined, undefined, {
                    hd: Tea_html.Attributes.$$class("form-label"),
                    tl: /* [] */0
                  }, {
                    hd: Tea_html.text(label_),
                    tl: /* [] */0
                  }),
              tl: {
                hd: Tea_html.input$p(undefined, undefined, {
                      hd: Tea_html.Attributes.$$class("form-input"),
                      tl: {
                        hd: Tea_html.Attributes.type$p("text"),
                        tl: {
                          hd: Tea_html.Attributes.placeholder(placeholder_),
                          tl: {
                            hd: Tea_html.Attributes.value(value_),
                            tl: {
                              hd: Tea_html.Events.onInput(undefined, (function (v) {
                                      return {
                                              TAG: "UpdateFormField",
                                              _0: fieldName,
                                              _1: v
                                            };
                                    })),
                              tl: /* [] */0
                            }
                          }
                        }
                      }
                    }, /* [] */0),
                tl: /* [] */0
              }
            });
}

function formSelect(label_, fieldName, value_, options) {
  var selected = value_ === "";
  return Tea_html.div(undefined, undefined, {
              hd: Tea_html.Attributes.$$class("form-field"),
              tl: /* [] */0
            }, {
              hd: Tea_html.label(undefined, undefined, {
                    hd: Tea_html.Attributes.$$class("form-label"),
                    tl: /* [] */0
                  }, {
                    hd: Tea_html.text(label_),
                    tl: /* [] */0
                  }),
              tl: {
                hd: Tea_html.select(undefined, undefined, {
                      hd: Tea_html.Attributes.$$class("form-select"),
                      tl: {
                        hd: Tea_html.Events.onInput(undefined, (function (v) {
                                return {
                                        TAG: "UpdateFormField",
                                        _0: fieldName,
                                        _1: v
                                      };
                              })),
                        tl: /* [] */0
                      }
                    }, Belt_List.fromArray([Tea_html.option(undefined, undefined, {
                                  hd: Tea_html.Attributes.value(""),
                                  tl: {
                                    hd: Tea_html.Attributes.disabled(true),
                                    tl: {
                                      hd: Tea_html.Attributes.selected(selected),
                                      tl: /* [] */0
                                    }
                                  }
                                }, {
                                  hd: Tea_html.text("Select " + label_ + "..."),
                                  tl: /* [] */0
                                })].concat(options.map(function (param) {
                                  var val = param[0];
                                  return Tea_html.option(undefined, undefined, {
                                              hd: Tea_html.Attributes.value(val),
                                              tl: {
                                                hd: Tea_html.Attributes.selected(val === value_),
                                                tl: /* [] */0
                                              }
                                            }, {
                                              hd: Tea_html.text(param[1]),
                                              tl: /* [] */0
                                            });
                                })))),
                tl: /* [] */0
              }
            });
}

function formCheckbox(label_, fieldName, checked_) {
  return Tea_html.div(undefined, undefined, {
              hd: Tea_html.Attributes.$$class("form-field form-field-checkbox"),
              tl: /* [] */0
            }, {
              hd: Tea_html.label(undefined, undefined, {
                    hd: Tea_html.Attributes.$$class("form-label"),
                    tl: /* [] */0
                  }, {
                    hd: Tea_html.input$p(undefined, undefined, {
                          hd: Tea_html.Attributes.type$p("checkbox"),
                          tl: {
                            hd: Tea_html.Attributes.checked(checked_),
                            tl: {
                              hd: Tea_html.Events.onClick({
                                    TAG: "UpdateFormBool",
                                    _0: fieldName,
                                    _1: !checked_
                                  }),
                              tl: /* [] */0
                            }
                          }
                        }, /* [] */0),
                    tl: {
                      hd: Tea_html.text(" " + label_),
                      tl: /* [] */0
                    }
                  }),
              tl: /* [] */0
            });
}

function formActions() {
  return Tea_html.div(undefined, undefined, {
              hd: Tea_html.Attributes.$$class("form-actions"),
              tl: /* [] */0
            }, {
              hd: Tea_html.button(undefined, undefined, {
                    hd: Tea_html.Events.onClick("SubmitForm"),
                    tl: {
                      hd: Tea_html.Attributes.$$class("btn-submit"),
                      tl: /* [] */0
                    }
                  }, {
                    hd: Tea_html.text("Create"),
                    tl: /* [] */0
                  }),
              tl: {
                hd: Tea_html.button(undefined, undefined, {
                      hd: Tea_html.Events.onClick("CloseForm"),
                      tl: {
                        hd: Tea_html.Attributes.$$class("btn-cancel"),
                        tl: /* [] */0
                      }
                    }, {
                      hd: Tea_html.text("Cancel"),
                      tl: /* [] */0
                    }),
                tl: /* [] */0
              }
            });
}

function renderRepoDetail(repo) {
  return Tea_html.div(undefined, undefined, {
              hd: Tea_html.Attributes.$$class("detail"),
              tl: /* [] */0
            }, {
              hd: Tea_html.h3(undefined, undefined, /* [] */0, {
                    hd: Tea_html.text(repo.name),
                    tl: /* [] */0
                  }),
              tl: {
                hd: Tea_html.dl(undefined, undefined, /* [] */0, {
                      hd: Tea_html.dt(undefined, undefined, /* [] */0, {
                            hd: Tea_html.text("ID"),
                            tl: /* [] */0
                          }),
                      tl: {
                        hd: Tea_html.dd(undefined, undefined, /* [] */0, {
                              hd: Tea_html.text(repo.id),
                              tl: /* [] */0
                            }),
                        tl: {
                          hd: Tea_html.dt(undefined, undefined, /* [] */0, {
                                hd: Tea_html.text("Owner"),
                                tl: /* [] */0
                              }),
                          tl: {
                            hd: Tea_html.dd(undefined, undefined, /* [] */0, {
                                  hd: Tea_html.text(repo.owner),
                                  tl: /* [] */0
                                }),
                            tl: {
                              hd: Tea_html.dt(undefined, undefined, /* [] */0, {
                                    hd: Tea_html.text("Forge"),
                                    tl: /* [] */0
                                  }),
                              tl: {
                                hd: Tea_html.dd(undefined, undefined, /* [] */0, {
                                      hd: Tea_html.text(forgeToString(repo.forge)),
                                      tl: /* [] */0
                                    }),
                                tl: {
                                  hd: Tea_html.dt(undefined, undefined, /* [] */0, {
                                        hd: Tea_html.text("Default Branch"),
                                        tl: /* [] */0
                                      }),
                                  tl: {
                                    hd: Tea_html.dd(undefined, undefined, /* [] */0, {
                                          hd: Tea_html.text(repo.default_branch),
                                          tl: /* [] */0
                                        }),
                                    tl: {
                                      hd: Tea_html.dt(undefined, undefined, /* [] */0, {
                                            hd: Tea_html.text("Tags"),
                                            tl: /* [] */0
                                          }),
                                      tl: {
                                        hd: Tea_html.dd(undefined, undefined, /* [] */0, {
                                              hd: Tea_html.text(repo.tags.join(", ")),
                                              tl: /* [] */0
                                            }),
                                        tl: /* [] */0
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }),
                tl: {
                  hd: Tea_html.button(undefined, undefined, {
                        hd: Tea_html.Events.onClick("ClearSelection"),
                        tl: {
                          hd: Tea_html.Attributes.$$class("btn-close"),
                          tl: /* [] */0
                        }
                      }, {
                        hd: Tea_html.text("Close"),
                        tl: /* [] */0
                      }),
                  tl: /* [] */0
                }
              }
            });
}

function renderEdgeDetail(edge) {
  return Tea_html.div(undefined, undefined, {
              hd: Tea_html.Attributes.$$class("detail"),
              tl: /* [] */0
            }, {
              hd: Tea_html.h3(undefined, undefined, /* [] */0, {
                    hd: Tea_html.text(Core__Option.getOr(edge.label, "Edge")),
                    tl: /* [] */0
                  }),
              tl: {
                hd: Tea_html.dl(undefined, undefined, /* [] */0, {
                      hd: Tea_html.dt(undefined, undefined, /* [] */0, {
                            hd: Tea_html.text("ID"),
                            tl: /* [] */0
                          }),
                      tl: {
                        hd: Tea_html.dd(undefined, undefined, /* [] */0, {
                              hd: Tea_html.text(edge.id),
                              tl: /* [] */0
                            }),
                        tl: {
                          hd: Tea_html.dt(undefined, undefined, /* [] */0, {
                                hd: Tea_html.text("From"),
                                tl: /* [] */0
                              }),
                          tl: {
                            hd: Tea_html.dd(undefined, undefined, /* [] */0, {
                                  hd: Tea_html.text(edge.from),
                                  tl: /* [] */0
                                }),
                            tl: {
                              hd: Tea_html.dt(undefined, undefined, /* [] */0, {
                                    hd: Tea_html.text("To"),
                                    tl: /* [] */0
                                  }),
                              tl: {
                                hd: Tea_html.dd(undefined, undefined, /* [] */0, {
                                      hd: Tea_html.text(edge.to),
                                      tl: /* [] */0
                                    }),
                                tl: {
                                  hd: Tea_html.dt(undefined, undefined, /* [] */0, {
                                        hd: Tea_html.text("Created By"),
                                        tl: /* [] */0
                                      }),
                                  tl: {
                                    hd: Tea_html.dd(undefined, undefined, /* [] */0, {
                                          hd: Tea_html.text(edge.meta.created_by),
                                          tl: /* [] */0
                                        }),
                                    tl: /* [] */0
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }),
                tl: {
                  hd: Tea_html.button(undefined, undefined, {
                        hd: Tea_html.Events.onClick({
                              TAG: "RemoveEdge",
                              _0: edge.id
                            }),
                        tl: {
                          hd: Tea_html.Attributes.$$class("btn-danger"),
                          tl: /* [] */0
                        }
                      }, {
                        hd: Tea_html.text("Remove"),
                        tl: /* [] */0
                      }),
                  tl: {
                    hd: Tea_html.button(undefined, undefined, {
                          hd: Tea_html.Events.onClick("ClearSelection"),
                          tl: {
                            hd: Tea_html.Attributes.$$class("btn-close"),
                            tl: /* [] */0
                          }
                        }, {
                          hd: Tea_html.text("Close"),
                          tl: /* [] */0
                        }),
                    tl: /* [] */0
                  }
                }
              }
            });
}

function renderGroupDetail(group) {
  return Tea_html.div(undefined, undefined, {
              hd: Tea_html.Attributes.$$class("detail"),
              tl: /* [] */0
            }, {
              hd: Tea_html.h3(undefined, undefined, /* [] */0, {
                    hd: Tea_html.text(group.name),
                    tl: /* [] */0
                  }),
              tl: {
                hd: Tea_html.dl(undefined, undefined, /* [] */0, {
                      hd: Tea_html.dt(undefined, undefined, /* [] */0, {
                            hd: Tea_html.text("ID"),
                            tl: /* [] */0
                          }),
                      tl: {
                        hd: Tea_html.dd(undefined, undefined, /* [] */0, {
                              hd: Tea_html.text(group.id),
                              tl: /* [] */0
                            }),
                        tl: {
                          hd: Tea_html.dt(undefined, undefined, /* [] */0, {
                                hd: Tea_html.text("Description"),
                                tl: /* [] */0
                              }),
                          tl: {
                            hd: Tea_html.dd(undefined, undefined, /* [] */0, {
                                  hd: Tea_html.text(Core__Option.getOr(group.description, "-")),
                                  tl: /* [] */0
                                }),
                            tl: {
                              hd: Tea_html.dt(undefined, undefined, /* [] */0, {
                                    hd: Tea_html.text("Members"),
                                    tl: /* [] */0
                                  }),
                              tl: {
                                hd: Tea_html.dd(undefined, undefined, /* [] */0, Belt_List.fromArray(group.members.map(function (m) {
                                              return Tea_html.div(undefined, undefined, {
                                                          hd: Tea_html.Attributes.$$class("member-row"),
                                                          tl: /* [] */0
                                                        }, {
                                                          hd: Tea_html.span(undefined, undefined, /* [] */0, {
                                                                hd: Tea_html.text(m),
                                                                tl: /* [] */0
                                                              }),
                                                          tl: {
                                                            hd: Tea_html.button(undefined, undefined, {
                                                                  hd: Tea_html.Events.onClick({
                                                                        TAG: "RemoveFromGroup",
                                                                        _0: group.id,
                                                                        _1: m
                                                                      }),
                                                                  tl: {
                                                                    hd: Tea_html.Attributes.$$class("btn-danger btn-sm"),
                                                                    tl: /* [] */0
                                                                  }
                                                                }, {
                                                                  hd: Tea_html.text("x"),
                                                                  tl: /* [] */0
                                                                }),
                                                            tl: /* [] */0
                                                          }
                                                        });
                                            }))),
                                tl: /* [] */0
                              }
                            }
                          }
                        }
                      }
                    }),
                tl: {
                  hd: Tea_html.button(undefined, undefined, {
                        hd: Tea_html.Events.onClick("ClearSelection"),
                        tl: {
                          hd: Tea_html.Attributes.$$class("btn-close"),
                          tl: /* [] */0
                        }
                      }, {
                        hd: Tea_html.text("Close"),
                        tl: /* [] */0
                      }),
                  tl: /* [] */0
                }
              }
            });
}

function renderAspectDetail(aspect) {
  return Tea_html.div(undefined, undefined, {
              hd: Tea_html.Attributes.$$class("detail"),
              tl: /* [] */0
            }, {
              hd: Tea_html.h3(undefined, undefined, /* [] */0, {
                    hd: Tea_html.text(aspect.aspect_id),
                    tl: /* [] */0
                  }),
              tl: {
                hd: Tea_html.dl(undefined, undefined, /* [] */0, {
                      hd: Tea_html.dt(undefined, undefined, /* [] */0, {
                            hd: Tea_html.text("Target"),
                            tl: /* [] */0
                          }),
                      tl: {
                        hd: Tea_html.dd(undefined, undefined, /* [] */0, {
                              hd: Tea_html.text(aspect.target),
                              tl: /* [] */0
                            }),
                        tl: {
                          hd: Tea_html.dt(undefined, undefined, /* [] */0, {
                                hd: Tea_html.text("Weight"),
                                tl: /* [] */0
                              }),
                          tl: {
                            hd: Tea_html.dd(undefined, undefined, /* [] */0, {
                                  hd: Tea_html.text(aspect.weight.toString()),
                                  tl: /* [] */0
                                }),
                            tl: {
                              hd: Tea_html.dt(undefined, undefined, /* [] */0, {
                                    hd: Tea_html.text("Reason"),
                                    tl: /* [] */0
                                  }),
                              tl: {
                                hd: Tea_html.dd(undefined, undefined, /* [] */0, {
                                      hd: Tea_html.text(aspect.reason),
                                      tl: /* [] */0
                                    }),
                                tl: /* [] */0
                              }
                            }
                          }
                        }
                      }
                    }),
                tl: {
                  hd: Tea_html.button(undefined, undefined, {
                        hd: Tea_html.Events.onClick({
                              TAG: "RemoveAspect",
                              _0: aspect.id
                            }),
                        tl: {
                          hd: Tea_html.Attributes.$$class("btn-danger"),
                          tl: /* [] */0
                        }
                      }, {
                        hd: Tea_html.text("Remove"),
                        tl: /* [] */0
                      }),
                  tl: {
                    hd: Tea_html.button(undefined, undefined, {
                          hd: Tea_html.Events.onClick("ClearSelection"),
                          tl: {
                            hd: Tea_html.Attributes.$$class("btn-close"),
                            tl: /* [] */0
                          }
                        }, {
                          hd: Tea_html.text("Close"),
                          tl: /* [] */0
                        }),
                    tl: /* [] */0
                  }
                }
              }
            });
}

function renderSlotDetail(slot) {
  return Tea_html.div(undefined, undefined, {
              hd: Tea_html.Attributes.$$class("detail"),
              tl: /* [] */0
            }, {
              hd: Tea_html.h3(undefined, undefined, /* [] */0, {
                    hd: Tea_html.text(slot.name),
                    tl: /* [] */0
                  }),
              tl: {
                hd: Tea_html.dl(undefined, undefined, /* [] */0, {
                      hd: Tea_html.dt(undefined, undefined, /* [] */0, {
                            hd: Tea_html.text("ID"),
                            tl: /* [] */0
                          }),
                      tl: {
                        hd: Tea_html.dd(undefined, undefined, /* [] */0, {
                              hd: Tea_html.text(slot.id),
                              tl: /* [] */0
                            }),
                        tl: {
                          hd: Tea_html.dt(undefined, undefined, /* [] */0, {
                                hd: Tea_html.text("Category"),
                                tl: /* [] */0
                              }),
                          tl: {
                            hd: Tea_html.dd(undefined, undefined, /* [] */0, {
                                  hd: Tea_html.text(slot.category),
                                  tl: /* [] */0
                                }),
                            tl: {
                              hd: Tea_html.dt(undefined, undefined, /* [] */0, {
                                    hd: Tea_html.text("Interface Version"),
                                    tl: /* [] */0
                                  }),
                              tl: {
                                hd: Tea_html.dd(undefined, undefined, /* [] */0, {
                                      hd: Tea_html.text(Core__Option.getOr(slot.interface_version, "-")),
                                      tl: /* [] */0
                                    }),
                                tl: {
                                  hd: Tea_html.dt(undefined, undefined, /* [] */0, {
                                        hd: Tea_html.text("Description"),
                                        tl: /* [] */0
                                      }),
                                  tl: {
                                    hd: Tea_html.dd(undefined, undefined, /* [] */0, {
                                          hd: Tea_html.text(slot.description),
                                          tl: /* [] */0
                                        }),
                                    tl: {
                                      hd: Tea_html.dt(undefined, undefined, /* [] */0, {
                                            hd: Tea_html.text("Required Capabilities"),
                                            tl: /* [] */0
                                          }),
                                      tl: {
                                        hd: Tea_html.dd(undefined, undefined, /* [] */0, {
                                              hd: Tea_html.text(slot.required_capabilities.join(", ")),
                                              tl: /* [] */0
                                            }),
                                        tl: /* [] */0
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }),
                tl: {
                  hd: Tea_html.button(undefined, undefined, {
                        hd: Tea_html.Events.onClick("ClearSelection"),
                        tl: {
                          hd: Tea_html.Attributes.$$class("btn-close"),
                          tl: /* [] */0
                        }
                      }, {
                        hd: Tea_html.text("Close"),
                        tl: /* [] */0
                      }),
                  tl: /* [] */0
                }
              }
            });
}

function renderProviderDetail(provider) {
  return Tea_html.div(undefined, undefined, {
              hd: Tea_html.Attributes.$$class("detail"),
              tl: /* [] */0
            }, {
              hd: Tea_html.h3(undefined, undefined, /* [] */0, {
                    hd: Tea_html.text(provider.name),
                    tl: /* [] */0
                  }),
              tl: {
                hd: Tea_html.dl(undefined, undefined, /* [] */0, {
                      hd: Tea_html.dt(undefined, undefined, /* [] */0, {
                            hd: Tea_html.text("ID"),
                            tl: /* [] */0
                          }),
                      tl: {
                        hd: Tea_html.dd(undefined, undefined, /* [] */0, {
                              hd: Tea_html.text(provider.id),
                              tl: /* [] */0
                            }),
                        tl: {
                          hd: Tea_html.dt(undefined, undefined, /* [] */0, {
                                hd: Tea_html.text("Slot"),
                                tl: /* [] */0
                              }),
                          tl: {
                            hd: Tea_html.dd(undefined, undefined, /* [] */0, {
                                  hd: Tea_html.text(provider.slot_id),
                                  tl: /* [] */0
                                }),
                            tl: {
                              hd: Tea_html.dt(undefined, undefined, /* [] */0, {
                                    hd: Tea_html.text("Type"),
                                    tl: /* [] */0
                                  }),
                              tl: {
                                hd: Tea_html.dd(undefined, undefined, /* [] */0, {
                                      hd: Tea_html.text(providerTypeToString(provider.provider_type)),
                                      tl: /* [] */0
                                    }),
                                tl: {
                                  hd: Tea_html.dt(undefined, undefined, /* [] */0, {
                                        hd: Tea_html.text("Repo"),
                                        tl: /* [] */0
                                      }),
                                  tl: {
                                    hd: Tea_html.dd(undefined, undefined, /* [] */0, {
                                          hd: Tea_html.text(Core__Option.getOr(provider.repo_id, "-")),
                                          tl: /* [] */0
                                        }),
                                    tl: {
                                      hd: Tea_html.dt(undefined, undefined, /* [] */0, {
                                            hd: Tea_html.text("Priority"),
                                            tl: /* [] */0
                                          }),
                                      tl: {
                                        hd: Tea_html.dd(undefined, undefined, /* [] */0, {
                                              hd: Tea_html.text(provider.priority.toString()),
                                              tl: /* [] */0
                                            }),
                                        tl: {
                                          hd: Tea_html.dt(undefined, undefined, /* [] */0, {
                                                hd: Tea_html.text("Fallback"),
                                                tl: /* [] */0
                                              }),
                                          tl: {
                                            hd: Tea_html.dd(undefined, undefined, /* [] */0, {
                                                  hd: Tea_html.text(provider.is_fallback ? "Yes" : "No"),
                                                  tl: /* [] */0
                                                }),
                                            tl: /* [] */0
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }),
                tl: {
                  hd: Tea_html.button(undefined, undefined, {
                        hd: Tea_html.Events.onClick("ClearSelection"),
                        tl: {
                          hd: Tea_html.Attributes.$$class("btn-close"),
                          tl: /* [] */0
                        }
                      }, {
                        hd: Tea_html.text("Close"),
                        tl: /* [] */0
                      }),
                  tl: /* [] */0
                }
              }
            });
}

function renderBindingDetail(binding) {
  return Tea_html.div(undefined, undefined, {
              hd: Tea_html.Attributes.$$class("detail"),
              tl: /* [] */0
            }, {
              hd: Tea_html.h3(undefined, undefined, /* [] */0, {
                    hd: Tea_html.text("Binding"),
                    tl: /* [] */0
                  }),
              tl: {
                hd: Tea_html.dl(undefined, undefined, /* [] */0, {
                      hd: Tea_html.dt(undefined, undefined, /* [] */0, {
                            hd: Tea_html.text("ID"),
                            tl: /* [] */0
                          }),
                      tl: {
                        hd: Tea_html.dd(undefined, undefined, /* [] */0, {
                              hd: Tea_html.text(binding.id),
                              tl: /* [] */0
                            }),
                        tl: {
                          hd: Tea_html.dt(undefined, undefined, /* [] */0, {
                                hd: Tea_html.text("Consumer"),
                                tl: /* [] */0
                              }),
                          tl: {
                            hd: Tea_html.dd(undefined, undefined, /* [] */0, {
                                  hd: Tea_html.text(binding.consumer_id),
                                  tl: /* [] */0
                                }),
                            tl: {
                              hd: Tea_html.dt(undefined, undefined, /* [] */0, {
                                    hd: Tea_html.text("Slot"),
                                    tl: /* [] */0
                                  }),
                              tl: {
                                hd: Tea_html.dd(undefined, undefined, /* [] */0, {
                                      hd: Tea_html.text(binding.slot_id),
                                      tl: /* [] */0
                                    }),
                                tl: {
                                  hd: Tea_html.dt(undefined, undefined, /* [] */0, {
                                        hd: Tea_html.text("Provider"),
                                        tl: /* [] */0
                                      }),
                                  tl: {
                                    hd: Tea_html.dd(undefined, undefined, /* [] */0, {
                                          hd: Tea_html.text(binding.provider_id),
                                          tl: /* [] */0
                                        }),
                                    tl: /* [] */0
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }),
                tl: {
                  hd: Tea_html.button(undefined, undefined, {
                        hd: Tea_html.Events.onClick({
                              TAG: "UnbindSlot",
                              _0: binding.id
                            }),
                        tl: {
                          hd: Tea_html.Attributes.$$class("btn-danger"),
                          tl: /* [] */0
                        }
                      }, {
                        hd: Tea_html.text("Unbind"),
                        tl: /* [] */0
                      }),
                  tl: {
                    hd: Tea_html.button(undefined, undefined, {
                          hd: Tea_html.Events.onClick("ClearSelection"),
                          tl: {
                            hd: Tea_html.Attributes.$$class("btn-close"),
                            tl: /* [] */0
                          }
                        }, {
                          hd: Tea_html.text("Close"),
                          tl: /* [] */0
                        }),
                    tl: /* [] */0
                  }
                }
              }
            });
}

function renderPlanDetail(plan) {
  return Tea_html.div(undefined, undefined, {
              hd: Tea_html.Attributes.$$class("detail"),
              tl: /* [] */0
            }, {
              hd: Tea_html.h3(undefined, undefined, /* [] */0, {
                    hd: Tea_html.text(plan.name),
                    tl: /* [] */0
                  }),
              tl: {
                hd: Tea_html.dl(undefined, undefined, /* [] */0, {
                      hd: Tea_html.dt(undefined, undefined, /* [] */0, {
                            hd: Tea_html.text("ID"),
                            tl: /* [] */0
                          }),
                      tl: {
                        hd: Tea_html.dd(undefined, undefined, /* [] */0, {
                              hd: Tea_html.text(plan.id),
                              tl: /* [] */0
                            }),
                        tl: {
                          hd: Tea_html.dt(undefined, undefined, /* [] */0, {
                                hd: Tea_html.text("Status"),
                                tl: /* [] */0
                              }),
                          tl: {
                            hd: Tea_html.dd(undefined, undefined, /* [] */0, {
                                  hd: Tea_html.text(planStatusToString(plan.status)),
                                  tl: /* [] */0
                                }),
                            tl: {
                              hd: Tea_html.dt(undefined, undefined, /* [] */0, {
                                    hd: Tea_html.text("Description"),
                                    tl: /* [] */0
                                  }),
                              tl: {
                                hd: Tea_html.dd(undefined, undefined, /* [] */0, {
                                      hd: Tea_html.text(Core__Option.getOr(plan.description, "-")),
                                      tl: /* [] */0
                                    }),
                                tl: /* [] */0
                              }
                            }
                          }
                        }
                      }
                    }),
                tl: {
                  hd: Tea_html.button(undefined, undefined, {
                        hd: Tea_html.Events.onClick("ClearSelection"),
                        tl: {
                          hd: Tea_html.Attributes.$$class("btn-close"),
                          tl: /* [] */0
                        }
                      }, {
                        hd: Tea_html.text("Close"),
                        tl: /* [] */0
                      }),
                  tl: /* [] */0
                }
              }
            });
}

function renderStatCard(label, count) {
  return Tea_html.div(undefined, undefined, {
              hd: Tea_html.Attributes.$$class("stat-card"),
              tl: /* [] */0
            }, {
              hd: Tea_html.span(undefined, undefined, {
                    hd: Tea_html.Attributes.$$class("stat-count"),
                    tl: /* [] */0
                  }, {
                    hd: Tea_html.text(count.toString()),
                    tl: /* [] */0
                  }),
              tl: {
                hd: Tea_html.span(undefined, undefined, {
                      hd: Tea_html.Attributes.$$class("stat-label"),
                      tl: /* [] */0
                    }, {
                      hd: Tea_html.text(label),
                      tl: /* [] */0
                    }),
                tl: /* [] */0
              }
            });
}

function renderDashboard(model) {
  return Tea_html.div(undefined, undefined, {
              hd: Tea_html.Attributes.$$class("dashboard"),
              tl: /* [] */0
            }, {
              hd: Tea_html.div(undefined, undefined, {
                    hd: Tea_html.Attributes.$$class("stats-row"),
                    tl: /* [] */0
                  }, {
                    hd: renderStatCard("Repositories", model.repos.length),
                    tl: {
                      hd: renderStatCard("Edges", model.edges.length),
                      tl: {
                        hd: renderStatCard("Groups", model.groups.length),
                        tl: {
                          hd: renderStatCard("Slots", model.slots.length),
                          tl: {
                            hd: renderStatCard("Plans", model.plans.length),
                            tl: /* [] */0
                          }
                        }
                      }
                    }
                  }),
              tl: {
                hd: Tea_html.div(undefined, undefined, {
                      hd: Tea_html.Attributes.id("graph-container"),
                      tl: {
                        hd: Tea_html.Attributes.$$class("graph-container"),
                        tl: /* [] */0
                      }
                    }, /* [] */0),
                tl: /* [] */0
              }
            });
}

function renderReposList(model) {
  var q = model.searchQuery;
  var filtered = model.repos.filter(function (repo) {
        if (matchesSearch(q, repo.name)) {
          return true;
        } else {
          return matchesSearch(q, repo.owner);
        }
      });
  return Tea_html.div(undefined, undefined, {
              hd: Tea_html.Attributes.$$class("list-view"),
              tl: /* [] */0
            }, {
              hd: Tea_html.div(undefined, undefined, {
                    hd: Tea_html.Attributes.$$class("list-header"),
                    tl: /* [] */0
                  }, {
                    hd: Tea_html.h2(undefined, undefined, /* [] */0, {
                          hd: Tea_html.text("Repositories"),
                          tl: /* [] */0
                        }),
                    tl: /* [] */0
                  }),
              tl: {
                hd: Tea_html.ul(undefined, undefined, {
                      hd: Tea_html.Attributes.$$class("item-list"),
                      tl: /* [] */0
                    }, Belt_List.fromArray(filtered.map(function (repo) {
                              return Tea_html.li(undefined, undefined, {
                                          hd: Tea_html.Attributes.$$class("item"),
                                          tl: {
                                            hd: Tea_html.Events.onClick({
                                                  TAG: "SelectRepo",
                                                  _0: repo
                                                }),
                                            tl: /* [] */0
                                          }
                                        }, {
                                          hd: Tea_html.span(undefined, undefined, {
                                                hd: Tea_html.Attributes.$$class("item-name"),
                                                tl: /* [] */0
                                              }, {
                                                hd: Tea_html.text(repo.name),
                                                tl: /* [] */0
                                              }),
                                          tl: {
                                            hd: Tea_html.span(undefined, undefined, {
                                                  hd: Tea_html.Attributes.$$class("item-meta"),
                                                  tl: /* [] */0
                                                }, {
                                                  hd: Tea_html.text(repo.owner + " | " + forgeToString(repo.forge)),
                                                  tl: /* [] */0
                                                }),
                                            tl: /* [] */0
                                          }
                                        });
                            }))),
                tl: /* [] */0
              }
            });
}

function renderEdgesList(model) {
  var q = model.searchQuery;
  var filtered = model.edges.filter(function (edge) {
        if (matchesSearch(q, Core__Option.getOr(edge.label, "")) || matchesSearch(q, edge.from)) {
          return true;
        } else {
          return matchesSearch(q, edge.to);
        }
      });
  var f = model.openForm;
  var tmp;
  if (typeof f !== "object" || f.TAG !== "EdgeForm") {
    tmp = Tea_html.noNode;
  } else {
    var f$1 = f._0;
    tmp = Tea_html.div(undefined, undefined, {
          hd: Tea_html.Attributes.$$class("creation-form"),
          tl: /* [] */0
        }, {
          hd: Tea_html.h3(undefined, undefined, /* [] */0, {
                hd: Tea_html.text("Add Edge"),
                tl: /* [] */0
              }),
          tl: {
            hd: formSelect("From", "from", f$1.from, model.repos.map(function (r) {
                      return [
                              r.id,
                              r.name
                            ];
                    })),
            tl: {
              hd: formSelect("To", "to", f$1.to_, model.repos.map(function (r) {
                        return [
                                r.id,
                                r.name
                              ];
                      })),
              tl: {
                hd: formSelect("Relation", "rel", f$1.rel, [
                      [
                        "uses",
                        "Uses"
                      ],
                      [
                        "provides",
                        "Provides"
                      ],
                      [
                        "extends",
                        "Extends"
                      ],
                      [
                        "mirrors",
                        "Mirrors"
                      ],
                      [
                        "replaces",
                        "Replaces"
                      ]
                    ]),
                tl: {
                  hd: formActions(),
                  tl: /* [] */0
                }
              }
            }
          }
        });
  }
  return Tea_html.div(undefined, undefined, {
              hd: Tea_html.Attributes.$$class("list-view"),
              tl: /* [] */0
            }, {
              hd: Tea_html.div(undefined, undefined, {
                    hd: Tea_html.Attributes.$$class("list-header"),
                    tl: /* [] */0
                  }, {
                    hd: Tea_html.h2(undefined, undefined, /* [] */0, {
                          hd: Tea_html.text("Edges"),
                          tl: /* [] */0
                        }),
                    tl: {
                      hd: Tea_html.button(undefined, undefined, {
                            hd: Tea_html.Events.onClick("OpenEdgeForm"),
                            tl: {
                              hd: Tea_html.Attributes.$$class("btn-add"),
                              tl: /* [] */0
                            }
                          }, {
                            hd: Tea_html.text("+"),
                            tl: /* [] */0
                          }),
                      tl: /* [] */0
                    }
                  }),
              tl: {
                hd: tmp,
                tl: {
                  hd: Tea_html.ul(undefined, undefined, {
                        hd: Tea_html.Attributes.$$class("item-list"),
                        tl: /* [] */0
                      }, Belt_List.fromArray(filtered.map(function (edge) {
                                return Tea_html.li(undefined, undefined, {
                                            hd: Tea_html.Attributes.$$class("item"),
                                            tl: {
                                              hd: Tea_html.Events.onClick({
                                                    TAG: "SelectEdge",
                                                    _0: edge
                                                  }),
                                              tl: /* [] */0
                                            }
                                          }, {
                                            hd: Tea_html.span(undefined, undefined, {
                                                  hd: Tea_html.Attributes.$$class("item-name"),
                                                  tl: /* [] */0
                                                }, {
                                                  hd: Tea_html.text(Core__Option.getOr(edge.label, edge.id)),
                                                  tl: /* [] */0
                                                }),
                                            tl: {
                                              hd: Tea_html.span(undefined, undefined, {
                                                    hd: Tea_html.Attributes.$$class("item-meta"),
                                                    tl: /* [] */0
                                                  }, {
                                                    hd: Tea_html.text(edge.from + " -> " + edge.to),
                                                    tl: /* [] */0
                                                  }),
                                              tl: /* [] */0
                                            }
                                          });
                              }))),
                  tl: /* [] */0
                }
              }
            });
}

function renderGroupsList(model) {
  var q = model.searchQuery;
  var filtered = model.groups.filter(function (group) {
        return matchesSearch(q, group.name);
      });
  var f = model.openForm;
  var tmp;
  if (typeof f !== "object" || f.TAG !== "GroupForm") {
    tmp = Tea_html.noNode;
  } else {
    var f$1 = f._0;
    tmp = Tea_html.div(undefined, undefined, {
          hd: Tea_html.Attributes.$$class("creation-form"),
          tl: /* [] */0
        }, {
          hd: Tea_html.h3(undefined, undefined, /* [] */0, {
                hd: Tea_html.text("Create Group"),
                tl: /* [] */0
              }),
          tl: {
            hd: formField("Name", "name", f$1.name, "Group name"),
            tl: {
              hd: formField("Description", "description", f$1.description, "Optional description"),
              tl: {
                hd: formActions(),
                tl: /* [] */0
              }
            }
          }
        });
  }
  return Tea_html.div(undefined, undefined, {
              hd: Tea_html.Attributes.$$class("list-view"),
              tl: /* [] */0
            }, {
              hd: Tea_html.div(undefined, undefined, {
                    hd: Tea_html.Attributes.$$class("list-header"),
                    tl: /* [] */0
                  }, {
                    hd: Tea_html.h2(undefined, undefined, /* [] */0, {
                          hd: Tea_html.text("Groups"),
                          tl: /* [] */0
                        }),
                    tl: {
                      hd: Tea_html.button(undefined, undefined, {
                            hd: Tea_html.Events.onClick("OpenGroupForm"),
                            tl: {
                              hd: Tea_html.Attributes.$$class("btn-add"),
                              tl: /* [] */0
                            }
                          }, {
                            hd: Tea_html.text("+"),
                            tl: /* [] */0
                          }),
                      tl: /* [] */0
                    }
                  }),
              tl: {
                hd: tmp,
                tl: {
                  hd: Tea_html.ul(undefined, undefined, {
                        hd: Tea_html.Attributes.$$class("item-list"),
                        tl: /* [] */0
                      }, Belt_List.fromArray(filtered.map(function (group) {
                                return Tea_html.li(undefined, undefined, {
                                            hd: Tea_html.Attributes.$$class("item"),
                                            tl: {
                                              hd: Tea_html.Events.onClick({
                                                    TAG: "SelectGroup",
                                                    _0: group
                                                  }),
                                              tl: /* [] */0
                                            }
                                          }, {
                                            hd: Tea_html.span(undefined, undefined, {
                                                  hd: Tea_html.Attributes.$$class("item-name"),
                                                  tl: /* [] */0
                                                }, {
                                                  hd: Tea_html.text(group.name),
                                                  tl: /* [] */0
                                                }),
                                            tl: {
                                              hd: Tea_html.span(undefined, undefined, {
                                                    hd: Tea_html.Attributes.$$class("item-meta"),
                                                    tl: /* [] */0
                                                  }, {
                                                    hd: Tea_html.text(group.members.length.toString() + " members"),
                                                    tl: /* [] */0
                                                  }),
                                              tl: /* [] */0
                                            }
                                          });
                              }))),
                  tl: /* [] */0
                }
              }
            });
}

function renderAspectsList(model) {
  var q = model.searchQuery;
  var filtered = model.aspects.filter(function (aspect) {
        if (matchesSearch(q, aspect.aspect_id)) {
          return true;
        } else {
          return matchesSearch(q, aspect.target);
        }
      });
  var f = model.openForm;
  var tmp;
  if (typeof f !== "object" || f.TAG !== "AspectForm") {
    tmp = Tea_html.noNode;
  } else {
    var f$1 = f._0;
    tmp = Tea_html.div(undefined, undefined, {
          hd: Tea_html.Attributes.$$class("creation-form"),
          tl: /* [] */0
        }, {
          hd: Tea_html.h3(undefined, undefined, /* [] */0, {
                hd: Tea_html.text("Tag Aspect"),
                tl: /* [] */0
              }),
          tl: {
            hd: formSelect("Target", "target", f$1.target, model.repos.map(function (r) {
                      return [
                              r.id,
                              r.name
                            ];
                    })),
            tl: {
              hd: formSelect("Aspect", "aspectId", f$1.aspectId, [
                    [
                      "security",
                      "Security"
                    ],
                    [
                      "reliability",
                      "Reliability"
                    ],
                    [
                      "maintainability",
                      "Maintainability"
                    ],
                    [
                      "performance",
                      "Performance"
                    ],
                    [
                      "supply-chain",
                      "Supply Chain"
                    ],
                    [
                      "observability",
                      "Observability"
                    ]
                  ]),
              tl: {
                hd: formSelect("Weight", "weight", f$1.weight, [
                      [
                        "0",
                        "0 - None"
                      ],
                      [
                        "1",
                        "1 - Low"
                      ],
                      [
                        "2",
                        "2 - Medium"
                      ],
                      [
                        "3",
                        "3 - High"
                      ]
                    ]),
                tl: {
                  hd: formSelect("Polarity", "polarity", f$1.polarity, [
                        [
                          "risk",
                          "Risk"
                        ],
                        [
                          "strength",
                          "Strength"
                        ],
                        [
                          "neutral",
                          "Neutral"
                        ]
                      ]),
                  tl: {
                    hd: formField("Reason", "reason", f$1.reason, "Why this annotation?"),
                    tl: {
                      hd: formActions(),
                      tl: /* [] */0
                    }
                  }
                }
              }
            }
          }
        });
  }
  return Tea_html.div(undefined, undefined, {
              hd: Tea_html.Attributes.$$class("list-view"),
              tl: /* [] */0
            }, {
              hd: Tea_html.div(undefined, undefined, {
                    hd: Tea_html.Attributes.$$class("list-header"),
                    tl: /* [] */0
                  }, {
                    hd: Tea_html.h2(undefined, undefined, /* [] */0, {
                          hd: Tea_html.text("Aspect Annotations"),
                          tl: /* [] */0
                        }),
                    tl: {
                      hd: Tea_html.button(undefined, undefined, {
                            hd: Tea_html.Events.onClick("OpenAspectForm"),
                            tl: {
                              hd: Tea_html.Attributes.$$class("btn-add"),
                              tl: /* [] */0
                            }
                          }, {
                            hd: Tea_html.text("+"),
                            tl: /* [] */0
                          }),
                      tl: /* [] */0
                    }
                  }),
              tl: {
                hd: tmp,
                tl: {
                  hd: Tea_html.ul(undefined, undefined, {
                        hd: Tea_html.Attributes.$$class("item-list"),
                        tl: /* [] */0
                      }, Belt_List.fromArray(filtered.map(function (aspect) {
                                return Tea_html.li(undefined, undefined, {
                                            hd: Tea_html.Attributes.$$class("item"),
                                            tl: {
                                              hd: Tea_html.Events.onClick({
                                                    TAG: "SelectAspect",
                                                    _0: aspect
                                                  }),
                                              tl: /* [] */0
                                            }
                                          }, {
                                            hd: Tea_html.span(undefined, undefined, {
                                                  hd: Tea_html.Attributes.$$class("item-name"),
                                                  tl: /* [] */0
                                                }, {
                                                  hd: Tea_html.text(aspect.aspect_id),
                                                  tl: /* [] */0
                                                }),
                                            tl: {
                                              hd: Tea_html.span(undefined, undefined, {
                                                    hd: Tea_html.Attributes.$$class("item-meta"),
                                                    tl: /* [] */0
                                                  }, {
                                                    hd: Tea_html.text("on " + aspect.target),
                                                    tl: /* [] */0
                                                  }),
                                              tl: /* [] */0
                                            }
                                          });
                              }))),
                  tl: /* [] */0
                }
              }
            });
}

function renderSlotsList(model) {
  var q = model.searchQuery;
  var filteredSlots = model.slots.filter(function (slot) {
        if (matchesSearch(q, slot.name)) {
          return true;
        } else {
          return matchesSearch(q, slot.category);
        }
      });
  var filteredProviders = model.providers.filter(function (provider) {
        return matchesSearch(q, provider.name);
      });
  var f = model.openForm;
  var tmp;
  if (typeof f !== "object" || f.TAG !== "SlotForm") {
    tmp = Tea_html.noNode;
  } else {
    var f$1 = f._0;
    tmp = Tea_html.div(undefined, undefined, {
          hd: Tea_html.Attributes.$$class("creation-form"),
          tl: /* [] */0
        }, {
          hd: Tea_html.h3(undefined, undefined, /* [] */0, {
                hd: Tea_html.text("Create Slot"),
                tl: /* [] */0
              }),
          tl: {
            hd: formField("Name", "name", f$1.name, "Slot name"),
            tl: {
              hd: formField("Category", "category", f$1.category, "e.g. database, auth, cache"),
              tl: {
                hd: formField("Description", "description", f$1.description, "What this slot provides"),
                tl: {
                  hd: formField("Capabilities", "capabilities", f$1.capabilities, "cap1, cap2, ..."),
                  tl: {
                    hd: formActions(),
                    tl: /* [] */0
                  }
                }
              }
            }
          }
        });
  }
  var f$2 = model.openForm;
  var tmp$1;
  if (typeof f$2 !== "object" || f$2.TAG !== "ProviderForm") {
    tmp$1 = Tea_html.noNode;
  } else {
    var f$3 = f$2._0;
    tmp$1 = Tea_html.div(undefined, undefined, {
          hd: Tea_html.Attributes.$$class("creation-form"),
          tl: /* [] */0
        }, {
          hd: Tea_html.h3(undefined, undefined, /* [] */0, {
                hd: Tea_html.text("Create Provider"),
                tl: /* [] */0
              }),
          tl: {
            hd: formField("Name", "name", f$3.name, "Provider name"),
            tl: {
              hd: formSelect("Slot", "slotId", f$3.slotId, model.slots.map(function (s) {
                        return [
                                s.id,
                                s.name
                              ];
                      })),
              tl: {
                hd: formSelect("Type", "providerType", f$3.providerType, [
                      [
                        "local",
                        "Local"
                      ],
                      [
                        "ecosystem",
                        "Ecosystem"
                      ],
                      [
                        "external",
                        "External"
                      ],
                      [
                        "stub",
                        "Stub"
                      ]
                    ]),
                tl: {
                  hd: formSelect("Repository", "repoId", f$3.repoId, model.repos.map(function (r) {
                            return [
                                    r.id,
                                    r.name
                                  ];
                          })),
                  tl: {
                    hd: formField("Capabilities", "capabilities", f$3.capabilities, "cap1, cap2, ..."),
                    tl: {
                      hd: formField("Priority", "priority", f$3.priority, "100"),
                      tl: {
                        hd: formCheckbox("Fallback provider", "isFallback", f$3.isFallback),
                        tl: {
                          hd: formActions(),
                          tl: /* [] */0
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        });
  }
  return Tea_html.div(undefined, undefined, {
              hd: Tea_html.Attributes.$$class("list-view"),
              tl: /* [] */0
            }, {
              hd: Tea_html.div(undefined, undefined, {
                    hd: Tea_html.Attributes.$$class("list-header"),
                    tl: /* [] */0
                  }, {
                    hd: Tea_html.h2(undefined, undefined, /* [] */0, {
                          hd: Tea_html.text("Slots"),
                          tl: /* [] */0
                        }),
                    tl: {
                      hd: Tea_html.button(undefined, undefined, {
                            hd: Tea_html.Events.onClick("OpenSlotForm"),
                            tl: {
                              hd: Tea_html.Attributes.$$class("btn-add"),
                              tl: /* [] */0
                            }
                          }, {
                            hd: Tea_html.text("+"),
                            tl: /* [] */0
                          }),
                      tl: /* [] */0
                    }
                  }),
              tl: {
                hd: tmp,
                tl: {
                  hd: Tea_html.ul(undefined, undefined, {
                        hd: Tea_html.Attributes.$$class("item-list"),
                        tl: /* [] */0
                      }, Belt_List.fromArray(filteredSlots.map(function (slot) {
                                return Tea_html.li(undefined, undefined, {
                                            hd: Tea_html.Attributes.$$class("item"),
                                            tl: {
                                              hd: Tea_html.Events.onClick({
                                                    TAG: "SelectSlot",
                                                    _0: slot
                                                  }),
                                              tl: /* [] */0
                                            }
                                          }, {
                                            hd: Tea_html.span(undefined, undefined, {
                                                  hd: Tea_html.Attributes.$$class("item-name"),
                                                  tl: /* [] */0
                                                }, {
                                                  hd: Tea_html.text(slot.name),
                                                  tl: /* [] */0
                                                }),
                                            tl: {
                                              hd: Tea_html.span(undefined, undefined, {
                                                    hd: Tea_html.Attributes.$$class("item-meta"),
                                                    tl: /* [] */0
                                                  }, {
                                                    hd: Tea_html.text("[" + slot.category + "]"),
                                                    tl: /* [] */0
                                                  }),
                                              tl: /* [] */0
                                            }
                                          });
                              }))),
                  tl: {
                    hd: Tea_html.div(undefined, undefined, {
                          hd: Tea_html.Attributes.$$class("list-header"),
                          tl: /* [] */0
                        }, {
                          hd: Tea_html.h2(undefined, undefined, /* [] */0, {
                                hd: Tea_html.text("Providers"),
                                tl: /* [] */0
                              }),
                          tl: {
                            hd: Tea_html.button(undefined, undefined, {
                                  hd: Tea_html.Events.onClick("OpenProviderForm"),
                                  tl: {
                                    hd: Tea_html.Attributes.$$class("btn-add"),
                                    tl: /* [] */0
                                  }
                                }, {
                                  hd: Tea_html.text("+"),
                                  tl: /* [] */0
                                }),
                            tl: /* [] */0
                          }
                        }),
                    tl: {
                      hd: tmp$1,
                      tl: {
                        hd: Tea_html.ul(undefined, undefined, {
                              hd: Tea_html.Attributes.$$class("item-list"),
                              tl: /* [] */0
                            }, Belt_List.fromArray(filteredProviders.map(function (provider) {
                                      return Tea_html.li(undefined, undefined, {
                                                  hd: Tea_html.Attributes.$$class("item"),
                                                  tl: {
                                                    hd: Tea_html.Events.onClick({
                                                          TAG: "SelectProvider",
                                                          _0: provider
                                                        }),
                                                    tl: /* [] */0
                                                  }
                                                }, {
                                                  hd: Tea_html.span(undefined, undefined, {
                                                        hd: Tea_html.Attributes.$$class("item-name"),
                                                        tl: /* [] */0
                                                      }, {
                                                        hd: Tea_html.text(provider.name),
                                                        tl: /* [] */0
                                                      }),
                                                  tl: {
                                                    hd: Tea_html.span(undefined, undefined, {
                                                          hd: Tea_html.Attributes.$$class("item-meta"),
                                                          tl: /* [] */0
                                                        }, {
                                                          hd: Tea_html.text(providerTypeToString(provider.provider_type)),
                                                          tl: /* [] */0
                                                        }),
                                                    tl: /* [] */0
                                                  }
                                                });
                                    }))),
                        tl: /* [] */0
                      }
                    }
                  }
                }
              }
            });
}

function renderPlansList(model) {
  var q = model.searchQuery;
  var filtered = model.plans.filter(function (plan) {
        return matchesSearch(q, plan.name);
      });
  return Tea_html.div(undefined, undefined, {
              hd: Tea_html.Attributes.$$class("list-view"),
              tl: /* [] */0
            }, {
              hd: Tea_html.div(undefined, undefined, {
                    hd: Tea_html.Attributes.$$class("list-header"),
                    tl: /* [] */0
                  }, {
                    hd: Tea_html.h2(undefined, undefined, /* [] */0, {
                          hd: Tea_html.text("Plans"),
                          tl: /* [] */0
                        }),
                    tl: /* [] */0
                  }),
              tl: {
                hd: Tea_html.ul(undefined, undefined, {
                      hd: Tea_html.Attributes.$$class("item-list"),
                      tl: /* [] */0
                    }, Belt_List.fromArray(filtered.map(function (plan) {
                              return Tea_html.li(undefined, undefined, {
                                          hd: Tea_html.Attributes.$$class("item"),
                                          tl: {
                                            hd: Tea_html.Events.onClick({
                                                  TAG: "SelectPlan",
                                                  _0: plan
                                                }),
                                            tl: /* [] */0
                                          }
                                        }, {
                                          hd: Tea_html.span(undefined, undefined, {
                                                hd: Tea_html.Attributes.$$class("item-name"),
                                                tl: /* [] */0
                                              }, {
                                                hd: Tea_html.text(plan.name),
                                                tl: /* [] */0
                                              }),
                                          tl: {
                                            hd: Tea_html.span(undefined, undefined, {
                                                  hd: Tea_html.Attributes.$$class("item-meta"),
                                                  tl: /* [] */0
                                                }, {
                                                  hd: Tea_html.text(planStatusToString(plan.status)),
                                                  tl: /* [] */0
                                                }),
                                            tl: /* [] */0
                                          }
                                        });
                            }))),
                tl: /* [] */0
              }
            });
}

function renderMainPanel(model) {
  var match = model.activeTab;
  var tmp;
  tmp = match === "Dashboard" ? Tea_html.noNode : Tea_html.div(undefined, undefined, {
          hd: Tea_html.Attributes.$$class("search-bar"),
          tl: /* [] */0
        }, {
          hd: Tea_html.input$p(undefined, undefined, {
                hd: Tea_html.Attributes.$$class("search-input"),
                tl: {
                  hd: Tea_html.Attributes.type$p("text"),
                  tl: {
                    hd: Tea_html.Attributes.placeholder("Search..."),
                    tl: {
                      hd: Tea_html.Attributes.value(model.searchQuery),
                      tl: {
                        hd: Tea_html.Events.onInput(undefined, (function (value) {
                                return {
                                        TAG: "SetSearchQuery",
                                        _0: value
                                      };
                              })),
                        tl: /* [] */0
                      }
                    }
                  }
                }
              }, /* [] */0),
          tl: /* [] */0
        });
  var tmp$1;
  if (model.loading) {
    tmp$1 = Tea_html.div(undefined, undefined, {
          hd: Tea_html.Attributes.$$class("loading"),
          tl: /* [] */0
        }, {
          hd: Tea_html.text("Loading..."),
          tl: /* [] */0
        });
  } else {
    var match$1 = model.activeTab;
    switch (match$1) {
      case "Dashboard" :
          tmp$1 = renderDashboard(model);
          break;
      case "Repos" :
          tmp$1 = renderReposList(model);
          break;
      case "Edges" :
          tmp$1 = renderEdgesList(model);
          break;
      case "Groups" :
          tmp$1 = renderGroupsList(model);
          break;
      case "Aspects" :
          tmp$1 = renderAspectsList(model);
          break;
      case "Slots" :
          tmp$1 = renderSlotsList(model);
          break;
      case "Plans" :
          tmp$1 = renderPlansList(model);
          break;
      
    }
  }
  return Tea_html.main(undefined, undefined, {
              hd: Tea_html.Attributes.$$class("main-panel"),
              tl: /* [] */0
            }, {
              hd: tmp,
              tl: {
                hd: tmp$1,
                tl: /* [] */0
              }
            });
}

function renderDetailPanel(model) {
  var repo = model.selectedItem;
  var tmp;
  if (typeof repo !== "object") {
    tmp = Tea_html.div(undefined, undefined, {
          hd: Tea_html.Attributes.$$class("no-selection"),
          tl: /* [] */0
        }, {
          hd: Tea_html.text("Select an item to view details"),
          tl: /* [] */0
        });
  } else {
    switch (repo.TAG) {
      case "SelectedRepo" :
          tmp = renderRepoDetail(repo._0);
          break;
      case "SelectedEdge" :
          tmp = renderEdgeDetail(repo._0);
          break;
      case "SelectedGroup" :
          tmp = renderGroupDetail(repo._0);
          break;
      case "SelectedAspect" :
          tmp = renderAspectDetail(repo._0);
          break;
      case "SelectedSlot" :
          tmp = renderSlotDetail(repo._0);
          break;
      case "SelectedProvider" :
          tmp = renderProviderDetail(repo._0);
          break;
      case "SelectedBinding" :
          tmp = renderBindingDetail(repo._0);
          break;
      case "SelectedPlan" :
          tmp = renderPlanDetail(repo._0);
          break;
      
    }
  }
  return Tea_html.aside(undefined, undefined, {
              hd: Tea_html.Attributes.$$class("detail-panel"),
              tl: /* [] */0
            }, {
              hd: tmp,
              tl: /* [] */0
            });
}

function renderPanllStatus(model) {
  var panll = model.panll;
  var match = panll.connection;
  var match$1;
  match$1 = typeof match !== "object" ? (
      match === "PanllDisconnected" ? [
          "panll-disconnected",
          "PanLL: Off"
        ] : [
          "panll-connecting",
          "PanLL: ..."
        ]
    ) : (
      match.TAG === "PanllConnected" ? [
          "panll-connected",
          "PanLL: On"
        ] : [
          "panll-error",
          "PanLL: Err"
        ]
    );
  var match$2 = panll.connection;
  var tmp;
  var exit = 0;
  if (typeof match$2 !== "object") {
    if (match$2 === "PanllDisconnected") {
      exit = 1;
    } else {
      tmp = Tea_html.noNode;
    }
  } else if (match$2.TAG === "PanllConnected") {
    tmp = Tea_html.div(undefined, undefined, /* [] */0, {
          hd: Tea_html.button(undefined, undefined, {
                hd: Tea_html.Events.onClick("PanllSyncGraph"),
                tl: {
                  hd: Tea_html.Attributes.$$class("btn-panll"),
                  tl: /* [] */0
                }
              }, {
                hd: Tea_html.text("Sync"),
                tl: /* [] */0
              }),
          tl: {
            hd: Tea_html.button(undefined, undefined, {
                  hd: Tea_html.Events.onClick("PanllDisconnect"),
                  tl: {
                    hd: Tea_html.Attributes.$$class("btn-panll-disconnect"),
                    tl: /* [] */0
                  }
                }, {
                  hd: Tea_html.text("X"),
                  tl: /* [] */0
                }),
            tl: /* [] */0
          }
        });
  } else {
    exit = 1;
  }
  if (exit === 1) {
    tmp = Tea_html.button(undefined, undefined, {
          hd: Tea_html.Events.onClick("PanllConnect"),
          tl: {
            hd: Tea_html.Attributes.$$class("btn-panll"),
            tl: /* [] */0
          }
        }, {
          hd: Tea_html.text("Connect"),
          tl: /* [] */0
        });
  }
  return Tea_html.div(undefined, undefined, {
              hd: Tea_html.Attributes.$$class("panll-status " + match$1[0]),
              tl: /* [] */0
            }, {
              hd: Tea_html.span(undefined, undefined, {
                    hd: Tea_html.Attributes.$$class("panll-indicator"),
                    tl: /* [] */0
                  }, {
                    hd: Tea_html.text(match$1[1]),
                    tl: /* [] */0
                  }),
              tl: {
                hd: tmp,
                tl: /* [] */0
              }
            });
}

function renderHeader(model) {
  return Tea_html.header(undefined, undefined, {
              hd: Tea_html.Attributes.$$class("app-header"),
              tl: /* [] */0
            }, {
              hd: Tea_html.h1(undefined, undefined, /* [] */0, {
                    hd: Tea_html.text("Reposystem"),
                    tl: /* [] */0
                  }),
              tl: {
                hd: Tea_html.span(undefined, undefined, {
                      hd: Tea_html.Attributes.$$class("tagline"),
                      tl: /* [] */0
                    }, {
                      hd: Tea_html.text("Railway yard for your repository ecosystem"),
                      tl: /* [] */0
                    }),
                tl: {
                  hd: Tea_html.div(undefined, undefined, {
                        hd: Tea_html.Attributes.$$class("header-actions"),
                        tl: /* [] */0
                      }, {
                        hd: renderPanllStatus(model),
                        tl: {
                          hd: Tea_html.button(undefined, undefined, {
                                hd: Tea_html.Events.onClick("SaveGraph"),
                                tl: {
                                  hd: Tea_html.Attributes.$$class("btn-save"),
                                  tl: /* [] */0
                                }
                              }, {
                                hd: Tea_html.text("Save"),
                                tl: /* [] */0
                              }),
                          tl: {
                            hd: Tea_html.button(undefined, undefined, {
                                  hd: Tea_html.Events.onClick("LoadAllData"),
                                  tl: {
                                    hd: Tea_html.Attributes.$$class("btn-refresh"),
                                    tl: /* [] */0
                                  }
                                }, {
                                  hd: Tea_html.text("Refresh"),
                                  tl: /* [] */0
                                }),
                            tl: /* [] */0
                          }
                        }
                      }),
                  tl: /* [] */0
                }
              }
            });
}

function renderSidebar(model) {
  return Tea_html.nav(undefined, undefined, {
              hd: Tea_html.Attributes.$$class("sidebar"),
              tl: /* [] */0
            }, {
              hd: Tea_html.ul(undefined, undefined, {
                    hd: Tea_html.Attributes.$$class("tab-list"),
                    tl: /* [] */0
                  }, Belt_List.fromArray(Model.allTabs.map(function (tab) {
                            var isActive = model.activeTab === tab;
                            return Tea_html.li(undefined, undefined, {
                                        hd: Tea_html.Attributes.$$class(isActive ? "tab-item active" : "tab-item"),
                                        tl: {
                                          hd: Tea_html.Events.onClick({
                                                TAG: "SetTab",
                                                _0: tab
                                              }),
                                          tl: /* [] */0
                                        }
                                      }, {
                                        hd: Tea_html.span(undefined, undefined, {
                                              hd: Tea_html.Attributes.$$class("tab-icon"),
                                              tl: /* [] */0
                                            }, {
                                              hd: Tea_html.text(tabIcon(tab)),
                                              tl: /* [] */0
                                            }),
                                        tl: {
                                          hd: Tea_html.span(undefined, undefined, {
                                                hd: Tea_html.Attributes.$$class("tab-label"),
                                                tl: /* [] */0
                                              }, {
                                                hd: Tea_html.text(Model.tabToString(tab)),
                                                tl: /* [] */0
                                              }),
                                          tl: {
                                            hd: Tea_html.span(undefined, undefined, {
                                                  hd: Tea_html.Attributes.$$class("tab-count"),
                                                  tl: /* [] */0
                                                }, {
                                                  hd: Tea_html.text(tabCount(model, tab)),
                                                  tl: /* [] */0
                                                }),
                                            tl: /* [] */0
                                          }
                                        }
                                      });
                          }))),
              tl: /* [] */0
            });
}

function renderError(model) {
  var err = model.error;
  if (err !== undefined) {
    return Tea_html.div(undefined, undefined, {
                hd: Tea_html.Attributes.$$class("error-toast"),
                tl: /* [] */0
              }, {
                hd: Tea_html.span(undefined, undefined, /* [] */0, {
                      hd: Tea_html.text(err),
                      tl: /* [] */0
                    }),
                tl: {
                  hd: Tea_html.button(undefined, undefined, {
                        hd: Tea_html.Events.onClick("DismissError"),
                        tl: {
                          hd: Tea_html.Attributes.$$class("btn-dismiss"),
                          tl: /* [] */0
                        }
                      }, {
                        hd: Tea_html.text("X"),
                        tl: /* [] */0
                      }),
                  tl: /* [] */0
                }
              });
  } else {
    return Tea_html.noNode;
  }
}

function view(model) {
  return Tea_html.div(undefined, undefined, {
              hd: Tea_html.Attributes.$$class("app"),
              tl: /* [] */0
            }, {
              hd: renderHeader(model),
              tl: {
                hd: Tea_html.div(undefined, undefined, {
                      hd: Tea_html.Attributes.$$class("main-content"),
                      tl: /* [] */0
                    }, {
                      hd: renderSidebar(model),
                      tl: {
                        hd: renderMainPanel(model),
                        tl: {
                          hd: renderDetailPanel(model),
                          tl: /* [] */0
                        }
                      }
                    }),
                tl: {
                  hd: renderError(model),
                  tl: /* [] */0
                }
              }
            });
}

export {
  matchesSearch ,
  tabIcon ,
  tabCount ,
  forgeToString ,
  providerTypeToString ,
  planStatusToString ,
  formField ,
  formSelect ,
  formCheckbox ,
  formActions ,
  renderRepoDetail ,
  renderEdgeDetail ,
  renderGroupDetail ,
  renderAspectDetail ,
  renderSlotDetail ,
  renderProviderDetail ,
  renderBindingDetail ,
  renderPlanDetail ,
  renderStatCard ,
  renderDashboard ,
  renderReposList ,
  renderEdgesList ,
  renderGroupsList ,
  renderAspectsList ,
  renderSlotsList ,
  renderPlansList ,
  renderMainPanel ,
  renderDetailPanel ,
  renderPanllStatus ,
  renderHeader ,
  renderSidebar ,
  renderError ,
  view ,
}
/* Tea_html Not a pure module */
