// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Random from "rescript/lib/es6/random.js";
import * as Tea_cmd from "./tea_cmd.res.js";
import * as PervasivesU from "rescript/lib/es6/pervasivesU.js";

Random.self_init();

var bool = {
  TAG: "Generator",
  _0: (function (state) {
      return Random.State.bool(state);
    })
};

function $$int(min, max) {
  var match = min < max ? [
      min,
      max
    ] : [
      max,
      min
    ];
  var max$1 = match[1];
  var min$1 = match[0];
  return {
          TAG: "Generator",
          _0: (function (state) {
              return min$1 + Random.State.$$int(state, (max$1 - min$1 | 0) + 1 | 0) | 0;
            })
        };
}

function $$float(min, max) {
  return {
          TAG: "Generator",
          _0: (function (state) {
              return min + Random.State.$$float(state, max - min);
            })
        };
}

function list(count, genCmd) {
  var genCmd$1 = genCmd._0;
  return {
          TAG: "Generator",
          _0: (function (state) {
              var _i = count;
              var _acc = /* [] */0;
              while(true) {
                var acc = _acc;
                var i = _i;
                if (i <= 0) {
                  return acc;
                }
                _acc = {
                  hd: genCmd$1(state),
                  tl: acc
                };
                _i = i - 1 | 0;
                continue ;
              };
            })
        };
}

function map(func, genCmd) {
  var genCmd$1 = genCmd._0;
  return {
          TAG: "Generator",
          _0: (function (state) {
              return func(genCmd$1(state));
            })
        };
}

function map2(func, genCmd1, genCmd2) {
  var genCmd2$1 = genCmd2._0;
  var genCmd1$1 = genCmd1._0;
  return {
          TAG: "Generator",
          _0: (function (state) {
              var res1 = genCmd1$1(state);
              var res2 = genCmd2$1(state);
              return func(res1, res2);
            })
        };
}

function map3(func, genCmd1, genCmd2, genCmd3) {
  var genCmd3$1 = genCmd3._0;
  var genCmd2$1 = genCmd2._0;
  var genCmd1$1 = genCmd1._0;
  return {
          TAG: "Generator",
          _0: (function (state) {
              var res1 = genCmd1$1(state);
              var res2 = genCmd2$1(state);
              var res3 = genCmd3$1(state);
              return func(res1, res2, res3);
            })
        };
}

function map4(func, genCmd1, genCmd2, genCmd3, genCmd4) {
  var genCmd4$1 = genCmd4._0;
  var genCmd3$1 = genCmd3._0;
  var genCmd2$1 = genCmd2._0;
  var genCmd1$1 = genCmd1._0;
  return {
          TAG: "Generator",
          _0: (function (state) {
              var res1 = genCmd1$1(state);
              var res2 = genCmd2$1(state);
              var res3 = genCmd3$1(state);
              var res4 = genCmd4$1(state);
              return func(res1, res2, res3, res4);
            })
        };
}

function map5(func, genCmd1, genCmd2, genCmd3, genCmd4, genCmd5) {
  var genCmd5$1 = genCmd5._0;
  var genCmd4$1 = genCmd4._0;
  var genCmd3$1 = genCmd3._0;
  var genCmd2$1 = genCmd2._0;
  var genCmd1$1 = genCmd1._0;
  return {
          TAG: "Generator",
          _0: (function (state) {
              var res1 = genCmd1$1(state);
              var res2 = genCmd2$1(state);
              var res3 = genCmd3$1(state);
              var res4 = genCmd4$1(state);
              var res5 = genCmd5$1(state);
              return func(res1, res2, res3, res4, res5);
            })
        };
}

function andThen(func, genCmd) {
  var genCmd$1 = genCmd._0;
  return {
          TAG: "Generator",
          _0: (function (state) {
              var res = genCmd$1(state);
              var userGen = func(res);
              return userGen._0(state);
            })
        };
}

function pair(gen1, gen2) {
  return map2((function (a, b) {
                return [
                        a,
                        b
                      ];
              }), gen1, gen2);
}

function generate(tagger, genCmd) {
  var genCmd$1 = genCmd._0;
  return Tea_cmd.call(function (callbacks) {
              var state = Random.get_state();
              var genValue = genCmd$1(state);
              Random.set_state(state);
              callbacks.contents.enqueue(tagger(genValue));
            });
}

function step(genCmd, state) {
  var newState = Random.State.copy(state._0);
  return [
          genCmd._0(newState),
          {
            TAG: "Seed",
            _0: newState
          }
        ];
}

function initialSeed(seed) {
  return {
          TAG: "Seed",
          _0: Random.State.make([seed])
        };
}

var minInt = PervasivesU.min_int;

var maxInt = PervasivesU.max_int;

var minFloat = PervasivesU.min_float;

var maxFloat = PervasivesU.max_float;

export {
  minInt ,
  maxInt ,
  minFloat ,
  maxFloat ,
  bool ,
  $$int ,
  $$float ,
  list ,
  map ,
  map2 ,
  map3 ,
  map4 ,
  map5 ,
  andThen ,
  pair ,
  generate ,
  step ,
  initialSeed ,
}
/*  Not a pure module */
