// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tea_cmd from "./tea_cmd.res.js";
import * as Tea_sub from "./tea_sub.res.js";

function every(key, interval, tagger) {
  var enableCall = function (callbacks) {
    var id = setInterval((function () {
            callbacks.enqueue(tagger(Date.now()));
          }), interval);
    return function () {
      clearInterval(id);
    };
  };
  return Tea_sub.registration(key, enableCall);
}

function delay(msTime, msg) {
  return Tea_cmd.call(function (callbacks) {
              setTimeout((function () {
                      callbacks.contents.enqueue(msg);
                    }), msTime);
            });
}

var second = 1000.0 * 1.0;

var minute = 60.0 * second;

var hour = 60.0 * minute;

function inMilliseconds(t) {
  return t;
}

function inSeconds(t) {
  return t / second;
}

function inMinutes(t) {
  return t / minute;
}

function inHours(t) {
  return t / hour;
}

var millisecond = 1.0;

export {
  every ,
  delay ,
  millisecond ,
  second ,
  minute ,
  hour ,
  inMilliseconds ,
  inSeconds ,
  inMinutes ,
  inHours ,
}
/* Tea_cmd Not a pure module */
