// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tea_sub from "./tea_sub.res.js";
import * as Tea_task from "./tea_task.res.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

function renderEvent(keyOpt, msg) {
  var key = keyOpt !== undefined ? keyOpt : "";
  var enableCall = function (callbacks) {
    callbacks.on({
          TAG: "AddRenderMsg",
          _0: msg
        });
    return function () {
      callbacks.on({
            TAG: "RemoveRenderMsg",
            _0: msg
          });
    };
  };
  return Tea_sub.registration(key, enableCall);
}

var length = Tea_task.nativeBinding(function (cb) {
      cb({
            TAG: "Ok",
            _0: localStorage.length
          });
    });

var clear = Tea_task.nativeBinding(function (cb) {
      cb({
            TAG: "Ok",
            _0: (localStorage.clear(), undefined)
          });
    });

function clearCmd() {
  return Tea_task.attemptOpt((function (param) {
                
              }), clear);
}

function key(idx) {
  return Tea_task.nativeBinding(function (cb) {
              cb({
                    TAG: "Ok",
                    _0: Caml_option.null_to_opt(localStorage.key(idx))
                  });
            });
}

function getItem(key) {
  return Tea_task.nativeBinding(function (cb) {
              cb({
                    TAG: "Ok",
                    _0: Caml_option.null_to_opt(localStorage.getItem(key))
                  });
            });
}

function removeItem(key) {
  return Tea_task.nativeBinding(function (cb) {
              cb({
                    TAG: "Ok",
                    _0: (localStorage.removeItem(key), undefined)
                  });
            });
}

function removeItemCmd(key) {
  return Tea_task.attemptOpt((function (param) {
                
              }), removeItem(key));
}

function setItem(key, value) {
  return Tea_task.nativeBinding(function (cb) {
              cb({
                    TAG: "Ok",
                    _0: (localStorage.setItem(key, value), undefined)
                  });
            });
}

function setItemCmd(key, value) {
  return Tea_task.attemptOpt((function (param) {
                
              }), setItem(key, value));
}

var LocalStorage = {
  length: length,
  clear: clear,
  clearCmd: clearCmd,
  key: key,
  getItem: getItem,
  removeItem: removeItem,
  removeItemCmd: removeItemCmd,
  setItem: setItem,
  setItemCmd: setItemCmd
};

export {
  renderEvent ,
  LocalStorage ,
}
/* length Not a pure module */
