// Generated by ReScript, PLEASE EDIT WITH CARE

import * as List from "rescript/lib/es6/list.js";
import * as Vdom from "./vdom.res.js";

function batch(cmds) {
  return {
          TAG: "Batch",
          _0: cmds
        };
}

function call(call$1) {
  return {
          TAG: "EnqueueCall",
          _0: call$1
        };
}

function fnMsg(fnMsg$1) {
  return {
          TAG: "EnqueueCall",
          _0: (function (callbacks) {
              callbacks.contents.enqueue(fnMsg$1());
            })
        };
}

function msg(msg$1) {
  return {
          TAG: "EnqueueCall",
          _0: (function (callbacks) {
              callbacks.contents.enqueue(msg$1);
            })
        };
}

function run(_callbacks, _x) {
  while(true) {
    var x = _x;
    var callbacks = _callbacks;
    if (typeof x !== "object") {
      return ;
    }
    switch (x.TAG) {
      case "Mapper" :
          var subCallbacks = x._0(callbacks);
          _x = x._1;
          _callbacks = subCallbacks;
          continue ;
      case "Batch" :
          return List.fold_left((function(callbacks){
                    return function (param, cmd) {
                      run(callbacks, cmd);
                    }
                    }(callbacks)), undefined, x._0);
      case "EnqueueCall" :
          return x._0(callbacks);
      
    }
  };
}

function map(func, cmd) {
  var mapper = function (callbacks) {
    return Vdom.wrapCallbacks(func, callbacks);
  };
  return {
          TAG: "Mapper",
          _0: mapper,
          _1: cmd
        };
}

var none = "NoCmd";

export {
  none ,
  batch ,
  call ,
  fnMsg ,
  msg ,
  run ,
  map ,
}
/* Vdom Not a pure module */
