// SPDX-License-Identifier: MPL-2.0
// Copyright (c) Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
/*
**
** The C code is generated by [ATS/Postiats-0-4-1]
** The starting compilation time is: 2026-5-18: 19h:49m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE_
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
#endif /* _ATS_CCOMP_HEADER_NONE_ */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE_
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/integer_long.cats"
#include "prelude/CATS/integer_size.cats"
#include "prelude/CATS/integer_short.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/fprintf.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE_ */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER_
//
#include _ATS_CCOMP_PRELUDE_USER_
//
#endif /* _ATS_CCOMP_PRELUDE_USER_ */
/*
** for user2-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER2_
//
#include _ATS_CCOMP_PRELUDE_USER2_
//
#endif /* _ATS_CCOMP_PRELUDE_USER2_ */

/*
staload-prologues(beg)
*/
/*
/usr/lib/ats2-postiats-0.4.2/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
/usr/lib/ats2-postiats-0.4.2/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/usr/lib/ats2-postiats-0.4.2/libats/libc/SATS/sys/stat.sats: 1390(line=36, offs=1) -- 1440(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/stat.cats"
/*
/usr/lib/ats2-postiats-0.4.2/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/usr/lib/ats2-postiats-0.4.2/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
/usr/lib/ats2-postiats-0.4.2/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
typedef
ATSstruct {
atstkind_t0ype(atstype_int) atslab__success_count ;
atstkind_t0ype(atstype_int) atslab__failure_count ;
atstkind_t0ype(atstype_int) atslab__skipped_count ;
atstkind_type(atstype_ptrk) atslab__message ;
} postiats_tyrec_0 ;
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_extfun(_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_types_056_sats__is_valid_spdx, (atstkind_type(atstype_ptrk)), atstkind_t0ype(atstype_bool)) ;
ATSdyncst_extfun(_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_git_sync_056_sats__execute_git_sync_operation, (atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_int), atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_bool)), postiats_tyrec_0) ;
ATSdyncst_mac(atspre_g0int2int_int_int)
ATSdyncst_mac(atspre_g0int_eq_int)
ATSdyncst_extfun(_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_license_update_056_sats__execute_license_update, (atstkind_type(atstype_ptrk), atstkind_type(atstype_ptrk), atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_bool), atstkind_t0ype(atstype_bool)), postiats_tyrec_0) ;
ATSdyncst_extfun(_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_file_replace_056_sats__execute_file_replace, (atstkind_type(atstype_ptrk), atstkind_type(atstype_ptrk), atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_bool), atstkind_t0ype(atstype_bool)), postiats_tyrec_0) ;
ATSdyncst_extfun(_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_spdx_audit_056_sats__execute_spdx_audit, (atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_int)), postiats_tyrec_0) ;
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
ATSextern()
atsvoid_t0ype
the_atsexncon_initize
(
  atstype_exnconptr d2c, atstype_string exnmsg
) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
/*
exnconlst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
#ifndef _ATS_CCOMP_ASSUME_CHECK_NONE_
#endif // #ifndef(_ATS_CCOMP_ASSUME_CHECK_NONE_)
/*
assumelst-declaration(end)
*/
ATSstatic()
postiats_tyrec_0
to_c_0(postiats_tyrec_0) ;

#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
c_get_version() ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atstkind_t0ype(atstype_int)
c_validate_spdx(atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
postiats_tyrec_0
c_git_sync(atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_int), atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__4(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__4__1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
ATSextern()
postiats_tyrec_0
c_license_update(atstkind_type(atstype_ptrk), atstkind_type(atstype_ptrk), atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__4__2(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__4__3(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
ATSextern()
postiats_tyrec_0
c_file_replace(atstkind_type(atstype_ptrk), atstkind_type(atstype_ptrk), atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__4__4(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__4__5(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
ATSextern()
postiats_tyrec_0
c_spdx_audit(atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]

/*
/home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/ffi/c_exports.dats: 1167(line=35, offs=4) -- 1345(line=40, offs=2)
*/
/*
local: 
global: to_c_0$0(level=0)
local: 
global: 
*/
ATSstatic()
postiats_tyrec_0
to_c_0(postiats_tyrec_0 arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret0, postiats_tyrec_0) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/ffi/c_exports.dats: 1167(line=35, offs=4) -- 1345(line=40, offs=2)
*/
ATSINSflab(__patsflab_to_c_0):
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/ffi/c_exports.dats: 1208(line=35, offs=45) -- 1345(line=40, offs=2)
*/
ATSINSmove_fltrec_beg()
ATSINSstore_fltrec_ofs(tmpret0, postiats_tyrec_0, atslab__success_count, ATSSELfltrec(arg0, postiats_tyrec_0, atslab__success_count)) ;
ATSINSstore_fltrec_ofs(tmpret0, postiats_tyrec_0, atslab__failure_count, ATSSELfltrec(arg0, postiats_tyrec_0, atslab__failure_count)) ;
ATSINSstore_fltrec_ofs(tmpret0, postiats_tyrec_0, atslab__skipped_count, ATSSELfltrec(arg0, postiats_tyrec_0, atslab__skipped_count)) ;
ATSINSstore_fltrec_ofs(tmpret0, postiats_tyrec_0, atslab__message, ATSSELfltrec(arg0, postiats_tyrec_0, atslab__message)) ;
ATSINSmove_fltrec_end()
ATSfunbody_end()
ATSreturn(tmpret0) ;
} /* end of [to_c_0] */

/*
/home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/ffi/c_exports.dats: 1454(line=45, offs=25) -- 1466(line=45, offs=37)
*/
/*
local: 
global: c_get_version$1$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_type(atstype_ptrk)
c_get_version()
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret1, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/ffi/c_exports.dats: 1440(line=45, offs=11) -- 1466(line=45, offs=37)
*/
ATSINSflab(__patsflab_c_get_version):
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/ffi/c_exports.dats: 1459(line=45, offs=30) -- 1466(line=45, offs=37)
*/
ATSINSmove(tmpret1, ATSPMVstring("0.1.0")) ;
ATSfunbody_end()
ATSreturn(tmpret1) ;
} /* end of [c_get_version] */

/*
/home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/ffi/c_exports.dats: 1613(line=50, offs=27) -- 1666(line=51, offs=42)
*/
/*
local: 
global: c_validate_spdx$2$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_t0ype(atstype_int)
c_validate_spdx(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret2, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp3, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/ffi/c_exports.dats: 1597(line=50, offs=11) -- 1666(line=51, offs=42)
*/
ATSINSflab(__patsflab_c_validate_spdx):
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/ffi/c_exports.dats: 1630(line=51, offs=6) -- 1651(line=51, offs=27)
*/
ATSINSmove(tmp3, _057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_types_056_sats__is_valid_spdx(arg0)) ;

/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/ffi/c_exports.dats: 1627(line=51, offs=3) -- 1666(line=51, offs=42)
*/
ATSif(
tmp3
) ATSthen() {
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/ffi/c_exports.dats: 1658(line=51, offs=34) -- 1659(line=51, offs=35)
*/
ATSINSmove(tmpret2, ATSPMVi0nt(1)) ;
} ATSelse() {
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/ffi/c_exports.dats: 1665(line=51, offs=41) -- 1666(line=51, offs=42)
*/
ATSINSmove(tmpret2, ATSPMVi0nt(0)) ;
} /* ATSendif */
ATSfunbody_end()
ATSreturn(tmpret2) ;
} /* end of [c_validate_spdx] */

/*
/home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/ffi/c_exports.dats: 1889(line=62, offs=22) -- 2054(line=64, offs=72)
*/
/*
local: to_c_0$0(level=0)
global: to_c_0$0(level=0), c_git_sync$3$0(level=0)
local: 
global: 
*/
ATSextern()
postiats_tyrec_0
c_git_sync(atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(atstype_int) arg1, atstkind_type(atstype_ptrk) arg2, atstkind_t0ype(atstype_int) arg3, atstkind_t0ype(atstype_int) arg4)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret4, postiats_tyrec_0) ;
ATStmpdec(tmp5, postiats_tyrec_0) ;
ATStmpdec(tmp6, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/ffi/c_exports.dats: 1878(line=62, offs=11) -- 2054(line=64, offs=72)
*/
ATSINSflab(__patsflab_c_git_sync):
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/ffi/c_exports.dats: 2041(line=64, offs=59) -- 2052(line=64, offs=70)
*/
ATSINSmove(tmp6, ATSLIB_056_prelude__eq_g0int_int__4__1(arg4, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/ffi/c_exports.dats: 1956(line=63, offs=8) -- 2053(line=64, offs=71)
*/
ATSINSmove(tmp5, _057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_git_sync_056_sats__execute_git_sync_operation(arg0, arg1, arg2, arg3, tmp6)) ;

/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/ffi/c_exports.dats: 1951(line=63, offs=3) -- 2054(line=64, offs=72)
*/
ATSINSmove(tmpret4, to_c_0(tmp5)) ;

ATSfunbody_end()
ATSreturn(tmpret4) ;
} /* end of [c_git_sync] */

#if(0)
/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats: 12259(line=635, offs=3) -- 12298(line=635, offs=42)
*/
/*
local: 
global: eq_g0int_int$4$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = tk(4634)
tmparg = S2Evar(tk(4634))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__4(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret7, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp8, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12244(line=634, offs=1) -- 12298(line=635, offs=42)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12285(line=635, offs=29) -- 12296(line=635, offs=40)
*/
ATSINSmove(tmp8, PMVtmpltcst(g0int2int<S2Eextkind(atstype_int), S2Evar(tk(4634))>)(arg1)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12268(line=635, offs=12) -- 12298(line=635, offs=42)
*/
ATSINSmove(tmpret7, PMVtmpltcst(g0int_eq<S2Evar(tk(4634))>)(arg0, tmp8)) ;

ATSfunbody_end()
ATSreturn(tmpret7) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__4] */
#endif // end of [TEMPLATE]

/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats: 12259(line=635, offs=3) -- 12298(line=635, offs=42)
*/
/*
local: 
global: eq_g0int_int$4$1(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4634)
tmparg = S2Evar(tk(4634))
tmpsub = Some(tk(4634) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__4__1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret7__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp8__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12244(line=634, offs=1) -- 12298(line=635, offs=42)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12285(line=635, offs=29) -- 12296(line=635, offs=40)
*/
ATSINSmove(tmp8__1, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12268(line=635, offs=12) -- 12298(line=635, offs=42)
*/
ATSINSmove(tmpret7__1, atspre_g0int_eq_int(arg0, tmp8__1)) ;

ATSfunbody_end()
ATSreturn(tmpret7__1) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__4__1] */

/*
/home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/ffi/c_exports.dats: 2321(line=77, offs=3) -- 2510(line=80, offs=36)
*/
/*
local: to_c_0$0(level=0)
global: to_c_0$0(level=0), c_license_update$8$0(level=0)
local: 
global: 
*/
ATSextern()
postiats_tyrec_0
c_license_update(atstkind_type(atstype_ptrk) arg0, atstkind_type(atstype_ptrk) arg1, atstkind_type(atstype_ptrk) arg2, atstkind_t0ype(atstype_int) arg3, atstkind_t0ype(atstype_int) arg4, atstkind_t0ype(atstype_int) arg5)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret11, postiats_tyrec_0) ;
ATStmpdec(tmp12, postiats_tyrec_0) ;
ATStmpdec(tmp13, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp16, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/ffi/c_exports.dats: 2302(line=76, offs=11) -- 2510(line=80, offs=36)
*/
ATSINSflab(__patsflab_c_license_update):
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/ffi/c_exports.dats: 2485(line=80, offs=11) -- 2495(line=80, offs=21)
*/
ATSINSmove(tmp13, ATSLIB_056_prelude__eq_g0int_int__4__2(arg5, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/ffi/c_exports.dats: 2497(line=80, offs=23) -- 2508(line=80, offs=34)
*/
ATSINSmove(tmp16, ATSLIB_056_prelude__eq_g0int_int__4__3(arg4, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/ffi/c_exports.dats: 2395(line=78, offs=8) -- 2509(line=80, offs=35)
*/
ATSINSmove(tmp12, _057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_license_update_056_sats__execute_license_update(arg0, arg1, arg2, arg3, tmp13, tmp16)) ;

/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/ffi/c_exports.dats: 2390(line=78, offs=3) -- 2510(line=80, offs=36)
*/
ATSINSmove(tmpret11, to_c_0(tmp12)) ;

ATSfunbody_end()
ATSreturn(tmpret11) ;
} /* end of [c_license_update] */

/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats: 12259(line=635, offs=3) -- 12298(line=635, offs=42)
*/
/*
local: 
global: eq_g0int_int$4$2(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4634)
tmparg = S2Evar(tk(4634))
tmpsub = Some(tk(4634) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__4__2(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret7__2, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp8__2, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12244(line=634, offs=1) -- 12298(line=635, offs=42)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12285(line=635, offs=29) -- 12296(line=635, offs=40)
*/
ATSINSmove(tmp8__2, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12268(line=635, offs=12) -- 12298(line=635, offs=42)
*/
ATSINSmove(tmpret7__2, atspre_g0int_eq_int(arg0, tmp8__2)) ;

ATSfunbody_end()
ATSreturn(tmpret7__2) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__4__2] */

/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats: 12259(line=635, offs=3) -- 12298(line=635, offs=42)
*/
/*
local: 
global: eq_g0int_int$4$3(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4634)
tmparg = S2Evar(tk(4634))
tmpsub = Some(tk(4634) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__4__3(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret7__3, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp8__3, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12244(line=634, offs=1) -- 12298(line=635, offs=42)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12285(line=635, offs=29) -- 12296(line=635, offs=40)
*/
ATSINSmove(tmp8__3, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12268(line=635, offs=12) -- 12298(line=635, offs=42)
*/
ATSINSmove(tmpret7__3, atspre_g0int_eq_int(arg0, tmp8__3)) ;

ATSfunbody_end()
ATSreturn(tmpret7__3) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__4__3] */

/*
/home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/ffi/c_exports.dats: 2765(line=93, offs=3) -- 2944(line=96, offs=36)
*/
/*
local: to_c_0$0(level=0)
global: to_c_0$0(level=0), c_file_replace$11$0(level=0)
local: 
global: 
*/
ATSextern()
postiats_tyrec_0
c_file_replace(atstkind_type(atstype_ptrk) arg0, atstkind_type(atstype_ptrk) arg1, atstkind_type(atstype_ptrk) arg2, atstkind_t0ype(atstype_int) arg3, atstkind_t0ype(atstype_int) arg4, atstkind_t0ype(atstype_int) arg5)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret19, postiats_tyrec_0) ;
ATStmpdec(tmp20, postiats_tyrec_0) ;
ATStmpdec(tmp21, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp24, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/ffi/c_exports.dats: 2748(line=92, offs=11) -- 2944(line=96, offs=36)
*/
ATSINSflab(__patsflab_c_file_replace):
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/ffi/c_exports.dats: 2919(line=96, offs=11) -- 2929(line=96, offs=21)
*/
ATSINSmove(tmp21, ATSLIB_056_prelude__eq_g0int_int__4__4(arg5, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/ffi/c_exports.dats: 2931(line=96, offs=23) -- 2942(line=96, offs=34)
*/
ATSINSmove(tmp24, ATSLIB_056_prelude__eq_g0int_int__4__5(arg4, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/ffi/c_exports.dats: 2835(line=94, offs=8) -- 2943(line=96, offs=35)
*/
ATSINSmove(tmp20, _057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_file_replace_056_sats__execute_file_replace(arg0, arg1, arg2, arg3, tmp21, tmp24)) ;

/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/ffi/c_exports.dats: 2830(line=94, offs=3) -- 2944(line=96, offs=36)
*/
ATSINSmove(tmpret19, to_c_0(tmp20)) ;

ATSfunbody_end()
ATSreturn(tmpret19) ;
} /* end of [c_file_replace] */

/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats: 12259(line=635, offs=3) -- 12298(line=635, offs=42)
*/
/*
local: 
global: eq_g0int_int$4$4(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4634)
tmparg = S2Evar(tk(4634))
tmpsub = Some(tk(4634) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__4__4(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret7__4, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp8__4, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12244(line=634, offs=1) -- 12298(line=635, offs=42)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12285(line=635, offs=29) -- 12296(line=635, offs=40)
*/
ATSINSmove(tmp8__4, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12268(line=635, offs=12) -- 12298(line=635, offs=42)
*/
ATSINSmove(tmpret7__4, atspre_g0int_eq_int(arg0, tmp8__4)) ;

ATSfunbody_end()
ATSreturn(tmpret7__4) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__4__4] */

/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats: 12259(line=635, offs=3) -- 12298(line=635, offs=42)
*/
/*
local: 
global: eq_g0int_int$4$5(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4634)
tmparg = S2Evar(tk(4634))
tmpsub = Some(tk(4634) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__4__5(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret7__5, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp8__5, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12244(line=634, offs=1) -- 12298(line=635, offs=42)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12285(line=635, offs=29) -- 12296(line=635, offs=40)
*/
ATSINSmove(tmp8__5, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12268(line=635, offs=12) -- 12298(line=635, offs=42)
*/
ATSINSmove(tmpret7__5, atspre_g0int_eq_int(arg0, tmp8__5)) ;

ATSfunbody_end()
ATSreturn(tmpret7__5) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__4__5] */

/*
/home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/ffi/c_exports.dats: 3105(line=102, offs=24) -- 3176(line=103, offs=48)
*/
/*
local: to_c_0$0(level=0)
global: to_c_0$0(level=0), c_spdx_audit$14$0(level=0)
local: 
global: 
*/
ATSextern()
postiats_tyrec_0
c_spdx_audit(atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret27, postiats_tyrec_0) ;
ATStmpdec(tmp28, postiats_tyrec_0) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/ffi/c_exports.dats: 3092(line=102, offs=11) -- 3176(line=103, offs=48)
*/
ATSINSflab(__patsflab_c_spdx_audit):
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/ffi/c_exports.dats: 3136(line=103, offs=8) -- 3175(line=103, offs=47)
*/
ATSINSmove(tmp28, _057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_spdx_audit_056_sats__execute_spdx_audit(arg0, arg1)) ;

/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/ffi/c_exports.dats: 3131(line=103, offs=3) -- 3176(line=103, offs=48)
*/
ATSINSmove(tmpret27, to_c_0(tmp28)) ;

ATSfunbody_end()
ATSreturn(tmpret27) ;
} /* end of [c_spdx_audit] */

/*
** for initialization(dynloading)
*/
ATSextern()
atsvoid_t0ype
_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_ffi_057_c_exports_056_dats__dynload()
{
ATSfunbody_beg()
ATSdynload(/*void*/)
ATSdynloadflag_ext(
_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_ffi_057_c_exports_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_ffi_057_c_exports_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_ffi_057_c_exports_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} /* end of [*_dynload] */

/* ****** ****** */

/* end-of-compilation-unit */
