/*
**
** The C code is generated by [ATS/Postiats-0-4-1]
** The starting compilation time is: 2026-5-18: 19h:49m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE_
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
#endif /* _ATS_CCOMP_HEADER_NONE_ */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE_
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/integer_long.cats"
#include "prelude/CATS/integer_size.cats"
#include "prelude/CATS/integer_short.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/fprintf.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE_ */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER_
//
#include _ATS_CCOMP_PRELUDE_USER_
//
#endif /* _ATS_CCOMP_PRELUDE_USER_ */
/*
** for user2-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER2_
//
#include _ATS_CCOMP_PRELUDE_USER2_
//
#endif /* _ATS_CCOMP_PRELUDE_USER2_ */

/*
staload-prologues(beg)
*/
/*
/usr/lib/ats2-postiats-0.4.2/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
/usr/lib/ats2-postiats-0.4.2/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/usr/lib/ats2-postiats-0.4.2/libats/libc/SATS/sys/stat.sats: 1390(line=36, offs=1) -- 1440(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/stat.cats"
/*
/usr/lib/ats2-postiats-0.4.2/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/usr/lib/ats2-postiats-0.4.2/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
/usr/lib/ats2-postiats-0.4.2/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
typedef
ATSstruct {
atstkind_t0ype(atstype_int) atslab__success_count ;
atstkind_t0ype(atstype_int) atslab__failure_count ;
atstkind_t0ype(atstype_int) atslab__skipped_count ;
atstkind_type(atstype_ptrk) atslab__message ;
} postiats_tyrec_0 ;
typedef
ATSstruct {
// #if(1)
int contag ;
// #endif
atstkind_type(atstype_ptrk) atslab__0 ;
} postiats_tysum_1 ;
typedef
ATSstruct {
#if(0)
int contag ;
#endif
atstkind_type(atstype_ptrk) atslab__0 ;
} postiats_tysum_2 ;
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_extfun(_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_github_settings_056_sats__apply_github_setting, (atstkind_type(atstype_ptrk), atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_bool)), atstype_boxed) ;
ATSdyncst_mac(atspre_strptr_free)
ATSdyncst_mac(atspre_malloc_gc)
ATSdyncst_mac(atspre_string_memcpy)
ATSdyncst_mac(atspre_add_ptr1_bsz)
ATSdyncst_mac(atspre_strlen)
ATSdyncst_mac(atspre_g1uint_add_size)
ATSdyncst_mac(atspre_g1uint_succ_size)
ATSdyncst_extfun(_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_utils_057_string_utils_056_sats__strptr_append_str, (atstkind_type(atstype_ptrk), atstkind_type(atstype_ptrk)), atstkind_type(atstype_ptrk)) ;
ATSdyncst_extfun(_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_effects_056_sats__wexit_ok, (atstkind_t0ype(atstype_int)), atstkind_t0ype(atstype_bool)) ;
ATSdyncst_extfun(_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_effects_056_sats__sys_run_owned, (atstkind_type(atstype_ptrk)), atstkind_t0ype(atstype_int)) ;
ATSdyncst_mac(atspre_exit_errmsg_void)
ATSdyncst_mac(atspre_assert_bool1)
ATSdyncst_mac(atspre_gt_ptr1_ptr1)
ATSdyncst_mac(the_atsptr_null)
ATSdyncst_mac(atspre_g1int2int_int_int)
ATSdyncst_mac(atspre_g1int_gte_int)
ATSdyncst_extfun(_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_utils_057_string_utils_056_sats__strptr_trim_free, (atstkind_type(atstype_ptrk)), atstkind_type(atstype_ptrk)) ;
ATSdyncst_extfun(_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_utils_057_string_utils_056_sats__strptr_peek_is_empty, (atsrefarg0_type(atstkind_type(atstype_ptrk))), atstkind_t0ype(atstype_bool)) ;
ATSdyncst_extfun(_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_types_056_sats__batch_add, (postiats_tyrec_0, atstype_boxed), postiats_tyrec_0) ;
ATSdyncst_mac(atslib_libats_libc_fopen)
ATSdyncst_mac(atspre_gt_ptr1_intz)
ATSdyncst_mac(atspre_file_mode_r)
ATSdyncst_extfun(_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_types_056_sats__empty_batch, (atstkind_type(atstype_ptrk)), postiats_tyrec_0) ;
ATSdyncst_mac(atspre_fileref_close)
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
ATSextern()
atsvoid_t0ype
the_atsexncon_initize
(
  atstype_exnconptr d2c, atstype_string exnmsg
) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
/*
exnconlst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
#ifndef _ATS_CCOMP_ASSUME_CHECK_NONE_
#endif // #ifndef(_ATS_CCOMP_ASSUME_CHECK_NONE_)
/*
assumelst-declaration(end)
*/
ATSstatic()
atstype_boxed
gh_setting_owned_0(atstkind_type(atstype_ptrk), atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_bool)) ;

#if(0)
ATSextern()
atstype_boxed
_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_github_settings_056_sats__apply_github_setting(atstkind_type(atstype_ptrk), atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_bool)) ;
#endif // end of [QUALIFIED]

#if(0)
#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__string0_append__2(atstkind_type(atstype_ptrk), atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__string0_append__2__1(atstkind_type(atstype_ptrk), atstkind_type(atstype_ptrk)) ;

#if(0)
#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__string1_append__4(atstkind_type(atstype_ptrk), atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__string1_append__4__1(atstkind_type(atstype_ptrk), atstkind_type(atstype_ptrk)) ;

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_size)
ATSLIB_056_prelude__string1_length__6(atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_size)
ATSLIB_056_prelude__string1_length__6__1(atstkind_type(atstype_ptrk)) ;

ATSstatic()
atstkind_t0ype(atstype_size)
ATSLIB_056_prelude__string1_length__6__2(atstkind_type(atstype_ptrk)) ;

#if(0)
ATSextern()
postiats_tyrec_0
_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_github_settings_056_sats__execute_github_settings(atstkind_type(atstype_ptrk), atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_bool)) ;
#endif // end of [QUALIFIED]

ATSstatic()
postiats_tyrec_0
loop_12(atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_bool), atstkind_type(atstype_ptrk), postiats_tyrec_0) ;

#if(0)
#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__fileref_get_line_string__13(atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__fileref_get_line_string__13__1(atstkind_type(atstype_ptrk)) ;

#if(0)
#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__fileref_get_line_string_main__15(atstkind_type(atstype_ptrk), atsrefarg1_type(atstkind_t0ype(atstype_int))) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__fileref_get_line_string_main__15__1(atstkind_type(atstype_ptrk), atsrefarg1_type(atstkind_t0ype(atstype_int))) ;

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_int)
ATSLIB_056_prelude__fileref_get_line_string__bufsize__17() ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_int)
ATSLIB_056_prelude__fileref_get_line_string__bufsize__17__1() ;

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__strnptr_isnot_null__19(atsrefarg0_type(atstkind_type(atstype_ptrk))) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__strnptr_isnot_null__19__1(atsrefarg0_type(atstkind_type(atstype_ptrk))) ;

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gte_g1int_int__21(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gte_g1int_int__21__1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
#if(0)
ATSextern()
atstype_boxed
ATSLIB_056_prelude__fileref_open_opt__25(atstkind_type(atstype_ptrk), atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstype_boxed
ATSLIB_056_prelude__fileref_open_opt__25__1(atstkind_type(atstype_ptrk), atstkind_type(atstype_ptrk)) ;

/*
/home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/github_settings.dats: 1171(line=28, offs=4) -- 1368(line=32, offs=9)
*/
/*
local: 
global: gh_setting_owned_0$0(level=0)
local: 
global: 
*/
ATSstatic()
atstype_boxed
gh_setting_owned_0(atstkind_type(atstype_ptrk) arg0, atstkind_type(atstype_ptrk) arg1, atstkind_t0ype(atstype_bool) arg2)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret0, atstype_boxed) ;
ATStmpdec(tmp1, atstype_boxed) ;
// ATStmpdec_void(tmp2) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/github_settings.dats: 1171(line=28, offs=4) -- 1368(line=32, offs=9)
*/
ATSINSflab(__patsflab_gh_setting_owned_0):
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/github_settings.dats: 1255(line=29, offs=68) -- 1368(line=32, offs=9)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/github_settings.dats: 1269(line=30, offs=11) -- 1333(line=30, offs=75)
*/
ATSINSmove(tmp1, _057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_github_settings_056_sats__apply_github_setting(ATSPMVcastfn(strptr2string, atstkind_type(atstype_ptrk), ATSPMVrefarg0(arg0)), arg1, arg2)) ;

/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/github_settings.dats: 1345(line=31, offs=12) -- 1358(line=31, offs=25)
*/
ATSINSmove_void(tmp2, atspre_strptr_free(arg0)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/github_settings.dats: 1363(line=32, offs=4) -- 1364(line=32, offs=5)
*/
ATSINSmove(tmpret0, tmp1) ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/github_settings.dats: 1255(line=29, offs=68) -- 1368(line=32, offs=9)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret0) ;
} /* end of [gh_setting_owned_0] */

/*
/home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/github_settings.dats: 1401(line=34, offs=32) -- 1852(line=48, offs=4)
*/
/*
local: 
global: apply_github_setting$1$0(level=0)
local: 
global: 
*/
ATSextern()
atstype_boxed
_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_github_settings_056_sats__apply_github_setting(atstkind_type(atstype_ptrk) arg0, atstkind_type(atstype_ptrk) arg1, atstkind_t0ype(atstype_bool) arg2)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret3, atstype_boxed) ;
ATStmpdec(tmp4, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp32, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp33, atstkind_type(atstype_ptrk)) ;
// ATStmpdec_void(tmp34) ;
ATStmpdec(tmp35, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp36, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/github_settings.dats: 1380(line=34, offs=11) -- 1852(line=48, offs=4)
*/
ATSINSflab(__patsflab_apply_github_setting):
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/github_settings.dats: 1428(line=34, offs=59) -- 1852(line=48, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/github_settings.dats: 1443(line=35, offs=12) -- 1479(line=35, offs=48)
*/
ATSINSmove(tmp4, ATSLIB_056_prelude__string0_append__2__1(ATSPMVstring("gh repo edit "), arg0)) ;

/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/github_settings.dats: 1491(line=36, offs=12) -- 1517(line=36, offs=38)
*/
ATSINSmove(tmp32, _057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_utils_057_string_utils_056_sats__strptr_append_str(tmp4, ATSPMVstring(" "))) ;

/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/github_settings.dats: 1529(line=37, offs=12) -- 1559(line=37, offs=42)
*/
ATSINSmove(tmp33, _057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_utils_057_string_utils_056_sats__strptr_append_str(tmp32, arg1)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/github_settings.dats: 1565(line=39, offs=3) -- 1848(line=47, offs=61)
*/
ATSif(
arg2
) ATSthen() {
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/github_settings.dats: 1581(line=39, offs=19) -- 1683(line=43, offs=6)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/github_settings.dats: 1598(line=40, offs=14) -- 1612(line=40, offs=28)
*/
ATSINSmove_void(tmp34, atspre_strptr_free(tmp33)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/github_settings.dats: 1623(line=42, offs=5) -- 1677(line=42, offs=59)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(tmpret3, postiats_tysum_1) ;
// #if(1)
ATSINSstore_con1_tag(tmpret3, 2) ;
// #endif
ATSINSstore_con1_ofs(tmpret3, postiats_tysum_1, atslab__0, ATSPMVstring("github-settings: dry-run (gh not invoked)")) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/github_settings.dats: 1581(line=39, offs=19) -- 1683(line=43, offs=6)
*/
/*
INSletpop()
*/
} ATSelse() {
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/github_settings.dats: 1707(line=45, offs=17) -- 1723(line=45, offs=33)
*/
ATSINSmove(tmp36, _057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_effects_056_sats__sys_run_owned(tmp33)) ;

/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/github_settings.dats: 1698(line=45, offs=8) -- 1725(line=45, offs=35)
*/
ATSINSmove(tmp35, _057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_effects_056_sats__wexit_ok(tmp36)) ;

/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/github_settings.dats: 1695(line=45, offs=5) -- 1848(line=47, offs=61)
*/
ATSif(
tmp35
) ATSthen() {
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/github_settings.dats: 1737(line=46, offs=12) -- 1787(line=46, offs=62)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(tmpret3, postiats_tysum_1) ;
// #if(1)
ATSINSstore_con1_tag(tmpret3, 0) ;
// #endif
ATSINSstore_con1_ofs(tmpret3, postiats_tysum_1, atslab__0, ATSPMVstring("github-settings: gh repo edit applied")) ;
ATSINSmove_con1_end()
} ATSelse() {
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/github_settings.dats: 1799(line=47, offs=12) -- 1848(line=47, offs=61)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(tmpret3, postiats_tysum_1) ;
// #if(1)
ATSINSstore_con1_tag(tmpret3, 1) ;
// #endif
ATSINSstore_con1_ofs(tmpret3, postiats_tysum_1, atslab__0, ATSPMVstring("github-settings: gh repo edit failed")) ;
ATSINSmove_con1_end()
} /* ATSendif */
} /* ATSendif */
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/github_settings.dats: 1428(line=34, offs=59) -- 1852(line=48, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret3) ;
} /* end of [_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_github_settings_056_sats__apply_github_setting] */

#if(0)
/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats: 14884(line=842, offs=3) -- 15043(line=851, offs=4)
*/
/*
local: 
global: string0_append$2$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = 
tmparg = 
tmpsub = None()
*/
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__string0_append__2(atstkind_type(atstype_ptrk) arg0, atstkind_type(atstype_ptrk) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret5, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp6, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 14867(line=841, offs=1) -- 15043(line=851, offs=4)
*/
ATSINSflab(__patsflab_string0_append):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 14895(line=842, offs=14) -- 15043(line=851, offs=4)
*/
/*
letpush(beg)
*/
/* (*nothing*) */
/* (*nothing*) */
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 14952(line=846, offs=11) -- 14974(line=846, offs=33)
*/
ATSINSmove(tmp6, PMVtmpltcst(string1_append<>)(ATSPMVcastfn(g1ofg0_string, atstkind_type(atstype_ptrk), arg0), ATSPMVcastfn(g1ofg0_string, atstkind_type(atstype_ptrk), arg1))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15019(line=850, offs=3) -- 15038(line=850, offs=22)
*/
ATSINSmove(tmpret5, ATSPMVcastfn(strnptr2strptr, atstkind_type(atstype_ptrk), tmp6)) ;
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 14895(line=842, offs=14) -- 15043(line=851, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret5) ;
} /* end of [ATSLIB_056_prelude__string0_append__2] */
#endif // end of [TEMPLATE]

/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats: 14884(line=842, offs=3) -- 15043(line=851, offs=4)
*/
/*
local: 
global: string0_append$2$1(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = 
tmparg = 
tmpsub = Some()
*/
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__string0_append__2__1(atstkind_type(atstype_ptrk) arg0, atstkind_type(atstype_ptrk) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret5__1, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp6__1, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 14867(line=841, offs=1) -- 15043(line=851, offs=4)
*/
ATSINSflab(__patsflab_string0_append):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 14895(line=842, offs=14) -- 15043(line=851, offs=4)
*/
/*
letpush(beg)
*/
/* (*nothing*) */
/* (*nothing*) */
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 14952(line=846, offs=11) -- 14974(line=846, offs=33)
*/
ATSINSmove(tmp6__1, ATSLIB_056_prelude__string1_append__4__1(ATSPMVcastfn(g1ofg0_string, atstkind_type(atstype_ptrk), arg0), ATSPMVcastfn(g1ofg0_string, atstkind_type(atstype_ptrk), arg1))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15019(line=850, offs=3) -- 15038(line=850, offs=22)
*/
ATSINSmove(tmpret5__1, ATSPMVcastfn(strnptr2strptr, atstkind_type(atstype_ptrk), tmp6__1)) ;
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 14895(line=842, offs=14) -- 15043(line=851, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret5__1) ;
} /* end of [ATSLIB_056_prelude__string0_append__2__1] */

#if(0)
/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats: 15116(line=856, offs=10) -- 15385(line=868, offs=4)
*/
/*
local: 
global: string1_append$4$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = 
tmparg = 
tmpsub = None()
*/
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__string1_append__4(atstkind_type(atstype_ptrk) arg0, atstkind_type(atstype_ptrk) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret9, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp10, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp11, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp12, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp13, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp14, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp15, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp16, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp17, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp18, atstkind_t0ype(atstype_size)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15092(line=855, offs=1) -- 15385(line=868, offs=4)
*/
ATSINSflab(__patsflab_string1_append):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15127(line=856, offs=21) -- 15385(line=868, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15143(line=858, offs=10) -- 15152(line=858, offs=19)
*/
ATSINSmove(tmp10, PMVtmpltcst(string1_length<>)(arg0)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15163(line=858, offs=30) -- 15172(line=858, offs=39)
*/
ATSINSmove(tmp11, PMVtmpltcst(string1_length<>)(arg1)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15187(line=860, offs=11) -- 15194(line=860, offs=18)
*/
ATSINSmove(tmp12, PMVtmpltcst(g1uint_add<S2Eextkind(atstype_size)>)(tmp10, tmp11)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15225(line=861, offs=31) -- 15233(line=861, offs=39)
*/
ATSINSmove(tmp14, PMVtmpltcst(g1uint_succ<S2Eextkind(atstype_size)>)(tmp12)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15215(line=861, offs=21) -- 15235(line=861, offs=41)
*/
ATSINSmove(tmp13, atspre_malloc_gc(tmp14)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15248(line=863, offs=10) -- 15277(line=863, offs=39)
*/
ATSINSmove(tmp15, atspre_string_memcpy(tmp13, ATSPMVcastfn(string2ptr, atstkind_type(atstype_ptrk), arg0), tmp10)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15294(line=864, offs=17) -- 15300(line=864, offs=23)
*/
ATSINSmove(tmp17, atspre_add_ptr1_bsz(tmp13, tmp10)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15318(line=864, offs=41) -- 15325(line=864, offs=48)
*/
ATSINSmove(tmp18, PMVtmpltcst(g1uint_succ<S2Eextkind(atstype_size)>)(tmp11)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15287(line=864, offs=10) -- 15327(line=864, offs=50)
*/
ATSINSmove(tmp16, atspre_string_memcpy(tmp17, ATSPMVcastfn(string2ptr, atstkind_type(atstype_ptrk), arg1), tmp18)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15336(line=867, offs=3) -- 15381(line=867, offs=48)
*/
ATSINSmove(tmpret9, ATSPMVcastfn(castvwtp0, atstkind_type(atstype_ptrk), tmp13)) ;
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15127(line=856, offs=21) -- 15385(line=868, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret9) ;
} /* end of [ATSLIB_056_prelude__string1_append__4] */
#endif // end of [TEMPLATE]

/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats: 15116(line=856, offs=10) -- 15385(line=868, offs=4)
*/
/*
local: 
global: string1_append$4$1(level=2)
local: 
global: 
*/
ATSstatic()
/*
imparg = 
tmparg = 
tmpsub = Some()
*/
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__string1_append__4__1(atstkind_type(atstype_ptrk) arg0, atstkind_type(atstype_ptrk) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret9__1, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp10__1, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp11__1, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp12__1, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp13__1, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp14__1, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp15__1, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp16__1, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp17__1, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp18__1, atstkind_t0ype(atstype_size)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15092(line=855, offs=1) -- 15385(line=868, offs=4)
*/
ATSINSflab(__patsflab_string1_append):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15127(line=856, offs=21) -- 15385(line=868, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15143(line=858, offs=10) -- 15152(line=858, offs=19)
*/
ATSINSmove(tmp10__1, ATSLIB_056_prelude__string1_length__6__1(arg0)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15163(line=858, offs=30) -- 15172(line=858, offs=39)
*/
ATSINSmove(tmp11__1, ATSLIB_056_prelude__string1_length__6__2(arg1)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15187(line=860, offs=11) -- 15194(line=860, offs=18)
*/
ATSINSmove(tmp12__1, atspre_g1uint_add_size(tmp10__1, tmp11__1)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15225(line=861, offs=31) -- 15233(line=861, offs=39)
*/
ATSINSmove(tmp14__1, atspre_g1uint_succ_size(tmp12__1)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15215(line=861, offs=21) -- 15235(line=861, offs=41)
*/
ATSINSmove(tmp13__1, atspre_malloc_gc(tmp14__1)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15248(line=863, offs=10) -- 15277(line=863, offs=39)
*/
ATSINSmove(tmp15__1, atspre_string_memcpy(tmp13__1, ATSPMVcastfn(string2ptr, atstkind_type(atstype_ptrk), arg0), tmp10__1)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15294(line=864, offs=17) -- 15300(line=864, offs=23)
*/
ATSINSmove(tmp17__1, atspre_add_ptr1_bsz(tmp13__1, tmp10__1)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15318(line=864, offs=41) -- 15325(line=864, offs=48)
*/
ATSINSmove(tmp18__1, atspre_g1uint_succ_size(tmp11__1)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15287(line=864, offs=10) -- 15327(line=864, offs=50)
*/
ATSINSmove(tmp16__1, atspre_string_memcpy(tmp17__1, ATSPMVcastfn(string2ptr, atstkind_type(atstype_ptrk), arg1), tmp18__1)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15336(line=867, offs=3) -- 15381(line=867, offs=48)
*/
ATSINSmove(tmpret9__1, ATSPMVcastfn(castvwtp0, atstkind_type(atstype_ptrk), tmp13__1)) ;
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15127(line=856, offs=21) -- 15385(line=868, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret9__1) ;
} /* end of [ATSLIB_056_prelude__string1_append__4__1] */

#if(0)
/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats: 11344(line=638, offs=6) -- 11453(line=644, offs=2)
*/
/*
local: 
global: string1_length$6$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = 
tmparg = 
tmpsub = None()
*/
atstkind_t0ype(atstype_size)
ATSLIB_056_prelude__string1_length__6(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret29, atstkind_t0ype(atstype_size)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 11324(line=637, offs=1) -- 11453(line=644, offs=2)
*/
ATSINSflab(__patsflab_string1_length):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 11354(line=639, offs=3) -- 11453(line=644, offs=2)
*/
/*
letpush(beg)
*/
/*
letpush(end)
*/

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 11354(line=639, offs=3) -- 11368(line=639, offs=17)
*/
ATSINSmove(tmpret29, atspre_strlen(arg0)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 11354(line=639, offs=3) -- 11453(line=644, offs=2)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret29) ;
} /* end of [ATSLIB_056_prelude__string1_length__6] */
#endif // end of [TEMPLATE]

/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats: 11344(line=638, offs=6) -- 11453(line=644, offs=2)
*/
/*
local: 
global: string1_length$6$1(level=3)
local: 
global: 
*/
ATSstatic()
/*
imparg = 
tmparg = 
tmpsub = Some()
*/
atstkind_t0ype(atstype_size)
ATSLIB_056_prelude__string1_length__6__1(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret29__1, atstkind_t0ype(atstype_size)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 11324(line=637, offs=1) -- 11453(line=644, offs=2)
*/
ATSINSflab(__patsflab_string1_length):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 11354(line=639, offs=3) -- 11453(line=644, offs=2)
*/
/*
letpush(beg)
*/
/*
letpush(end)
*/

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 11354(line=639, offs=3) -- 11368(line=639, offs=17)
*/
ATSINSmove(tmpret29__1, atspre_strlen(arg0)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 11354(line=639, offs=3) -- 11453(line=644, offs=2)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret29__1) ;
} /* end of [ATSLIB_056_prelude__string1_length__6__1] */

/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats: 11344(line=638, offs=6) -- 11453(line=644, offs=2)
*/
/*
local: 
global: string1_length$6$2(level=3)
local: 
global: 
*/
ATSstatic()
/*
imparg = 
tmparg = 
tmpsub = Some()
*/
atstkind_t0ype(atstype_size)
ATSLIB_056_prelude__string1_length__6__2(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret29__2, atstkind_t0ype(atstype_size)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 11324(line=637, offs=1) -- 11453(line=644, offs=2)
*/
ATSINSflab(__patsflab_string1_length):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 11354(line=639, offs=3) -- 11453(line=644, offs=2)
*/
/*
letpush(beg)
*/
/*
letpush(end)
*/

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 11354(line=639, offs=3) -- 11368(line=639, offs=17)
*/
ATSINSmove(tmpret29__2, atspre_strlen(arg0)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 11354(line=639, offs=3) -- 11453(line=644, offs=2)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret29__2) ;
} /* end of [ATSLIB_056_prelude__string1_length__6__2] */

/*
/home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/github_settings.dats: 1888(line=50, offs=35) -- 2638(line=73, offs=4)
*/
/*
local: gh_setting_owned_0$0(level=0)
global: gh_setting_owned_0$0(level=0), execute_github_settings$11$0(level=0)
local: 
global: 
*/
ATSextern()
postiats_tyrec_0
_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_github_settings_056_sats__execute_github_settings(atstkind_type(atstype_ptrk) arg0, atstkind_type(atstype_ptrk) arg1, atstkind_t0ype(atstype_bool) arg2)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret37, postiats_tyrec_0) ;
ATStmpdec(tmp73, atstype_boxed) ;
ATStmpdec(tmp80, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp81, postiats_tyrec_0) ;
ATStmpdec(tmp82, postiats_tyrec_0) ;
// ATStmpdec_void(tmp83) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/github_settings.dats: 1864(line=50, offs=11) -- 2638(line=73, offs=4)
*/
ATSINSflab(__patsflab_execute_github_settings):
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/github_settings.dats: 1925(line=50, offs=72) -- 2638(line=73, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/github_settings.dats: 2268(line=60, offs=11) -- 2313(line=60, offs=56)
*/
ATSINSmove(tmp73, ATSLIB_056_prelude__fileref_open_opt__25__1(arg0, atspre_file_mode_r)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/github_settings.dats: 2319(line=62, offs=3) -- 2634(line=72, offs=60)
*/
ATScaseof_beg()
/*
** ibranchlst-beg
*/
ATSbranch_beg()
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/github_settings.dats: 2334(line=63, offs=5) -- 2346(line=63, offs=17)
*/
ATSINSlab(__atstmplab0):
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/github_settings.dats: 2268(line=60, offs=11) -- 2313(line=60, offs=56)
*/
ATSifthen(ATSCKptrisnull(tmp73)) { ATSINSgoto(__atstmplab3) ; } ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/github_settings.dats: 2346(line=63, offs=17) -- 2346(line=63, offs=17)
*/
ATSINSlab(__atstmplab1):
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/github_settings.dats: 2343(line=63, offs=14) -- 2345(line=63, offs=16)
*/
ATSINSmove(tmp80, ATSSELcon(tmp73, postiats_tysum_2, atslab__0)) ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/github_settings.dats: 2334(line=63, offs=5) -- 2490(line=69, offs=8)
*/
ATSINSfreecon(tmp73) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/github_settings.dats: 2350(line=63, offs=21) -- 2490(line=69, offs=8)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/github_settings.dats: 2371(line=64, offs=18) -- 2401(line=64, offs=48)
*/
ATSINSmove(tmp81, _057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_types_056_sats__empty_batch(ATSPMVstring("github-settings"))) ;

/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/github_settings.dats: 2418(line=65, offs=17) -- 2432(line=65, offs=31)
*/
ATSINSmove(tmp82, loop_12(arg1, arg2, tmp80, tmp81)) ;

/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/github_settings.dats: 2448(line=66, offs=16) -- 2464(line=66, offs=32)
*/
ATSINSmove_void(tmp83, atspre_fileref_close(tmp80)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/github_settings.dats: 2479(line=68, offs=7) -- 2482(line=68, offs=10)
*/
ATSINSmove(tmpret37, tmp82) ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/github_settings.dats: 2350(line=63, offs=21) -- 2490(line=69, offs=8)
*/
/*
INSletpop()
*/
ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/github_settings.dats: 2495(line=70, offs=5) -- 2505(line=70, offs=15)
*/
ATSINSlab(__atstmplab2):
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/github_settings.dats: 2268(line=60, offs=11) -- 2313(line=60, offs=56)
*/
#if(0)
ATSifthen(ATSCKptriscons(tmp73)) { ATSINSdeadcode_fail() ; } ;
#endif
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/github_settings.dats: 2505(line=70, offs=15) -- 2505(line=70, offs=15)
*/
ATSINSlab(__atstmplab3):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/github_settings.dats: 2509(line=70, offs=19) -- 2634(line=72, offs=60)
*/
ATSINSmove_fltrec_beg()
ATSINSstore_fltrec_ofs(tmpret37, postiats_tyrec_0, atslab__success_count, ATSPMVi0nt(0)) ;
ATSINSstore_fltrec_ofs(tmpret37, postiats_tyrec_0, atslab__failure_count, ATSPMVi0nt(1)) ;
ATSINSstore_fltrec_ofs(tmpret37, postiats_tyrec_0, atslab__skipped_count, ATSPMVi0nt(0)) ;
ATSINSstore_fltrec_ofs(tmpret37, postiats_tyrec_0, atslab__message, ATSPMVstring("github-settings: repo list not readable")) ;
ATSINSmove_fltrec_end()
ATSbranch_end()

/*
** ibranchlst-end
*/
ATScaseof_end()

/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/github_settings.dats: 1925(line=50, offs=72) -- 2638(line=73, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret37) ;
} /* end of [_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_github_settings_056_sats__execute_github_settings] */

/*
/home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/github_settings.dats: 1935(line=51, offs=7) -- 2257(line=59, offs=6)
*/
/*
local: gh_setting_owned_0$0(level=0), loop_12$0(level=1)
global: gh_setting_owned_0$0(level=0), loop_12$0(level=1)
local: gh_flag$4749(1)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk)))), dry_run$4750(1)(HSEapp(HSEcst(atstkind_t0ype); HSEs2exp(S2Eextkind(atstype_bool))))
global: gh_flag$4749(1)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk)))), dry_run$4750(1)(HSEapp(HSEcst(atstkind_t0ype); HSEs2exp(S2Eextkind(atstype_bool))))
*/
ATSstatic()
postiats_tyrec_0
loop_12(atstkind_type(atstype_ptrk) env0, atstkind_t0ype(atstype_bool) env1, atstkind_type(atstype_ptrk) arg0, postiats_tyrec_0 arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(apy0, atstkind_type(atstype_ptrk)) ;
ATStmpdec(apy1, postiats_tyrec_0) ;
ATStmpdec(tmpret38, postiats_tyrec_0) ;
ATStmpdec(tmp39, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp68, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp69, atstkind_t0ype(atstype_bool)) ;
// ATStmpdec_void(tmp70) ;
ATStmpdec(tmp71, postiats_tyrec_0) ;
ATStmpdec(tmp72, atstype_boxed) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/github_settings.dats: 1935(line=51, offs=7) -- 2257(line=59, offs=6)
*/
ATSINSflab(__patsflab_loop_12):
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/github_settings.dats: 1989(line=51, offs=61) -- 2257(line=59, offs=6)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/github_settings.dats: 2008(line=52, offs=16) -- 2034(line=52, offs=42)
*/
ATSINSmove(tmp39, ATSLIB_056_prelude__fileref_get_line_string__13__1(arg0)) ;

/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/github_settings.dats: 2048(line=53, offs=13) -- 2069(line=53, offs=34)
*/
ATSINSmove(tmp68, _057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_utils_057_string_utils_056_sats__strptr_trim_free(tmp39)) ;

/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/github_settings.dats: 2087(line=54, offs=17) -- 2109(line=54, offs=39)
*/
ATSINSmove(tmp69, _057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_utils_057_string_utils_056_sats__strptr_peek_is_empty(ATSPMVrefarg0(tmp68))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/github_settings.dats: 2120(line=56, offs=5) -- 2251(line=58, offs=70)
*/
ATSif(
tmp69
) ATSthen() {
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/github_settings.dats: 2134(line=56, offs=19) -- 2172(line=56, offs=57)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/github_settings.dats: 2147(line=56, offs=32) -- 2160(line=56, offs=45)
*/
ATSINSmove_void(tmp70, atspre_strptr_free(tmp68)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/github_settings.dats: 2165(line=56, offs=50) -- 2168(line=56, offs=53)
*/
ATSINSmove(tmpret38, arg1) ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/github_settings.dats: 2134(line=56, offs=19) -- 2172(line=56, offs=57)
*/
/*
INSletpop()
*/
} ATSelse() {
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/github_settings.dats: 2212(line=58, offs=31) -- 2249(line=58, offs=68)
*/
ATSINSmove(tmp72, gh_setting_owned_0(tmp68, env0, env1)) ;

/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/github_settings.dats: 2197(line=58, offs=16) -- 2250(line=58, offs=69)
*/
ATSINSmove(tmp71, _057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_types_056_sats__batch_add(arg1, tmp72)) ;

/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/github_settings.dats: 2188(line=58, offs=7) -- 2251(line=58, offs=70)
*/
ATStailcal_beg()
ATSINSmove_tlcal(apy0, arg0) ;
ATSINSmove_tlcal(apy1, tmp71) ;
ATSINSargmove_tlcal(arg0, apy0) ;
ATSINSargmove_tlcal(arg1, apy1) ;
ATSINSfgoto(__patsflab_loop_12) ;
ATStailcal_end()

} /* ATSendif */
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/github_settings.dats: 1989(line=51, offs=61) -- 2257(line=59, offs=6)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret38) ;
} /* end of [loop_12] */

#if(0)
/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats: 10106(line=574, offs=3) -- 10272(line=582, offs=4)
*/
/*
local: 
global: fileref_get_line_string$13$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = 
tmparg = 
tmpsub = None()
*/
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__fileref_get_line_string__13(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret40, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmpref41, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp42, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10080(line=573, offs=1) -- 10272(line=582, offs=4)
*/
ATSINSflab(__patsflab_fileref_get_line_string):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10114(line=574, offs=11) -- 10272(line=582, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10125(line=576, offs=5) -- 10129(line=576, offs=9)
*/
/*
ATSINStmpdec(tmpref41) ;
*/
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10163(line=577, offs=12) -- 10202(line=577, offs=51)
*/
ATSINSmove(tmp42, PMVtmpltcst(fileref_get_line_string_main<>)(arg0, ATSPMVrefarg1(ATSPMVptrof(tmpref41)))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10248(line=581, offs=3) -- 10267(line=581, offs=22)
*/
ATSINSmove(tmpret40, ATSPMVcastfn(strnptr2strptr, atstkind_type(atstype_ptrk), tmp42)) ;
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10114(line=574, offs=11) -- 10272(line=582, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret40) ;
} /* end of [ATSLIB_056_prelude__fileref_get_line_string__13] */
#endif // end of [TEMPLATE]

/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats: 10106(line=574, offs=3) -- 10272(line=582, offs=4)
*/
/*
local: 
global: fileref_get_line_string$13$1(level=2)
local: 
global: 
*/
ATSstatic()
/*
imparg = 
tmparg = 
tmpsub = Some()
*/
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__fileref_get_line_string__13__1(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret40__1, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmpref41__1, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp42__1, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10080(line=573, offs=1) -- 10272(line=582, offs=4)
*/
ATSINSflab(__patsflab_fileref_get_line_string):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10114(line=574, offs=11) -- 10272(line=582, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10125(line=576, offs=5) -- 10129(line=576, offs=9)
*/
/*
ATSINStmpdec(tmpref41) ;
*/
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10163(line=577, offs=12) -- 10202(line=577, offs=51)
*/
ATSINSmove(tmp42__1, ATSLIB_056_prelude__fileref_get_line_string_main__15__1(arg0, ATSPMVrefarg1(ATSPMVptrof(tmpref41__1)))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10248(line=581, offs=3) -- 10267(line=581, offs=22)
*/
ATSINSmove(tmpret40__1, ATSPMVcastfn(strnptr2strptr, atstkind_type(atstype_ptrk), tmp42__1)) ;
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10114(line=574, offs=11) -- 10272(line=582, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret40__1) ;
} /* end of [ATSLIB_056_prelude__fileref_get_line_string__13__1] */

#if(0)
/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats: 10382(line=589, offs=3) -- 11000(line=628, offs=4)
*/
/*
local: 
global: fileref_get_line_string_main$15$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = 
tmparg = 
tmpsub = None()
*/
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__fileref_get_line_string_main__15(atstkind_type(atstype_ptrk) arg0, atsrefarg1_type(atstkind_t0ype(atstype_int)) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret46, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp47, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp48, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp49, atstkind_t0ype(atstype_bool)) ;
// ATStmpdec_void(tmp50) ;
// ATStmpdec_void(tmp51) ;
ATStmpdec(tmp52, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10351(line=588, offs=1) -- 11000(line=628, offs=4)
*/
ATSINSflab(__patsflab_fileref_get_line_string_main):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10396(line=589, offs=17) -- 11000(line=628, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10413(line=593, offs=1) -- 10448(line=593, offs=36)
*/
ATSINSmove(tmp47, PMVtmpltcst(fileref_get_line_string$bufsize<>)()) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10477(line=597, offs=7) -- 10564(line=601, offs=2)
*/
ATSINSmove(tmp48, ATSextfcall(atspre_fileref_get_line_string_main2, (tmp47, arg0, arg1))) ;
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10735(line=613, offs=13) -- 10757(line=613, offs=35)
*/
ATSINSmove(tmp49, PMVtmpltcst(strnptr_isnot_null<>)(ATSPMVrefarg0(tmp48))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10768(line=617, offs=1) -- 10975(line=626, offs=4)
*/
ATSif(
tmp49
) ATSthen() {
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10782(line=619, offs=6) -- 10785(line=619, offs=9)
*/
ATSINSmove(tmpret46, tmp48) ;
} ATSelse() {
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10791(line=619, offs=15) -- 10975(line=626, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10808(line=621, offs=3) -- 10872(line=622, offs=48)
*/
ATSINSmove_void(tmp50, atspre_exit_errmsg_void(ATSPMVi0nt(1), ATSPMVstring("[fileref_get_line_string_main] failed."))) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10892(line=623, offs=20) -- 10901(line=623, offs=29)
*/
ATSINSmove(tmp52, PMVtmpltcst(gte_g1int_int<S2Eextkind(atstype_int)>)(ATSderef(arg1, atstkind_t0ype(atstype_int)), ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10884(line=623, offs=12) -- 10902(line=623, offs=30)
*/
ATSINSmove_void(tmp51, atspre_assert_bool1(tmp52)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10934(line=625, offs=3) -- 10937(line=625, offs=6)
*/
ATSINSmove(tmpret46, tmp48) ;
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10791(line=619, offs=15) -- 10975(line=626, offs=4)
*/
/*
INSletpop()
*/
} /* ATSendif */
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10396(line=589, offs=17) -- 11000(line=628, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret46) ;
} /* end of [ATSLIB_056_prelude__fileref_get_line_string_main__15] */
#endif // end of [TEMPLATE]

/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats: 10382(line=589, offs=3) -- 11000(line=628, offs=4)
*/
/*
local: 
global: fileref_get_line_string_main$15$1(level=3)
local: 
global: 
*/
ATSstatic()
/*
imparg = 
tmparg = 
tmpsub = Some()
*/
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__fileref_get_line_string_main__15__1(atstkind_type(atstype_ptrk) arg0, atsrefarg1_type(atstkind_t0ype(atstype_int)) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret46__1, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp47__1, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp48__1, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp49__1, atstkind_t0ype(atstype_bool)) ;
// ATStmpdec_void(tmp50__1) ;
// ATStmpdec_void(tmp51__1) ;
ATStmpdec(tmp52__1, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10351(line=588, offs=1) -- 11000(line=628, offs=4)
*/
ATSINSflab(__patsflab_fileref_get_line_string_main):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10396(line=589, offs=17) -- 11000(line=628, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10413(line=593, offs=1) -- 10448(line=593, offs=36)
*/
ATSINSmove(tmp47__1, ATSLIB_056_prelude__fileref_get_line_string__bufsize__17__1()) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10477(line=597, offs=7) -- 10564(line=601, offs=2)
*/
ATSINSmove(tmp48__1, ATSextfcall(atspre_fileref_get_line_string_main2, (tmp47__1, arg0, arg1))) ;
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10735(line=613, offs=13) -- 10757(line=613, offs=35)
*/
ATSINSmove(tmp49__1, ATSLIB_056_prelude__strnptr_isnot_null__19__1(ATSPMVrefarg0(tmp48__1))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10768(line=617, offs=1) -- 10975(line=626, offs=4)
*/
ATSif(
tmp49__1
) ATSthen() {
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10782(line=619, offs=6) -- 10785(line=619, offs=9)
*/
ATSINSmove(tmpret46__1, tmp48__1) ;
} ATSelse() {
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10791(line=619, offs=15) -- 10975(line=626, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10808(line=621, offs=3) -- 10872(line=622, offs=48)
*/
ATSINSmove_void(tmp50__1, atspre_exit_errmsg_void(ATSPMVi0nt(1), ATSPMVstring("[fileref_get_line_string_main] failed."))) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10892(line=623, offs=20) -- 10901(line=623, offs=29)
*/
ATSINSmove(tmp52__1, ATSLIB_056_prelude__gte_g1int_int__21__1(ATSderef(arg1, atstkind_t0ype(atstype_int)), ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10884(line=623, offs=12) -- 10902(line=623, offs=30)
*/
ATSINSmove_void(tmp51__1, atspre_assert_bool1(tmp52__1)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10934(line=625, offs=3) -- 10937(line=625, offs=6)
*/
ATSINSmove(tmpret46__1, tmp48__1) ;
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10791(line=619, offs=15) -- 10975(line=626, offs=4)
*/
/*
INSletpop()
*/
} /* ATSendif */
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10396(line=589, offs=17) -- 11000(line=628, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret46__1) ;
} /* end of [ATSLIB_056_prelude__fileref_get_line_string_main__15__1] */

#if(0)
/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats: 9967(line=564, offs=32) -- 9974(line=564, offs=39)
*/
/*
local: 
global: fileref_get_line_string$bufsize$17$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = 
tmparg = 
tmpsub = None()
*/
atstkind_t0ype(atstype_int)
ATSLIB_056_prelude__fileref_get_line_string__bufsize__17()
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret60, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 9936(line=564, offs=1) -- 9974(line=564, offs=39)
*/
ATSINSflab(__patsflab_fileref_get_line_string__bufsize):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 9972(line=564, offs=37) -- 9974(line=564, offs=39)
*/
ATSINSmove(tmpret60, ATSPMVi0nt(64)) ;
ATSfunbody_end()
ATSreturn(tmpret60) ;
} /* end of [ATSLIB_056_prelude__fileref_get_line_string__bufsize__17] */
#endif // end of [TEMPLATE]

/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats: 9967(line=564, offs=32) -- 9974(line=564, offs=39)
*/
/*
local: 
global: fileref_get_line_string$bufsize$17$1(level=4)
local: 
global: 
*/
ATSstatic()
/*
imparg = 
tmparg = 
tmpsub = Some()
*/
atstkind_t0ype(atstype_int)
ATSLIB_056_prelude__fileref_get_line_string__bufsize__17__1()
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret60__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 9936(line=564, offs=1) -- 9974(line=564, offs=39)
*/
ATSINSflab(__patsflab_fileref_get_line_string__bufsize):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 9972(line=564, offs=37) -- 9974(line=564, offs=39)
*/
ATSINSmove(tmpret60__1, ATSPMVi0nt(64)) ;
ATSfunbody_end()
ATSreturn(tmpret60__1) ;
} /* end of [ATSLIB_056_prelude__fileref_get_line_string__bufsize__17__1] */

#if(0)
/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/strptr.dats: 4111(line=188, offs=20) -- 4146(line=188, offs=55)
*/
/*
local: 
global: strnptr_isnot_null$19$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = 
tmparg = 
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__strnptr_isnot_null__19(atsrefarg0_type(atstkind_type(atstype_ptrk)) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret62, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/strptr.dats({$PATSPRE}/DATS/strptr.dats): 4092(line=188, offs=1) -- 4146(line=188, offs=55)
*/
ATSINSflab(__patsflab_strnptr_isnot_null):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/strptr.dats({$PATSPRE}/DATS/strptr.dats): 4120(line=188, offs=29) -- 4145(line=188, offs=54)
*/
ATSINSmove(tmpret62, atspre_gt_ptr1_ptr1(ATSPMVcastfn(strnptr2ptr, atstkind_type(atstype_ptrk), ATSPMVrefarg0(arg0)), the_atsptr_null)) ;

ATSfunbody_end()
ATSreturn(tmpret62) ;
} /* end of [ATSLIB_056_prelude__strnptr_isnot_null__19] */
#endif // end of [TEMPLATE]

/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/strptr.dats: 4111(line=188, offs=20) -- 4146(line=188, offs=55)
*/
/*
local: 
global: strnptr_isnot_null$19$1(level=4)
local: 
global: 
*/
ATSstatic()
/*
imparg = 
tmparg = 
tmpsub = Some()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__strnptr_isnot_null__19__1(atsrefarg0_type(atstkind_type(atstype_ptrk)) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret62__1, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/strptr.dats({$PATSPRE}/DATS/strptr.dats): 4092(line=188, offs=1) -- 4146(line=188, offs=55)
*/
ATSINSflab(__patsflab_strnptr_isnot_null):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/strptr.dats({$PATSPRE}/DATS/strptr.dats): 4120(line=188, offs=29) -- 4145(line=188, offs=54)
*/
ATSINSmove(tmpret62__1, atspre_gt_ptr1_ptr1(ATSPMVcastfn(strnptr2ptr, atstkind_type(atstype_ptrk), ATSPMVrefarg0(arg0)), the_atsptr_null)) ;

ATSfunbody_end()
ATSreturn(tmpret62__1) ;
} /* end of [ATSLIB_056_prelude__strnptr_isnot_null__19__1] */

#if(0)
/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats: 12757(line=663, offs=3) -- 12797(line=663, offs=43)
*/
/*
local: 
global: gte_g1int_int$21$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = tk(4646)
tmparg = S2Evar(tk(4646))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gte_g1int_int__21(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret64, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp65, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12741(line=662, offs=1) -- 12797(line=663, offs=43)
*/
ATSINSflab(__patsflab_gte_g1int_int):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12784(line=663, offs=30) -- 12795(line=663, offs=41)
*/
ATSINSmove(tmp65, PMVtmpltcst(g1int2int<S2Eextkind(atstype_int), S2Evar(tk(4646))>)(arg1)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12766(line=663, offs=12) -- 12797(line=663, offs=43)
*/
ATSINSmove(tmpret64, PMVtmpltcst(g1int_gte<S2Evar(tk(4646))>)(arg0, tmp65)) ;

ATSfunbody_end()
ATSreturn(tmpret64) ;
} /* end of [ATSLIB_056_prelude__gte_g1int_int__21] */
#endif // end of [TEMPLATE]

/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats: 12757(line=663, offs=3) -- 12797(line=663, offs=43)
*/
/*
local: 
global: gte_g1int_int$21$1(level=4)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4646)
tmparg = S2Evar(tk(4646))
tmpsub = Some(tk(4646) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gte_g1int_int__21__1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret64__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp65__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12741(line=662, offs=1) -- 12797(line=663, offs=43)
*/
ATSINSflab(__patsflab_gte_g1int_int):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12784(line=663, offs=30) -- 12795(line=663, offs=41)
*/
ATSINSmove(tmp65__1, atspre_g1int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12766(line=663, offs=12) -- 12797(line=663, offs=43)
*/
ATSINSmove(tmpret64__1, atspre_g1int_gte_int(arg0, tmp65__1)) ;

ATSfunbody_end()
ATSreturn(tmpret64__1) ;
} /* end of [ATSLIB_056_prelude__gte_g1int_int__21__1] */

#if(0)
/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats: 5101(line=258, offs=3) -- 5460(line=286, offs=4)
*/
/*
local: 
global: fileref_open_opt$25$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = 
tmparg = 
tmpsub = None()
*/
atstype_boxed
ATSLIB_056_prelude__fileref_open_opt__25(atstkind_type(atstype_ptrk) arg0, atstkind_type(atstype_ptrk) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret74, atstype_boxed) ;
ATStmpdec(tmp75, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp76, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 5082(line=257, offs=1) -- 5460(line=286, offs=4)
*/
ATSINSflab(__patsflab_fileref_open_opt):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 5114(line=258, offs=16) -- 5460(line=286, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 5132(line=261, offs=8) -- 5155(line=261, offs=31)
*/
ATSINSmove(tmp75, atslib_libats_libc_fopen(arg0, arg1)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 5168(line=263, offs=9) -- 5196(line=263, offs=37)
*/
ATSINSmove(tmp76, atspre_gt_ptr1_intz(ATSPMVcastfn(FILEptr2ptr, atstkind_type(atstype_ptrk), ATSPMVrefarg0(tmp75)), ATSPMVi0nt(0))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 5206(line=267, offs=1) -- 5436(line=284, offs=4)
*/
ATSif(
tmp76
) ATSthen() {
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 5220(line=269, offs=6) -- 5313(line=276, offs=4)
*/
/*
letpush(beg)
*/
/* (*nothing*) */
/*
letpush(end)
*/

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 5276(line=275, offs=3) -- 5297(line=275, offs=24)
*/

/*
#LINCONSTATUS==0
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(tmpret74, postiats_tysum_2) ;
#if(0)
ATSINSstore_con1_tag(tmpret74, 0) ;
#endif
ATSINSstore_con1_ofs(tmpret74, postiats_tysum_2, atslab__0, ATSPMVcastfn(FILEptr_refize, atstkind_type(atstype_ptrk), tmp75)) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 5220(line=269, offs=6) -- 5313(line=276, offs=4)
*/
/*
INSletpop()
*/
} ATSelse() {
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 5395(line=283, offs=3) -- 5421(line=283, offs=29)
*/

ATSINSmove_nil(tmpret74) ;

} /* ATSendif */
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 5114(line=258, offs=16) -- 5460(line=286, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret74) ;
} /* end of [ATSLIB_056_prelude__fileref_open_opt__25] */
#endif // end of [TEMPLATE]

/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats: 5101(line=258, offs=3) -- 5460(line=286, offs=4)
*/
/*
local: 
global: fileref_open_opt$25$1(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = 
tmparg = 
tmpsub = Some()
*/
atstype_boxed
ATSLIB_056_prelude__fileref_open_opt__25__1(atstkind_type(atstype_ptrk) arg0, atstkind_type(atstype_ptrk) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret74__1, atstype_boxed) ;
ATStmpdec(tmp75__1, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp76__1, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 5082(line=257, offs=1) -- 5460(line=286, offs=4)
*/
ATSINSflab(__patsflab_fileref_open_opt):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 5114(line=258, offs=16) -- 5460(line=286, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 5132(line=261, offs=8) -- 5155(line=261, offs=31)
*/
ATSINSmove(tmp75__1, atslib_libats_libc_fopen(arg0, arg1)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 5168(line=263, offs=9) -- 5196(line=263, offs=37)
*/
ATSINSmove(tmp76__1, atspre_gt_ptr1_intz(ATSPMVcastfn(FILEptr2ptr, atstkind_type(atstype_ptrk), ATSPMVrefarg0(tmp75__1)), ATSPMVi0nt(0))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 5206(line=267, offs=1) -- 5436(line=284, offs=4)
*/
ATSif(
tmp76__1
) ATSthen() {
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 5220(line=269, offs=6) -- 5313(line=276, offs=4)
*/
/*
letpush(beg)
*/
/* (*nothing*) */
/*
letpush(end)
*/

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 5276(line=275, offs=3) -- 5297(line=275, offs=24)
*/

/*
#LINCONSTATUS==0
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(tmpret74__1, postiats_tysum_2) ;
#if(0)
ATSINSstore_con1_tag(tmpret74__1, 0) ;
#endif
ATSINSstore_con1_ofs(tmpret74__1, postiats_tysum_2, atslab__0, ATSPMVcastfn(FILEptr_refize, atstkind_type(atstype_ptrk), tmp75__1)) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 5220(line=269, offs=6) -- 5313(line=276, offs=4)
*/
/*
INSletpop()
*/
} ATSelse() {
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 5395(line=283, offs=3) -- 5421(line=283, offs=29)
*/

ATSINSmove_nil(tmpret74__1) ;

} /* ATSendif */
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 5114(line=258, offs=16) -- 5460(line=286, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret74__1) ;
} /* end of [ATSLIB_056_prelude__fileref_open_opt__25__1] */

/*
** for initialization(dynloading)
*/
ATSextern()
atsvoid_t0ype
_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_github_settings_056_dats__dynload()
{
ATSfunbody_beg()
ATSdynload(/*void*/)
ATSdynloadflag_ext(
_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_github_settings_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_github_settings_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_github_settings_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} /* end of [*_dynload] */

/* ****** ****** */

/* end-of-compilation-unit */
