/*
**
** The C code is generated by [ATS/Postiats-0-4-1]
** The starting compilation time is: 2026-5-18: 19h:49m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE_
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
#endif /* _ATS_CCOMP_HEADER_NONE_ */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE_
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/integer_long.cats"
#include "prelude/CATS/integer_size.cats"
#include "prelude/CATS/integer_short.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/fprintf.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE_ */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER_
//
#include _ATS_CCOMP_PRELUDE_USER_
//
#endif /* _ATS_CCOMP_PRELUDE_USER_ */
/*
** for user2-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER2_
//
#include _ATS_CCOMP_PRELUDE_USER2_
//
#endif /* _ATS_CCOMP_PRELUDE_USER2_ */

/*
staload-prologues(beg)
*/
/*
/usr/lib/ats2-postiats-0.4.2/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
/usr/lib/ats2-postiats-0.4.2/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/usr/lib/ats2-postiats-0.4.2/libats/libc/SATS/sys/stat.sats: 1390(line=36, offs=1) -- 1440(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/stat.cats"
/*
/usr/lib/ats2-postiats-0.4.2/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/usr/lib/ats2-postiats-0.4.2/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
/usr/lib/ats2-postiats-0.4.2/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
typedef
ATSstruct {
atstkind_t0ype(atstype_int) atslab__success_count ;
atstkind_t0ype(atstype_int) atslab__failure_count ;
atstkind_t0ype(atstype_int) atslab__skipped_count ;
atstkind_type(atstype_ptrk) atslab__message ;
} postiats_tyrec_0 ;
typedef
ATSstruct {
#if(0)
int contag ;
#endif
atstkind_type(atstype_ptrk) atslab__0 ;
} postiats_tysum_1 ;
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_extfun(_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_utils_057_string_utils_056_sats__tostring_int, (atstkind_t0ype(atstype_int)), atstkind_type(atstype_ptrk)) ;
ATSdyncst_mac(atspre_malloc_gc)
ATSdyncst_mac(atspre_string_memcpy)
ATSdyncst_mac(atspre_add_ptr1_bsz)
ATSdyncst_mac(atspre_strlen)
ATSdyncst_mac(atspre_g1uint_add_size)
ATSdyncst_mac(atspre_g1uint_succ_size)
ATSdyncst_extfun(_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_utils_057_string_utils_056_sats__strptr_append_str, (atstkind_type(atstype_ptrk), atstkind_type(atstype_ptrk)), atstkind_type(atstype_ptrk)) ;
ATSdyncst_extfun(_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_utils_057_string_utils_056_sats__strptr_append_strptr, (atstkind_type(atstype_ptrk), atstkind_type(atstype_ptrk)), atstkind_type(atstype_ptrk)) ;
ATSdyncst_extfun(_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_effects_056_sats__sys_run_owned, (atstkind_type(atstype_ptrk)), atstkind_t0ype(atstype_int)) ;
ATSdyncst_mac(atspre_neg_bool0)
ATSdyncst_extfun(_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_effects_056_sats__wexit_ok, (atstkind_t0ype(atstype_int)), atstkind_t0ype(atstype_bool)) ;
ATSdyncst_mac(atspre_g1int_neg_int)
ATSdyncst_mac(atslib_libats_libc_fopen)
ATSdyncst_mac(atspre_gt_ptr1_intz)
ATSdyncst_mac(atspre_file_mode_r)
ATSdyncst_mac(atspre_exit_errmsg_void)
ATSdyncst_mac(atspre_assert_bool1)
ATSdyncst_mac(atspre_gt_ptr1_ptr1)
ATSdyncst_mac(the_atsptr_null)
ATSdyncst_mac(atspre_g1int2int_int_int)
ATSdyncst_mac(atspre_g1int_gte_int)
ATSdyncst_mac(atspre_fileref_close)
ATSdyncst_extfun(_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_utils_057_string_utils_056_sats__strptr_parse_int_free, (atstkind_type(atstype_ptrk)), atstkind_t0ype(atstype_int)) ;
ATSdyncst_extfun(_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_utils_057_string_utils_056_sats__strptr_trim_free, (atstkind_type(atstype_ptrk)), atstkind_type(atstype_ptrk)) ;
ATSdyncst_mac(atspre_g0int2int_int_int)
ATSdyncst_mac(atspre_g0int_lt_int)
ATSdyncst_extfun(_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_spdx_audit_056_sats__count_missing_spdx, (atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_int)), atstkind_t0ype(atstype_int)) ;
ATSdyncst_mac(atspre_g0int_eq_int)
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
ATSextern()
atsvoid_t0ype
the_atsexncon_initize
(
  atstype_exnconptr d2c, atstype_string exnmsg
) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
/*
exnconlst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
#ifndef _ATS_CCOMP_ASSUME_CHECK_NONE_
#endif // #ifndef(_ATS_CCOMP_ASSUME_CHECK_NONE_)
/*
assumelst-declaration(end)
*/
ATSstatic()
atstkind_type(atstype_ptrk)
istr_0(atstkind_t0ype(atstype_int)) ;

#if(0)
ATSextern()
atstkind_t0ype(atstype_int)
_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_spdx_audit_056_sats__count_missing_spdx(atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]

#if(0)
#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__string0_append__2(atstkind_type(atstype_ptrk), atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__string0_append__2__1(atstkind_type(atstype_ptrk), atstkind_type(atstype_ptrk)) ;

#if(0)
#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__string1_append__4(atstkind_type(atstype_ptrk), atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__string1_append__4__1(atstkind_type(atstype_ptrk), atstkind_type(atstype_ptrk)) ;

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_size)
ATSLIB_056_prelude__string1_length__6(atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_size)
ATSLIB_056_prelude__string1_length__6__1(atstkind_type(atstype_ptrk)) ;

ATSstatic()
atstkind_t0ype(atstype_size)
ATSLIB_056_prelude__string1_length__6__2(atstkind_type(atstype_ptrk)) ;

#if(0)
#if(0)
ATSextern()
atstype_boxed
ATSLIB_056_prelude__fileref_open_opt__12(atstkind_type(atstype_ptrk), atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstype_boxed
ATSLIB_056_prelude__fileref_open_opt__12__1(atstkind_type(atstype_ptrk), atstkind_type(atstype_ptrk)) ;

#if(0)
#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__fileref_get_line_string__14(atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__fileref_get_line_string__14__1(atstkind_type(atstype_ptrk)) ;

#if(0)
#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__fileref_get_line_string_main__16(atstkind_type(atstype_ptrk), atsrefarg1_type(atstkind_t0ype(atstype_int))) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__fileref_get_line_string_main__16__1(atstkind_type(atstype_ptrk), atsrefarg1_type(atstkind_t0ype(atstype_int))) ;

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_int)
ATSLIB_056_prelude__fileref_get_line_string__bufsize__18() ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_int)
ATSLIB_056_prelude__fileref_get_line_string__bufsize__18__1() ;

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__strnptr_isnot_null__20(atsrefarg0_type(atstkind_type(atstype_ptrk))) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__strnptr_isnot_null__20__1(atsrefarg0_type(atstkind_type(atstype_ptrk))) ;

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gte_g1int_int__22(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gte_g1int_int__22__1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__lt_g0int_int__26(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__lt_g0int_int__26__1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
ATSextern()
postiats_tyrec_0
_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_spdx_audit_056_sats__execute_spdx_audit(atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__lt_g0int_int__26__2(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__32(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__32__1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

/*
/home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/spdx_audit.dats: 688(line=22, offs=4) -- 728(line=22, offs=44)
*/
/*
local: 
global: istr_0$0(level=0)
local: 
global: 
*/
ATSstatic()
atstkind_type(atstype_ptrk)
istr_0(atstkind_t0ype(atstype_int) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret0, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/spdx_audit.dats: 688(line=22, offs=4) -- 728(line=22, offs=44)
*/
ATSINSflab(__patsflab_istr_0):
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/spdx_audit.dats: 713(line=22, offs=29) -- 727(line=22, offs=43)
*/
ATSINSmove(tmpret0, _057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_utils_057_string_utils_056_sats__tostring_int(arg0)) ;

ATSfunbody_end()
ATSreturn(tmpret0) ;
} /* end of [istr_0] */

/*
/home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/spdx_audit.dats: 759(line=24, offs=30) -- 1578(line=45, offs=4)
*/
/*
local: istr_0$0(level=0)
global: istr_0$0(level=0), count_missing_spdx$1$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_t0ype(atstype_int)
_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_spdx_audit_056_sats__count_missing_spdx(atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret1, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp2, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp30, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp31, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp32, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp33, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp34, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp35, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp36, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp37, atstype_boxed) ;
ATStmpdec(tmp44, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp45, atstkind_type(atstype_ptrk)) ;
// ATStmpdec_void(tmp74) ;
ATStmpdec(tmp75, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp76, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp77, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/spdx_audit.dats: 740(line=24, offs=11) -- 1578(line=45, offs=4)
*/
ATSINSflab(__patsflab_count_missing_spdx):
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/spdx_audit.dats: 783(line=24, offs=54) -- 1578(line=45, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/spdx_audit.dats: 798(line=25, offs=12) -- 830(line=25, offs=44)
*/
ATSINSmove(tmp2, ATSLIB_056_prelude__string0_append__2__1(ATSPMVstring("find "), arg0)) ;

/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/spdx_audit.dats: 842(line=26, offs=12) -- 878(line=26, offs=48)
*/
ATSINSmove(tmp30, _057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_utils_057_string_utils_056_sats__strptr_append_str(tmp2, ATSPMVstring(" -maxdepth "))) ;

/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/spdx_audit.dats: 915(line=27, offs=37) -- 929(line=27, offs=51)
*/
ATSINSmove(tmp32, istr_0(arg1)) ;

/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/spdx_audit.dats: 890(line=27, offs=12) -- 931(line=27, offs=53)
*/
ATSINSmove(tmp31, _057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_utils_057_string_utils_056_sats__strptr_append_strptr(tmp30, tmp32)) ;

/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/spdx_audit.dats: 943(line=28, offs=12) -- 1169(line=28, offs=238)
*/
ATSINSmove(tmp33, _057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_utils_057_string_utils_056_sats__strptr_append_str(tmp31, ATSPMVstring(" -type f \\( -name '*.dats' -o -name '*.sats' -o -name '*.rs' -o -name '*.zig' -o -name '*.idr' \\) 2>/dev/null | xargs -r grep -L 'SPDX-License-Identifier:' 2>/dev/null | wc -l > /tmp/.rb56_spdx_audit"))) ;

/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/spdx_audit.dats: 1181(line=29, offs=12) -- 1197(line=29, offs=28)
*/
ATSINSmove(tmp34, _057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_effects_056_sats__sys_run_owned(tmp33)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/spdx_audit.dats: 1208(line=31, offs=7) -- 1219(line=31, offs=18)
*/
ATSINSmove(tmp36, _057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_effects_056_sats__wexit_ok(tmp34)) ;

/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/spdx_audit.dats: 1207(line=31, offs=6) -- 1219(line=31, offs=18)
*/
ATSINSmove(tmp35, atspre_neg_bool0(tmp36)) ;

/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/spdx_audit.dats: 1204(line=31, offs=3) -- 1574(line=44, offs=6)
*/
ATSif(
tmp35
) ATSthen() {
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/spdx_audit.dats: 1226(line=31, offs=25) -- 1228(line=31, offs=27)
*/
ATSINSmove(tmpret1, atspre_g1int_neg_int(ATSPMVi0nt(1))) ;

} ATSelse() {
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/spdx_audit.dats: 1236(line=32, offs=8) -- 1574(line=44, offs=6)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/spdx_audit.dats: 1252(line=33, offs=13) -- 1306(line=33, offs=67)
*/
ATSINSmove(tmp37, ATSLIB_056_prelude__fileref_open_opt__12__1(ATSPMVstring("/tmp/.rb56_spdx_audit"), atspre_file_mode_r)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/spdx_audit.dats: 1316(line=35, offs=5) -- 1568(line=43, offs=22)
*/
ATScaseof_beg()
/*
** ibranchlst-beg
*/
ATSbranch_beg()
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/spdx_audit.dats: 1333(line=36, offs=7) -- 1345(line=36, offs=19)
*/
ATSINSlab(__atstmplab0):
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/spdx_audit.dats: 1252(line=33, offs=13) -- 1306(line=33, offs=67)
*/
ATSifthen(ATSCKptrisnull(tmp37)) { ATSINSgoto(__atstmplab3) ; } ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/spdx_audit.dats: 1345(line=36, offs=19) -- 1345(line=36, offs=19)
*/
ATSINSlab(__atstmplab1):
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/spdx_audit.dats: 1342(line=36, offs=16) -- 1344(line=36, offs=18)
*/
ATSINSmove(tmp44, ATSSELcon(tmp37, postiats_tysum_1, atslab__0)) ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/spdx_audit.dats: 1333(line=36, offs=7) -- 1546(line=42, offs=10)
*/
ATSINSfreecon(tmp37) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/spdx_audit.dats: 1349(line=36, offs=23) -- 1546(line=42, offs=10)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/spdx_audit.dats: 1372(line=37, offs=20) -- 1398(line=37, offs=46)
*/
ATSINSmove(tmp45, ATSLIB_056_prelude__fileref_get_line_string__14__1(tmp44)) ;

/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/spdx_audit.dats: 1417(line=38, offs=18) -- 1433(line=38, offs=34)
*/
ATSINSmove_void(tmp74, atspre_fileref_close(tmp44)) ;

/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/spdx_audit.dats: 1473(line=39, offs=39) -- 1494(line=39, offs=60)
*/
ATSINSmove(tmp76, _057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_utils_057_string_utils_056_sats__strptr_trim_free(tmp45)) ;

/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/spdx_audit.dats: 1451(line=39, offs=17) -- 1496(line=39, offs=62)
*/
ATSINSmove(tmp75, _057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_utils_057_string_utils_056_sats__strptr_parse_int_free(tmp76)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/spdx_audit.dats: 1517(line=41, offs=12) -- 1522(line=41, offs=17)
*/
ATSINSmove(tmp77, ATSLIB_056_prelude__lt_g0int_int__26__1(tmp75, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/spdx_audit.dats: 1514(line=41, offs=9) -- 1536(line=41, offs=31)
*/
ATSif(
tmp77
) ATSthen() {
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/spdx_audit.dats: 1528(line=41, offs=23) -- 1529(line=41, offs=24)
*/
ATSINSmove(tmpret1, ATSPMVi0nt(0)) ;
} ATSelse() {
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/spdx_audit.dats: 1535(line=41, offs=30) -- 1536(line=41, offs=31)
*/
ATSINSmove(tmpret1, tmp75) ;
} /* ATSendif */
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/spdx_audit.dats: 1349(line=36, offs=23) -- 1546(line=42, offs=10)
*/
/*
INSletpop()
*/
ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/spdx_audit.dats: 1553(line=43, offs=7) -- 1563(line=43, offs=17)
*/
ATSINSlab(__atstmplab2):
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/spdx_audit.dats: 1252(line=33, offs=13) -- 1306(line=33, offs=67)
*/
#if(0)
ATSifthen(ATSCKptriscons(tmp37)) { ATSINSdeadcode_fail() ; } ;
#endif
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/spdx_audit.dats: 1563(line=43, offs=17) -- 1563(line=43, offs=17)
*/
ATSINSlab(__atstmplab3):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/spdx_audit.dats: 1567(line=43, offs=21) -- 1568(line=43, offs=22)
*/
ATSINSmove(tmpret1, ATSPMVi0nt(0)) ;
ATSbranch_end()

/*
** ibranchlst-end
*/
ATScaseof_end()

/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/spdx_audit.dats: 1236(line=32, offs=8) -- 1574(line=44, offs=6)
*/
/*
INSletpop()
*/
} /* ATSendif */
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/spdx_audit.dats: 783(line=24, offs=54) -- 1578(line=45, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret1) ;
} /* end of [_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_spdx_audit_056_sats__count_missing_spdx] */

#if(0)
/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats: 14884(line=842, offs=3) -- 15043(line=851, offs=4)
*/
/*
local: 
global: string0_append$2$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = 
tmparg = 
tmpsub = None()
*/
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__string0_append__2(atstkind_type(atstype_ptrk) arg0, atstkind_type(atstype_ptrk) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret3, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp4, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 14867(line=841, offs=1) -- 15043(line=851, offs=4)
*/
ATSINSflab(__patsflab_string0_append):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 14895(line=842, offs=14) -- 15043(line=851, offs=4)
*/
/*
letpush(beg)
*/
/* (*nothing*) */
/* (*nothing*) */
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 14952(line=846, offs=11) -- 14974(line=846, offs=33)
*/
ATSINSmove(tmp4, PMVtmpltcst(string1_append<>)(ATSPMVcastfn(g1ofg0_string, atstkind_type(atstype_ptrk), arg0), ATSPMVcastfn(g1ofg0_string, atstkind_type(atstype_ptrk), arg1))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15019(line=850, offs=3) -- 15038(line=850, offs=22)
*/
ATSINSmove(tmpret3, ATSPMVcastfn(strnptr2strptr, atstkind_type(atstype_ptrk), tmp4)) ;
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 14895(line=842, offs=14) -- 15043(line=851, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret3) ;
} /* end of [ATSLIB_056_prelude__string0_append__2] */
#endif // end of [TEMPLATE]

/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats: 14884(line=842, offs=3) -- 15043(line=851, offs=4)
*/
/*
local: 
global: string0_append$2$1(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = 
tmparg = 
tmpsub = Some()
*/
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__string0_append__2__1(atstkind_type(atstype_ptrk) arg0, atstkind_type(atstype_ptrk) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret3__1, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp4__1, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 14867(line=841, offs=1) -- 15043(line=851, offs=4)
*/
ATSINSflab(__patsflab_string0_append):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 14895(line=842, offs=14) -- 15043(line=851, offs=4)
*/
/*
letpush(beg)
*/
/* (*nothing*) */
/* (*nothing*) */
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 14952(line=846, offs=11) -- 14974(line=846, offs=33)
*/
ATSINSmove(tmp4__1, ATSLIB_056_prelude__string1_append__4__1(ATSPMVcastfn(g1ofg0_string, atstkind_type(atstype_ptrk), arg0), ATSPMVcastfn(g1ofg0_string, atstkind_type(atstype_ptrk), arg1))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15019(line=850, offs=3) -- 15038(line=850, offs=22)
*/
ATSINSmove(tmpret3__1, ATSPMVcastfn(strnptr2strptr, atstkind_type(atstype_ptrk), tmp4__1)) ;
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 14895(line=842, offs=14) -- 15043(line=851, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret3__1) ;
} /* end of [ATSLIB_056_prelude__string0_append__2__1] */

#if(0)
/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats: 15116(line=856, offs=10) -- 15385(line=868, offs=4)
*/
/*
local: 
global: string1_append$4$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = 
tmparg = 
tmpsub = None()
*/
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__string1_append__4(atstkind_type(atstype_ptrk) arg0, atstkind_type(atstype_ptrk) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret7, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp8, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp9, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp10, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp11, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp12, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp13, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp14, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp15, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp16, atstkind_t0ype(atstype_size)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15092(line=855, offs=1) -- 15385(line=868, offs=4)
*/
ATSINSflab(__patsflab_string1_append):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15127(line=856, offs=21) -- 15385(line=868, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15143(line=858, offs=10) -- 15152(line=858, offs=19)
*/
ATSINSmove(tmp8, PMVtmpltcst(string1_length<>)(arg0)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15163(line=858, offs=30) -- 15172(line=858, offs=39)
*/
ATSINSmove(tmp9, PMVtmpltcst(string1_length<>)(arg1)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15187(line=860, offs=11) -- 15194(line=860, offs=18)
*/
ATSINSmove(tmp10, PMVtmpltcst(g1uint_add<S2Eextkind(atstype_size)>)(tmp8, tmp9)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15225(line=861, offs=31) -- 15233(line=861, offs=39)
*/
ATSINSmove(tmp12, PMVtmpltcst(g1uint_succ<S2Eextkind(atstype_size)>)(tmp10)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15215(line=861, offs=21) -- 15235(line=861, offs=41)
*/
ATSINSmove(tmp11, atspre_malloc_gc(tmp12)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15248(line=863, offs=10) -- 15277(line=863, offs=39)
*/
ATSINSmove(tmp13, atspre_string_memcpy(tmp11, ATSPMVcastfn(string2ptr, atstkind_type(atstype_ptrk), arg0), tmp8)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15294(line=864, offs=17) -- 15300(line=864, offs=23)
*/
ATSINSmove(tmp15, atspre_add_ptr1_bsz(tmp11, tmp8)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15318(line=864, offs=41) -- 15325(line=864, offs=48)
*/
ATSINSmove(tmp16, PMVtmpltcst(g1uint_succ<S2Eextkind(atstype_size)>)(tmp9)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15287(line=864, offs=10) -- 15327(line=864, offs=50)
*/
ATSINSmove(tmp14, atspre_string_memcpy(tmp15, ATSPMVcastfn(string2ptr, atstkind_type(atstype_ptrk), arg1), tmp16)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15336(line=867, offs=3) -- 15381(line=867, offs=48)
*/
ATSINSmove(tmpret7, ATSPMVcastfn(castvwtp0, atstkind_type(atstype_ptrk), tmp11)) ;
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15127(line=856, offs=21) -- 15385(line=868, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret7) ;
} /* end of [ATSLIB_056_prelude__string1_append__4] */
#endif // end of [TEMPLATE]

/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats: 15116(line=856, offs=10) -- 15385(line=868, offs=4)
*/
/*
local: 
global: string1_append$4$1(level=2)
local: 
global: 
*/
ATSstatic()
/*
imparg = 
tmparg = 
tmpsub = Some()
*/
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__string1_append__4__1(atstkind_type(atstype_ptrk) arg0, atstkind_type(atstype_ptrk) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret7__1, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp8__1, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp9__1, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp10__1, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp11__1, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp12__1, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp13__1, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp14__1, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp15__1, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp16__1, atstkind_t0ype(atstype_size)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15092(line=855, offs=1) -- 15385(line=868, offs=4)
*/
ATSINSflab(__patsflab_string1_append):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15127(line=856, offs=21) -- 15385(line=868, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15143(line=858, offs=10) -- 15152(line=858, offs=19)
*/
ATSINSmove(tmp8__1, ATSLIB_056_prelude__string1_length__6__1(arg0)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15163(line=858, offs=30) -- 15172(line=858, offs=39)
*/
ATSINSmove(tmp9__1, ATSLIB_056_prelude__string1_length__6__2(arg1)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15187(line=860, offs=11) -- 15194(line=860, offs=18)
*/
ATSINSmove(tmp10__1, atspre_g1uint_add_size(tmp8__1, tmp9__1)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15225(line=861, offs=31) -- 15233(line=861, offs=39)
*/
ATSINSmove(tmp12__1, atspre_g1uint_succ_size(tmp10__1)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15215(line=861, offs=21) -- 15235(line=861, offs=41)
*/
ATSINSmove(tmp11__1, atspre_malloc_gc(tmp12__1)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15248(line=863, offs=10) -- 15277(line=863, offs=39)
*/
ATSINSmove(tmp13__1, atspre_string_memcpy(tmp11__1, ATSPMVcastfn(string2ptr, atstkind_type(atstype_ptrk), arg0), tmp8__1)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15294(line=864, offs=17) -- 15300(line=864, offs=23)
*/
ATSINSmove(tmp15__1, atspre_add_ptr1_bsz(tmp11__1, tmp8__1)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15318(line=864, offs=41) -- 15325(line=864, offs=48)
*/
ATSINSmove(tmp16__1, atspre_g1uint_succ_size(tmp9__1)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15287(line=864, offs=10) -- 15327(line=864, offs=50)
*/
ATSINSmove(tmp14__1, atspre_string_memcpy(tmp15__1, ATSPMVcastfn(string2ptr, atstkind_type(atstype_ptrk), arg1), tmp16__1)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15336(line=867, offs=3) -- 15381(line=867, offs=48)
*/
ATSINSmove(tmpret7__1, ATSPMVcastfn(castvwtp0, atstkind_type(atstype_ptrk), tmp11__1)) ;
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15127(line=856, offs=21) -- 15385(line=868, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret7__1) ;
} /* end of [ATSLIB_056_prelude__string1_append__4__1] */

#if(0)
/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats: 11344(line=638, offs=6) -- 11453(line=644, offs=2)
*/
/*
local: 
global: string1_length$6$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = 
tmparg = 
tmpsub = None()
*/
atstkind_t0ype(atstype_size)
ATSLIB_056_prelude__string1_length__6(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret27, atstkind_t0ype(atstype_size)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 11324(line=637, offs=1) -- 11453(line=644, offs=2)
*/
ATSINSflab(__patsflab_string1_length):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 11354(line=639, offs=3) -- 11453(line=644, offs=2)
*/
/*
letpush(beg)
*/
/*
letpush(end)
*/

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 11354(line=639, offs=3) -- 11368(line=639, offs=17)
*/
ATSINSmove(tmpret27, atspre_strlen(arg0)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 11354(line=639, offs=3) -- 11453(line=644, offs=2)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret27) ;
} /* end of [ATSLIB_056_prelude__string1_length__6] */
#endif // end of [TEMPLATE]

/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats: 11344(line=638, offs=6) -- 11453(line=644, offs=2)
*/
/*
local: 
global: string1_length$6$1(level=3)
local: 
global: 
*/
ATSstatic()
/*
imparg = 
tmparg = 
tmpsub = Some()
*/
atstkind_t0ype(atstype_size)
ATSLIB_056_prelude__string1_length__6__1(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret27__1, atstkind_t0ype(atstype_size)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 11324(line=637, offs=1) -- 11453(line=644, offs=2)
*/
ATSINSflab(__patsflab_string1_length):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 11354(line=639, offs=3) -- 11453(line=644, offs=2)
*/
/*
letpush(beg)
*/
/*
letpush(end)
*/

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 11354(line=639, offs=3) -- 11368(line=639, offs=17)
*/
ATSINSmove(tmpret27__1, atspre_strlen(arg0)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 11354(line=639, offs=3) -- 11453(line=644, offs=2)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret27__1) ;
} /* end of [ATSLIB_056_prelude__string1_length__6__1] */

/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats: 11344(line=638, offs=6) -- 11453(line=644, offs=2)
*/
/*
local: 
global: string1_length$6$2(level=3)
local: 
global: 
*/
ATSstatic()
/*
imparg = 
tmparg = 
tmpsub = Some()
*/
atstkind_t0ype(atstype_size)
ATSLIB_056_prelude__string1_length__6__2(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret27__2, atstkind_t0ype(atstype_size)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 11324(line=637, offs=1) -- 11453(line=644, offs=2)
*/
ATSINSflab(__patsflab_string1_length):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 11354(line=639, offs=3) -- 11453(line=644, offs=2)
*/
/*
letpush(beg)
*/
/*
letpush(end)
*/

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 11354(line=639, offs=3) -- 11368(line=639, offs=17)
*/
ATSINSmove(tmpret27__2, atspre_strlen(arg0)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 11354(line=639, offs=3) -- 11453(line=644, offs=2)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret27__2) ;
} /* end of [ATSLIB_056_prelude__string1_length__6__2] */

#if(0)
/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats: 5101(line=258, offs=3) -- 5460(line=286, offs=4)
*/
/*
local: 
global: fileref_open_opt$12$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = 
tmparg = 
tmpsub = None()
*/
atstype_boxed
ATSLIB_056_prelude__fileref_open_opt__12(atstkind_type(atstype_ptrk) arg0, atstkind_type(atstype_ptrk) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret38, atstype_boxed) ;
ATStmpdec(tmp39, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp40, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 5082(line=257, offs=1) -- 5460(line=286, offs=4)
*/
ATSINSflab(__patsflab_fileref_open_opt):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 5114(line=258, offs=16) -- 5460(line=286, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 5132(line=261, offs=8) -- 5155(line=261, offs=31)
*/
ATSINSmove(tmp39, atslib_libats_libc_fopen(arg0, arg1)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 5168(line=263, offs=9) -- 5196(line=263, offs=37)
*/
ATSINSmove(tmp40, atspre_gt_ptr1_intz(ATSPMVcastfn(FILEptr2ptr, atstkind_type(atstype_ptrk), ATSPMVrefarg0(tmp39)), ATSPMVi0nt(0))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 5206(line=267, offs=1) -- 5436(line=284, offs=4)
*/
ATSif(
tmp40
) ATSthen() {
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 5220(line=269, offs=6) -- 5313(line=276, offs=4)
*/
/*
letpush(beg)
*/
/* (*nothing*) */
/*
letpush(end)
*/

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 5276(line=275, offs=3) -- 5297(line=275, offs=24)
*/

/*
#LINCONSTATUS==0
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(tmpret38, postiats_tysum_1) ;
#if(0)
ATSINSstore_con1_tag(tmpret38, 0) ;
#endif
ATSINSstore_con1_ofs(tmpret38, postiats_tysum_1, atslab__0, ATSPMVcastfn(FILEptr_refize, atstkind_type(atstype_ptrk), tmp39)) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 5220(line=269, offs=6) -- 5313(line=276, offs=4)
*/
/*
INSletpop()
*/
} ATSelse() {
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 5395(line=283, offs=3) -- 5421(line=283, offs=29)
*/

ATSINSmove_nil(tmpret38) ;

} /* ATSendif */
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 5114(line=258, offs=16) -- 5460(line=286, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret38) ;
} /* end of [ATSLIB_056_prelude__fileref_open_opt__12] */
#endif // end of [TEMPLATE]

/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats: 5101(line=258, offs=3) -- 5460(line=286, offs=4)
*/
/*
local: 
global: fileref_open_opt$12$1(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = 
tmparg = 
tmpsub = Some()
*/
atstype_boxed
ATSLIB_056_prelude__fileref_open_opt__12__1(atstkind_type(atstype_ptrk) arg0, atstkind_type(atstype_ptrk) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret38__1, atstype_boxed) ;
ATStmpdec(tmp39__1, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp40__1, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 5082(line=257, offs=1) -- 5460(line=286, offs=4)
*/
ATSINSflab(__patsflab_fileref_open_opt):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 5114(line=258, offs=16) -- 5460(line=286, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 5132(line=261, offs=8) -- 5155(line=261, offs=31)
*/
ATSINSmove(tmp39__1, atslib_libats_libc_fopen(arg0, arg1)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 5168(line=263, offs=9) -- 5196(line=263, offs=37)
*/
ATSINSmove(tmp40__1, atspre_gt_ptr1_intz(ATSPMVcastfn(FILEptr2ptr, atstkind_type(atstype_ptrk), ATSPMVrefarg0(tmp39__1)), ATSPMVi0nt(0))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 5206(line=267, offs=1) -- 5436(line=284, offs=4)
*/
ATSif(
tmp40__1
) ATSthen() {
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 5220(line=269, offs=6) -- 5313(line=276, offs=4)
*/
/*
letpush(beg)
*/
/* (*nothing*) */
/*
letpush(end)
*/

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 5276(line=275, offs=3) -- 5297(line=275, offs=24)
*/

/*
#LINCONSTATUS==0
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(tmpret38__1, postiats_tysum_1) ;
#if(0)
ATSINSstore_con1_tag(tmpret38__1, 0) ;
#endif
ATSINSstore_con1_ofs(tmpret38__1, postiats_tysum_1, atslab__0, ATSPMVcastfn(FILEptr_refize, atstkind_type(atstype_ptrk), tmp39__1)) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 5220(line=269, offs=6) -- 5313(line=276, offs=4)
*/
/*
INSletpop()
*/
} ATSelse() {
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 5395(line=283, offs=3) -- 5421(line=283, offs=29)
*/

ATSINSmove_nil(tmpret38__1) ;

} /* ATSendif */
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 5114(line=258, offs=16) -- 5460(line=286, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret38__1) ;
} /* end of [ATSLIB_056_prelude__fileref_open_opt__12__1] */

#if(0)
/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats: 10106(line=574, offs=3) -- 10272(line=582, offs=4)
*/
/*
local: 
global: fileref_get_line_string$14$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = 
tmparg = 
tmpsub = None()
*/
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__fileref_get_line_string__14(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret46, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmpref47, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp48, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10080(line=573, offs=1) -- 10272(line=582, offs=4)
*/
ATSINSflab(__patsflab_fileref_get_line_string):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10114(line=574, offs=11) -- 10272(line=582, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10125(line=576, offs=5) -- 10129(line=576, offs=9)
*/
/*
ATSINStmpdec(tmpref47) ;
*/
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10163(line=577, offs=12) -- 10202(line=577, offs=51)
*/
ATSINSmove(tmp48, PMVtmpltcst(fileref_get_line_string_main<>)(arg0, ATSPMVrefarg1(ATSPMVptrof(tmpref47)))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10248(line=581, offs=3) -- 10267(line=581, offs=22)
*/
ATSINSmove(tmpret46, ATSPMVcastfn(strnptr2strptr, atstkind_type(atstype_ptrk), tmp48)) ;
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10114(line=574, offs=11) -- 10272(line=582, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret46) ;
} /* end of [ATSLIB_056_prelude__fileref_get_line_string__14] */
#endif // end of [TEMPLATE]

/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats: 10106(line=574, offs=3) -- 10272(line=582, offs=4)
*/
/*
local: 
global: fileref_get_line_string$14$1(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = 
tmparg = 
tmpsub = Some()
*/
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__fileref_get_line_string__14__1(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret46__1, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmpref47__1, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp48__1, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10080(line=573, offs=1) -- 10272(line=582, offs=4)
*/
ATSINSflab(__patsflab_fileref_get_line_string):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10114(line=574, offs=11) -- 10272(line=582, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10125(line=576, offs=5) -- 10129(line=576, offs=9)
*/
/*
ATSINStmpdec(tmpref47) ;
*/
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10163(line=577, offs=12) -- 10202(line=577, offs=51)
*/
ATSINSmove(tmp48__1, ATSLIB_056_prelude__fileref_get_line_string_main__16__1(arg0, ATSPMVrefarg1(ATSPMVptrof(tmpref47__1)))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10248(line=581, offs=3) -- 10267(line=581, offs=22)
*/
ATSINSmove(tmpret46__1, ATSPMVcastfn(strnptr2strptr, atstkind_type(atstype_ptrk), tmp48__1)) ;
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10114(line=574, offs=11) -- 10272(line=582, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret46__1) ;
} /* end of [ATSLIB_056_prelude__fileref_get_line_string__14__1] */

#if(0)
/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats: 10382(line=589, offs=3) -- 11000(line=628, offs=4)
*/
/*
local: 
global: fileref_get_line_string_main$16$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = 
tmparg = 
tmpsub = None()
*/
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__fileref_get_line_string_main__16(atstkind_type(atstype_ptrk) arg0, atsrefarg1_type(atstkind_t0ype(atstype_int)) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret52, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp53, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp54, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp55, atstkind_t0ype(atstype_bool)) ;
// ATStmpdec_void(tmp56) ;
// ATStmpdec_void(tmp57) ;
ATStmpdec(tmp58, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10351(line=588, offs=1) -- 11000(line=628, offs=4)
*/
ATSINSflab(__patsflab_fileref_get_line_string_main):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10396(line=589, offs=17) -- 11000(line=628, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10413(line=593, offs=1) -- 10448(line=593, offs=36)
*/
ATSINSmove(tmp53, PMVtmpltcst(fileref_get_line_string$bufsize<>)()) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10477(line=597, offs=7) -- 10564(line=601, offs=2)
*/
ATSINSmove(tmp54, ATSextfcall(atspre_fileref_get_line_string_main2, (tmp53, arg0, arg1))) ;
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10735(line=613, offs=13) -- 10757(line=613, offs=35)
*/
ATSINSmove(tmp55, PMVtmpltcst(strnptr_isnot_null<>)(ATSPMVrefarg0(tmp54))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10768(line=617, offs=1) -- 10975(line=626, offs=4)
*/
ATSif(
tmp55
) ATSthen() {
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10782(line=619, offs=6) -- 10785(line=619, offs=9)
*/
ATSINSmove(tmpret52, tmp54) ;
} ATSelse() {
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10791(line=619, offs=15) -- 10975(line=626, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10808(line=621, offs=3) -- 10872(line=622, offs=48)
*/
ATSINSmove_void(tmp56, atspre_exit_errmsg_void(ATSPMVi0nt(1), ATSPMVstring("[fileref_get_line_string_main] failed."))) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10892(line=623, offs=20) -- 10901(line=623, offs=29)
*/
ATSINSmove(tmp58, PMVtmpltcst(gte_g1int_int<S2Eextkind(atstype_int)>)(ATSderef(arg1, atstkind_t0ype(atstype_int)), ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10884(line=623, offs=12) -- 10902(line=623, offs=30)
*/
ATSINSmove_void(tmp57, atspre_assert_bool1(tmp58)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10934(line=625, offs=3) -- 10937(line=625, offs=6)
*/
ATSINSmove(tmpret52, tmp54) ;
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10791(line=619, offs=15) -- 10975(line=626, offs=4)
*/
/*
INSletpop()
*/
} /* ATSendif */
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10396(line=589, offs=17) -- 11000(line=628, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret52) ;
} /* end of [ATSLIB_056_prelude__fileref_get_line_string_main__16] */
#endif // end of [TEMPLATE]

/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats: 10382(line=589, offs=3) -- 11000(line=628, offs=4)
*/
/*
local: 
global: fileref_get_line_string_main$16$1(level=2)
local: 
global: 
*/
ATSstatic()
/*
imparg = 
tmparg = 
tmpsub = Some()
*/
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__fileref_get_line_string_main__16__1(atstkind_type(atstype_ptrk) arg0, atsrefarg1_type(atstkind_t0ype(atstype_int)) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret52__1, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp53__1, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp54__1, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp55__1, atstkind_t0ype(atstype_bool)) ;
// ATStmpdec_void(tmp56__1) ;
// ATStmpdec_void(tmp57__1) ;
ATStmpdec(tmp58__1, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10351(line=588, offs=1) -- 11000(line=628, offs=4)
*/
ATSINSflab(__patsflab_fileref_get_line_string_main):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10396(line=589, offs=17) -- 11000(line=628, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10413(line=593, offs=1) -- 10448(line=593, offs=36)
*/
ATSINSmove(tmp53__1, ATSLIB_056_prelude__fileref_get_line_string__bufsize__18__1()) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10477(line=597, offs=7) -- 10564(line=601, offs=2)
*/
ATSINSmove(tmp54__1, ATSextfcall(atspre_fileref_get_line_string_main2, (tmp53__1, arg0, arg1))) ;
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10735(line=613, offs=13) -- 10757(line=613, offs=35)
*/
ATSINSmove(tmp55__1, ATSLIB_056_prelude__strnptr_isnot_null__20__1(ATSPMVrefarg0(tmp54__1))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10768(line=617, offs=1) -- 10975(line=626, offs=4)
*/
ATSif(
tmp55__1
) ATSthen() {
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10782(line=619, offs=6) -- 10785(line=619, offs=9)
*/
ATSINSmove(tmpret52__1, tmp54__1) ;
} ATSelse() {
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10791(line=619, offs=15) -- 10975(line=626, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10808(line=621, offs=3) -- 10872(line=622, offs=48)
*/
ATSINSmove_void(tmp56__1, atspre_exit_errmsg_void(ATSPMVi0nt(1), ATSPMVstring("[fileref_get_line_string_main] failed."))) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10892(line=623, offs=20) -- 10901(line=623, offs=29)
*/
ATSINSmove(tmp58__1, ATSLIB_056_prelude__gte_g1int_int__22__1(ATSderef(arg1, atstkind_t0ype(atstype_int)), ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10884(line=623, offs=12) -- 10902(line=623, offs=30)
*/
ATSINSmove_void(tmp57__1, atspre_assert_bool1(tmp58__1)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10934(line=625, offs=3) -- 10937(line=625, offs=6)
*/
ATSINSmove(tmpret52__1, tmp54__1) ;
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10791(line=619, offs=15) -- 10975(line=626, offs=4)
*/
/*
INSletpop()
*/
} /* ATSendif */
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 10396(line=589, offs=17) -- 11000(line=628, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret52__1) ;
} /* end of [ATSLIB_056_prelude__fileref_get_line_string_main__16__1] */

#if(0)
/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats: 9967(line=564, offs=32) -- 9974(line=564, offs=39)
*/
/*
local: 
global: fileref_get_line_string$bufsize$18$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = 
tmparg = 
tmpsub = None()
*/
atstkind_t0ype(atstype_int)
ATSLIB_056_prelude__fileref_get_line_string__bufsize__18()
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret66, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 9936(line=564, offs=1) -- 9974(line=564, offs=39)
*/
ATSINSflab(__patsflab_fileref_get_line_string__bufsize):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 9972(line=564, offs=37) -- 9974(line=564, offs=39)
*/
ATSINSmove(tmpret66, ATSPMVi0nt(64)) ;
ATSfunbody_end()
ATSreturn(tmpret66) ;
} /* end of [ATSLIB_056_prelude__fileref_get_line_string__bufsize__18] */
#endif // end of [TEMPLATE]

/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats: 9967(line=564, offs=32) -- 9974(line=564, offs=39)
*/
/*
local: 
global: fileref_get_line_string$bufsize$18$1(level=3)
local: 
global: 
*/
ATSstatic()
/*
imparg = 
tmparg = 
tmpsub = Some()
*/
atstkind_t0ype(atstype_int)
ATSLIB_056_prelude__fileref_get_line_string__bufsize__18__1()
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret66__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 9936(line=564, offs=1) -- 9974(line=564, offs=39)
*/
ATSINSflab(__patsflab_fileref_get_line_string__bufsize):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/filebas.dats({$PATSPRE}/DATS/filebas.dats): 9972(line=564, offs=37) -- 9974(line=564, offs=39)
*/
ATSINSmove(tmpret66__1, ATSPMVi0nt(64)) ;
ATSfunbody_end()
ATSreturn(tmpret66__1) ;
} /* end of [ATSLIB_056_prelude__fileref_get_line_string__bufsize__18__1] */

#if(0)
/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/strptr.dats: 4111(line=188, offs=20) -- 4146(line=188, offs=55)
*/
/*
local: 
global: strnptr_isnot_null$20$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = 
tmparg = 
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__strnptr_isnot_null__20(atsrefarg0_type(atstkind_type(atstype_ptrk)) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret68, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/strptr.dats({$PATSPRE}/DATS/strptr.dats): 4092(line=188, offs=1) -- 4146(line=188, offs=55)
*/
ATSINSflab(__patsflab_strnptr_isnot_null):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/strptr.dats({$PATSPRE}/DATS/strptr.dats): 4120(line=188, offs=29) -- 4145(line=188, offs=54)
*/
ATSINSmove(tmpret68, atspre_gt_ptr1_ptr1(ATSPMVcastfn(strnptr2ptr, atstkind_type(atstype_ptrk), ATSPMVrefarg0(arg0)), the_atsptr_null)) ;

ATSfunbody_end()
ATSreturn(tmpret68) ;
} /* end of [ATSLIB_056_prelude__strnptr_isnot_null__20] */
#endif // end of [TEMPLATE]

/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/strptr.dats: 4111(line=188, offs=20) -- 4146(line=188, offs=55)
*/
/*
local: 
global: strnptr_isnot_null$20$1(level=3)
local: 
global: 
*/
ATSstatic()
/*
imparg = 
tmparg = 
tmpsub = Some()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__strnptr_isnot_null__20__1(atsrefarg0_type(atstkind_type(atstype_ptrk)) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret68__1, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/strptr.dats({$PATSPRE}/DATS/strptr.dats): 4092(line=188, offs=1) -- 4146(line=188, offs=55)
*/
ATSINSflab(__patsflab_strnptr_isnot_null):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/strptr.dats({$PATSPRE}/DATS/strptr.dats): 4120(line=188, offs=29) -- 4145(line=188, offs=54)
*/
ATSINSmove(tmpret68__1, atspre_gt_ptr1_ptr1(ATSPMVcastfn(strnptr2ptr, atstkind_type(atstype_ptrk), ATSPMVrefarg0(arg0)), the_atsptr_null)) ;

ATSfunbody_end()
ATSreturn(tmpret68__1) ;
} /* end of [ATSLIB_056_prelude__strnptr_isnot_null__20__1] */

#if(0)
/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats: 12757(line=663, offs=3) -- 12797(line=663, offs=43)
*/
/*
local: 
global: gte_g1int_int$22$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = tk(4646)
tmparg = S2Evar(tk(4646))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gte_g1int_int__22(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret70, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp71, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12741(line=662, offs=1) -- 12797(line=663, offs=43)
*/
ATSINSflab(__patsflab_gte_g1int_int):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12784(line=663, offs=30) -- 12795(line=663, offs=41)
*/
ATSINSmove(tmp71, PMVtmpltcst(g1int2int<S2Eextkind(atstype_int), S2Evar(tk(4646))>)(arg1)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12766(line=663, offs=12) -- 12797(line=663, offs=43)
*/
ATSINSmove(tmpret70, PMVtmpltcst(g1int_gte<S2Evar(tk(4646))>)(arg0, tmp71)) ;

ATSfunbody_end()
ATSreturn(tmpret70) ;
} /* end of [ATSLIB_056_prelude__gte_g1int_int__22] */
#endif // end of [TEMPLATE]

/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats: 12757(line=663, offs=3) -- 12797(line=663, offs=43)
*/
/*
local: 
global: gte_g1int_int$22$1(level=3)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4646)
tmparg = S2Evar(tk(4646))
tmpsub = Some(tk(4646) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gte_g1int_int__22__1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret70__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp71__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12741(line=662, offs=1) -- 12797(line=663, offs=43)
*/
ATSINSflab(__patsflab_gte_g1int_int):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12784(line=663, offs=30) -- 12795(line=663, offs=41)
*/
ATSINSmove(tmp71__1, atspre_g1int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12766(line=663, offs=12) -- 12797(line=663, offs=43)
*/
ATSINSmove(tmpret70__1, atspre_g1int_gte_int(arg0, tmp71__1)) ;

ATSfunbody_end()
ATSreturn(tmpret70__1) ;
} /* end of [ATSLIB_056_prelude__gte_g1int_int__22__1] */

#if(0)
/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats: 11941(line=617, offs=3) -- 11980(line=617, offs=42)
*/
/*
local: 
global: lt_g0int_int$26$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = tk(4630)
tmparg = S2Evar(tk(4630))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__lt_g0int_int__26(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret78, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp79, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11926(line=616, offs=1) -- 11980(line=617, offs=42)
*/
ATSINSflab(__patsflab_lt_g0int_int):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11967(line=617, offs=29) -- 11978(line=617, offs=40)
*/
ATSINSmove(tmp79, PMVtmpltcst(g0int2int<S2Eextkind(atstype_int), S2Evar(tk(4630))>)(arg1)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11950(line=617, offs=12) -- 11980(line=617, offs=42)
*/
ATSINSmove(tmpret78, PMVtmpltcst(g0int_lt<S2Evar(tk(4630))>)(arg0, tmp79)) ;

ATSfunbody_end()
ATSreturn(tmpret78) ;
} /* end of [ATSLIB_056_prelude__lt_g0int_int__26] */
#endif // end of [TEMPLATE]

/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats: 11941(line=617, offs=3) -- 11980(line=617, offs=42)
*/
/*
local: 
global: lt_g0int_int$26$1(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4630)
tmparg = S2Evar(tk(4630))
tmpsub = Some(tk(4630) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__lt_g0int_int__26__1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret78__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp79__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11926(line=616, offs=1) -- 11980(line=617, offs=42)
*/
ATSINSflab(__patsflab_lt_g0int_int):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11967(line=617, offs=29) -- 11978(line=617, offs=40)
*/
ATSINSmove(tmp79__1, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11950(line=617, offs=12) -- 11980(line=617, offs=42)
*/
ATSINSmove(tmpret78__1, atspre_g0int_lt_int(arg0, tmp79__1)) ;

ATSfunbody_end()
ATSreturn(tmpret78__1) ;
} /* end of [ATSLIB_056_prelude__lt_g0int_int__26__1] */

/*
/home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/spdx_audit.dats: 1609(line=47, offs=30) -- 2136(line=59, offs=4)
*/
/*
local: 
global: execute_spdx_audit$30$0(level=0)
local: 
global: 
*/
ATSextern()
postiats_tyrec_0
_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_spdx_audit_056_sats__execute_spdx_audit(atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret82, postiats_tyrec_0) ;
ATStmpdec(tmp83, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp84, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp87, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/spdx_audit.dats: 1590(line=47, offs=11) -- 2136(line=59, offs=4)
*/
ATSINSflab(__patsflab_execute_spdx_audit):
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/spdx_audit.dats: 1633(line=47, offs=54) -- 2136(line=59, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/spdx_audit.dats: 1650(line=48, offs=14) -- 1689(line=48, offs=53)
*/
ATSINSmove(tmp83, _057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_spdx_audit_056_sats__count_missing_spdx(arg0, arg1)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/spdx_audit.dats: 1698(line=50, offs=6) -- 1706(line=50, offs=14)
*/
ATSINSmove(tmp84, ATSLIB_056_prelude__lt_g0int_int__26__2(tmp83, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/spdx_audit.dats: 1695(line=50, offs=3) -- 2132(line=58, offs=84)
*/
ATSif(
tmp84
) ATSthen() {
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/spdx_audit.dats: 1712(line=50, offs=20) -- 1817(line=52, offs=42)
*/
ATSINSmove_fltrec_beg()
ATSINSstore_fltrec_ofs(tmpret82, postiats_tyrec_0, atslab__success_count, ATSPMVi0nt(0)) ;
ATSINSstore_fltrec_ofs(tmpret82, postiats_tyrec_0, atslab__failure_count, ATSPMVi0nt(1)) ;
ATSINSstore_fltrec_ofs(tmpret82, postiats_tyrec_0, atslab__skipped_count, ATSPMVi0nt(0)) ;
ATSINSstore_fltrec_ofs(tmpret82, postiats_tyrec_0, atslab__message, ATSPMVstring("spdx-audit: scan failed")) ;
ATSINSmove_fltrec_end()
} ATSelse() {
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/spdx_audit.dats: 1828(line=53, offs=11) -- 1836(line=53, offs=19)
*/
ATSINSmove(tmp87, ATSLIB_056_prelude__eq_g0int_int__32__1(tmp83, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/spdx_audit.dats: 1825(line=53, offs=8) -- 2132(line=58, offs=84)
*/
ATSif(
tmp87
) ATSthen() {
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/spdx_audit.dats: 1842(line=53, offs=25) -- 1974(line=55, offs=69)
*/
ATSINSmove_fltrec_beg()
ATSINSstore_fltrec_ofs(tmpret82, postiats_tyrec_0, atslab__success_count, ATSPMVi0nt(1)) ;
ATSINSstore_fltrec_ofs(tmpret82, postiats_tyrec_0, atslab__failure_count, ATSPMVi0nt(0)) ;
ATSINSstore_fltrec_ofs(tmpret82, postiats_tyrec_0, atslab__skipped_count, ATSPMVi0nt(0)) ;
ATSINSstore_fltrec_ofs(tmpret82, postiats_tyrec_0, atslab__message, ATSPMVstring("spdx-audit: all scanned files carry an SPDX header")) ;
ATSINSmove_fltrec_end()
} ATSelse() {
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/spdx_audit.dats: 1982(line=56, offs=8) -- 2132(line=58, offs=84)
*/
ATSINSmove_fltrec_beg()
ATSINSstore_fltrec_ofs(tmpret82, postiats_tyrec_0, atslab__success_count, ATSPMVi0nt(0)) ;
ATSINSstore_fltrec_ofs(tmpret82, postiats_tyrec_0, atslab__failure_count, tmp83) ;
ATSINSstore_fltrec_ofs(tmpret82, postiats_tyrec_0, atslab__skipped_count, ATSPMVi0nt(0)) ;
ATSINSstore_fltrec_ofs(tmpret82, postiats_tyrec_0, atslab__message, ATSPMVstring("spdx-audit: files missing SPDX header (see /tmp/.rb56_spdx_audit)")) ;
ATSINSmove_fltrec_end()
} /* ATSendif */
} /* ATSendif */
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/spdx_audit.dats: 1633(line=47, offs=54) -- 2136(line=59, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret82) ;
} /* end of [_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_spdx_audit_056_sats__execute_spdx_audit] */

/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats: 11941(line=617, offs=3) -- 11980(line=617, offs=42)
*/
/*
local: 
global: lt_g0int_int$26$2(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4630)
tmparg = S2Evar(tk(4630))
tmpsub = Some(tk(4630) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__lt_g0int_int__26__2(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret78__2, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp79__2, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11926(line=616, offs=1) -- 11980(line=617, offs=42)
*/
ATSINSflab(__patsflab_lt_g0int_int):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11967(line=617, offs=29) -- 11978(line=617, offs=40)
*/
ATSINSmove(tmp79__2, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11950(line=617, offs=12) -- 11980(line=617, offs=42)
*/
ATSINSmove(tmpret78__2, atspre_g0int_lt_int(arg0, tmp79__2)) ;

ATSfunbody_end()
ATSreturn(tmpret78__2) ;
} /* end of [ATSLIB_056_prelude__lt_g0int_int__26__2] */

#if(0)
/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats: 12259(line=635, offs=3) -- 12298(line=635, offs=42)
*/
/*
local: 
global: eq_g0int_int$32$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = tk(4634)
tmparg = S2Evar(tk(4634))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__32(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret88, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp89, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12244(line=634, offs=1) -- 12298(line=635, offs=42)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12285(line=635, offs=29) -- 12296(line=635, offs=40)
*/
ATSINSmove(tmp89, PMVtmpltcst(g0int2int<S2Eextkind(atstype_int), S2Evar(tk(4634))>)(arg1)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12268(line=635, offs=12) -- 12298(line=635, offs=42)
*/
ATSINSmove(tmpret88, PMVtmpltcst(g0int_eq<S2Evar(tk(4634))>)(arg0, tmp89)) ;

ATSfunbody_end()
ATSreturn(tmpret88) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__32] */
#endif // end of [TEMPLATE]

/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats: 12259(line=635, offs=3) -- 12298(line=635, offs=42)
*/
/*
local: 
global: eq_g0int_int$32$1(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4634)
tmparg = S2Evar(tk(4634))
tmpsub = Some(tk(4634) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__32__1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret88__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp89__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12244(line=634, offs=1) -- 12298(line=635, offs=42)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12285(line=635, offs=29) -- 12296(line=635, offs=40)
*/
ATSINSmove(tmp89__1, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12268(line=635, offs=12) -- 12298(line=635, offs=42)
*/
ATSINSmove(tmpret88__1, atspre_g0int_eq_int(arg0, tmp89__1)) ;

ATSfunbody_end()
ATSreturn(tmpret88__1) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__32__1] */

/*
** for initialization(dynloading)
*/
ATSextern()
atsvoid_t0ype
_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_spdx_audit_056_dats__dynload()
{
ATSfunbody_beg()
ATSdynload(/*void*/)
ATSdynloadflag_ext(
_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_spdx_audit_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_spdx_audit_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_spdx_audit_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} /* end of [*_dynload] */

/* ****** ****** */

/* end-of-compilation-unit */
