// SPDX-License-Identifier: MPL-2.0
// Copyright (c) Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
/*
**
** The C code is generated by [ATS/Postiats-0-4-1]
** The starting compilation time is: 2026-5-18: 19h:49m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE_
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
#endif /* _ATS_CCOMP_HEADER_NONE_ */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE_
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/integer_long.cats"
#include "prelude/CATS/integer_size.cats"
#include "prelude/CATS/integer_short.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/fprintf.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE_ */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER_
//
#include _ATS_CCOMP_PRELUDE_USER_
//
#endif /* _ATS_CCOMP_PRELUDE_USER_ */
/*
** for user2-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER2_
//
#include _ATS_CCOMP_PRELUDE_USER2_
//
#endif /* _ATS_CCOMP_PRELUDE_USER2_ */

/*
staload-prologues(beg)
*/
/*
/usr/lib/ats2-postiats-0.4.2/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
/usr/lib/ats2-postiats-0.4.2/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/usr/lib/ats2-postiats-0.4.2/libats/libc/SATS/sys/stat.sats: 1390(line=36, offs=1) -- 1440(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/stat.cats"
/*
/usr/lib/ats2-postiats-0.4.2/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/usr/lib/ats2-postiats-0.4.2/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
/usr/lib/ats2-postiats-0.4.2/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
typedef
ATSstruct {
atstkind_t0ype(atstype_int) atslab__success_count ;
atstkind_t0ype(atstype_int) atslab__failure_count ;
atstkind_t0ype(atstype_int) atslab__skipped_count ;
atstkind_type(atstype_ptrk) atslab__message ;
} postiats_tyrec_0 ;
typedef
ATSstruct {
#if(0)
int contag ;
#endif
atstkind_type(atstype_ptrk) atslab__0 ;
atstype_boxed atslab__1 ;
} postiats_tysum_1 ;
typedef
ATSstruct {
#if(0)
int contag ;
#endif
atstkind_type(atstype_ptrk) atslab__0 ;
} postiats_tysum_2 ;
typedef
ATSstruct {
// #if(1)
int contag ;
// #endif
atstkind_type(atstype_ptrk) atslab__0 ;
} postiats_tysum_3 ;
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(atspre_strptr_free)
ATSdyncst_mac(atspre_eq_string_string)
ATSdyncst_extfun(_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_utils_057_string_utils_056_sats__string_is_empty, (atstkind_type(atstype_ptrk)), atstkind_t0ype(atstype_bool)) ;
ATSdyncst_extfun(_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_types_056_sats__is_valid_spdx, (atstkind_type(atstype_ptrk)), atstkind_t0ype(atstype_bool)) ;
ATSdyncst_extfun(_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_utils_057_string_utils_056_sats__string_is_nonempty, (atstkind_type(atstype_ptrk)), atstkind_t0ype(atstype_bool)) ;
ATSdyncst_mac(atspre_malloc_gc)
ATSdyncst_mac(atspre_string_memcpy)
ATSdyncst_mac(atspre_add_ptr1_bsz)
ATSdyncst_mac(atspre_strlen)
ATSdyncst_mac(atspre_g1uint_add_size)
ATSdyncst_mac(atspre_g1uint_succ_size)
ATSdyncst_mac(atspre_g0int2int_int_int)
ATSdyncst_mac(atspre_g0int_eq_int)
ATSdyncst_extfun(_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_utils_057_string_utils_056_sats__strptr_prepend_str, (atstkind_type(atstype_ptrk), atstkind_type(atstype_ptrk)), atstkind_type(atstype_ptrk)) ;
ATSdyncst_mac(atspre_g0int_add_int)
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
ATSextern()
atsvoid_t0ype
the_atsexncon_initize
(
  atstype_exnconptr d2c, atstype_string exnmsg
) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
/*
exnconlst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
#ifndef _ATS_CCOMP_ASSUME_CHECK_NONE_
/*
/home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 528(line=18, offs=1) -- 559(line=18, offs=32)
*/
ATSassume(_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_types_056_sats__spdx_id) ;
/*
/home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 560(line=19, offs=1) -- 591(line=19, offs=32)
*/
ATSassume(_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_types_056_sats__nonempty_string) ;
/*
/home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 592(line=20, offs=1) -- 623(line=20, offs=32)
*/
ATSassume(_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_types_056_sats__existing_path) ;
/*
/home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 624(line=21, offs=1) -- 655(line=21, offs=32)
*/
ATSassume(_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_types_056_sats__git_repo) ;
#endif // #ifndef(_ATS_CCOMP_ASSUME_CHECK_NONE_)
/*
assumelst-declaration(end)
*/
ATSstatic()
atstkind_t0ype(atstype_int)
system_owned_0(atstkind_type(atstype_ptrk)) ;

ATSstatic()
atstype_boxed
spdx_list_1() ;

#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_types_056_sats__is_valid_spdx(atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]

ATSstatic()
atstkind_t0ype(atstype_bool)
mem_3(atstkind_type(atstype_ptrk), atstype_boxed) ;

#if(0)
ATSextern()
atstype_boxed
_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_types_056_sats__validate_spdx_id(atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atstype_boxed
_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_types_056_sats__validate_nonempty(atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atstype_boxed
_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_types_056_sats__validate_path_exists(atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]

#if(0)
#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__string0_append__7(atstkind_type(atstype_ptrk), atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__string0_append__7__1(atstkind_type(atstype_ptrk), atstkind_type(atstype_ptrk)) ;

#if(0)
#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__string1_append__9(atstkind_type(atstype_ptrk), atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__string1_append__9__1(atstkind_type(atstype_ptrk), atstkind_type(atstype_ptrk)) ;

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_size)
ATSLIB_056_prelude__string1_length__11(atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_size)
ATSLIB_056_prelude__string1_length__11__1(atstkind_type(atstype_ptrk)) ;

ATSstatic()
atstkind_t0ype(atstype_size)
ATSLIB_056_prelude__string1_length__11__2(atstkind_type(atstype_ptrk)) ;

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__16(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__16__1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
ATSextern()
atstype_boxed
_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_types_056_sats__validate_git_repo(atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]

ATSstatic()
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__string0_append__7__2(atstkind_type(atstype_ptrk), atstkind_type(atstype_ptrk)) ;

ATSstatic()
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__string1_append__9__2(atstkind_type(atstype_ptrk), atstkind_type(atstype_ptrk)) ;

ATSstatic()
atstkind_t0ype(atstype_size)
ATSLIB_056_prelude__string1_length__11__3(atstkind_type(atstype_ptrk)) ;

ATSstatic()
atstkind_t0ype(atstype_size)
ATSLIB_056_prelude__string1_length__11__4(atstkind_type(atstype_ptrk)) ;

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__16__2(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_types_056_sats__spdx_unwrap(atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_types_056_sats__nonempty_unwrap(atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_types_056_sats__path_unwrap(atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_types_056_sats__gitrepo_unwrap(atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_types_056_sats__result_message(atstype_boxed) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_types_056_sats__result_is_ok(atstype_boxed) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
postiats_tyrec_0
_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_types_056_sats__empty_batch(atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
postiats_tyrec_0
_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_types_056_sats__batch_add(postiats_tyrec_0, atstype_boxed) ;
#endif // end of [QUALIFIED]

/*
/home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1145(line=30, offs=4) -- 1285(line=33, offs=10)
*/
/*
local: 
global: system_owned_0$0(level=0)
local: 
global: 
*/
ATSstatic()
atstkind_t0ype(atstype_int)
system_owned_0(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret0, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp1, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmp2) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1145(line=30, offs=4) -- 1285(line=33, offs=10)
*/
ATSINSflab(__patsflab_system_owned_0):
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1180(line=30, offs=39) -- 1285(line=33, offs=10)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1195(line=31, offs=12) -- 1247(line=31, offs=64)
*/
ATSINSmove(tmp1, ATSextfcall(system, (ATSPMVcastfn(strptr2string, atstkind_type(atstype_ptrk), ATSPMVrefarg0(arg0))))) ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1259(line=32, offs=12) -- 1274(line=32, offs=27)
*/
ATSINSmove_void(tmp2, atspre_strptr_free(arg0)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1279(line=33, offs=4) -- 1281(line=33, offs=6)
*/
ATSINSmove(tmpret0, tmp1) ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1180(line=30, offs=39) -- 1285(line=33, offs=10)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret0) ;
} /* end of [system_owned_0] */

/*
/home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1407(line=38, offs=4) -- 1680(line=45, offs=4)
*/
/*
local: 
global: spdx_list_1$0(level=0)
local: 
global: 
*/
ATSstatic()
atstype_boxed
spdx_list_1()
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret3, atstype_boxed) ;
ATStmpdec(tmp4, atstype_datconptr) ;
ATStmpdec(tmp5, atstype_datconptr) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1407(line=38, offs=4) -- 1680(line=45, offs=4)
*/
ATSINSflab(__patsflab_spdx_list_1):
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1439(line=39, offs=3) -- 1680(line=45, offs=4)
*/
/*
ATSINStmpdec(tmpret3) ;
*/
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1439(line=39, offs=3) -- 1680(line=45, offs=4)
*/
ATSINSmove(tmp5, ATSPMVptrof(tmpret3)) ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1458(line=40, offs=5) -- 1477(line=40, offs=24)
*/
ATSINSpmove_list_cons(tmp5, atstkind_type(atstype_ptrk)) ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1458(line=40, offs=5) -- 1477(line=40, offs=24)
*/
ATSINSmove_list_phead(tmp4, tmp5, atstkind_type(atstype_ptrk)) ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1458(line=40, offs=5) -- 1477(line=40, offs=24)
*/
ATSINSpmove(tmp4, atstkind_type(atstype_ptrk), ATSPMVstring("PMPL-1.0-or-later")) ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1458(line=40, offs=5) -- 1477(line=40, offs=24)
*/
ATSINSmove_list_ptail(tmp5, tmp5, atstkind_type(atstype_ptrk)) ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1479(line=40, offs=26) -- 1484(line=40, offs=31)
*/
ATSINSpmove_list_cons(tmp5, atstkind_type(atstype_ptrk)) ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1479(line=40, offs=26) -- 1484(line=40, offs=31)
*/
ATSINSmove_list_phead(tmp4, tmp5, atstkind_type(atstype_ptrk)) ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1479(line=40, offs=26) -- 1484(line=40, offs=31)
*/
ATSINSpmove(tmp4, atstkind_type(atstype_ptrk), ATSPMVstring("MIT")) ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1479(line=40, offs=26) -- 1484(line=40, offs=31)
*/
ATSINSmove_list_ptail(tmp5, tmp5, atstkind_type(atstype_ptrk)) ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1486(line=40, offs=33) -- 1498(line=40, offs=45)
*/
ATSINSpmove_list_cons(tmp5, atstkind_type(atstype_ptrk)) ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1486(line=40, offs=33) -- 1498(line=40, offs=45)
*/
ATSINSmove_list_phead(tmp4, tmp5, atstkind_type(atstype_ptrk)) ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1486(line=40, offs=33) -- 1498(line=40, offs=45)
*/
ATSINSpmove(tmp4, atstkind_type(atstype_ptrk), ATSPMVstring("Apache-2.0")) ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1486(line=40, offs=33) -- 1498(line=40, offs=45)
*/
ATSINSmove_list_ptail(tmp5, tmp5, atstkind_type(atstype_ptrk)) ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1504(line=41, offs=5) -- 1518(line=41, offs=19)
*/
ATSINSpmove_list_cons(tmp5, atstkind_type(atstype_ptrk)) ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1504(line=41, offs=5) -- 1518(line=41, offs=19)
*/
ATSINSmove_list_phead(tmp4, tmp5, atstkind_type(atstype_ptrk)) ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1504(line=41, offs=5) -- 1518(line=41, offs=19)
*/
ATSINSpmove(tmp4, atstkind_type(atstype_ptrk), ATSPMVstring("GPL-3.0-only")) ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1504(line=41, offs=5) -- 1518(line=41, offs=19)
*/
ATSINSmove_list_ptail(tmp5, tmp5, atstkind_type(atstype_ptrk)) ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1520(line=41, offs=21) -- 1538(line=41, offs=39)
*/
ATSINSpmove_list_cons(tmp5, atstkind_type(atstype_ptrk)) ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1520(line=41, offs=21) -- 1538(line=41, offs=39)
*/
ATSINSmove_list_phead(tmp4, tmp5, atstkind_type(atstype_ptrk)) ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1520(line=41, offs=21) -- 1538(line=41, offs=39)
*/
ATSINSpmove(tmp4, atstkind_type(atstype_ptrk), ATSPMVstring("GPL-3.0-or-later")) ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1520(line=41, offs=21) -- 1538(line=41, offs=39)
*/
ATSINSmove_list_ptail(tmp5, tmp5, atstkind_type(atstype_ptrk)) ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1544(line=42, offs=5) -- 1559(line=42, offs=20)
*/
ATSINSpmove_list_cons(tmp5, atstkind_type(atstype_ptrk)) ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1544(line=42, offs=5) -- 1559(line=42, offs=20)
*/
ATSINSmove_list_phead(tmp4, tmp5, atstkind_type(atstype_ptrk)) ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1544(line=42, offs=5) -- 1559(line=42, offs=20)
*/
ATSINSpmove(tmp4, atstkind_type(atstype_ptrk), ATSPMVstring("LGPL-3.0-only")) ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1544(line=42, offs=5) -- 1559(line=42, offs=20)
*/
ATSINSmove_list_ptail(tmp5, tmp5, atstkind_type(atstype_ptrk)) ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1561(line=42, offs=22) -- 1580(line=42, offs=41)
*/
ATSINSpmove_list_cons(tmp5, atstkind_type(atstype_ptrk)) ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1561(line=42, offs=22) -- 1580(line=42, offs=41)
*/
ATSINSmove_list_phead(tmp4, tmp5, atstkind_type(atstype_ptrk)) ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1561(line=42, offs=22) -- 1580(line=42, offs=41)
*/
ATSINSpmove(tmp4, atstkind_type(atstype_ptrk), ATSPMVstring("LGPL-3.0-or-later")) ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1561(line=42, offs=22) -- 1580(line=42, offs=41)
*/
ATSINSmove_list_ptail(tmp5, tmp5, atstkind_type(atstype_ptrk)) ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1586(line=43, offs=5) -- 1600(line=43, offs=19)
*/
ATSINSpmove_list_cons(tmp5, atstkind_type(atstype_ptrk)) ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1586(line=43, offs=5) -- 1600(line=43, offs=19)
*/
ATSINSmove_list_phead(tmp4, tmp5, atstkind_type(atstype_ptrk)) ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1586(line=43, offs=5) -- 1600(line=43, offs=19)
*/
ATSINSpmove(tmp4, atstkind_type(atstype_ptrk), ATSPMVstring("BSD-2-Clause")) ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1586(line=43, offs=5) -- 1600(line=43, offs=19)
*/
ATSINSmove_list_ptail(tmp5, tmp5, atstkind_type(atstype_ptrk)) ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1602(line=43, offs=21) -- 1616(line=43, offs=35)
*/
ATSINSpmove_list_cons(tmp5, atstkind_type(atstype_ptrk)) ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1602(line=43, offs=21) -- 1616(line=43, offs=35)
*/
ATSINSmove_list_phead(tmp4, tmp5, atstkind_type(atstype_ptrk)) ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1602(line=43, offs=21) -- 1616(line=43, offs=35)
*/
ATSINSpmove(tmp4, atstkind_type(atstype_ptrk), ATSPMVstring("BSD-3-Clause")) ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1602(line=43, offs=21) -- 1616(line=43, offs=35)
*/
ATSINSmove_list_ptail(tmp5, tmp5, atstkind_type(atstype_ptrk)) ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1618(line=43, offs=37) -- 1623(line=43, offs=42)
*/
ATSINSpmove_list_cons(tmp5, atstkind_type(atstype_ptrk)) ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1618(line=43, offs=37) -- 1623(line=43, offs=42)
*/
ATSINSmove_list_phead(tmp4, tmp5, atstkind_type(atstype_ptrk)) ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1618(line=43, offs=37) -- 1623(line=43, offs=42)
*/
ATSINSpmove(tmp4, atstkind_type(atstype_ptrk), ATSPMVstring("ISC")) ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1618(line=43, offs=37) -- 1623(line=43, offs=42)
*/
ATSINSmove_list_ptail(tmp5, tmp5, atstkind_type(atstype_ptrk)) ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1629(line=44, offs=5) -- 1638(line=44, offs=14)
*/
ATSINSpmove_list_cons(tmp5, atstkind_type(atstype_ptrk)) ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1629(line=44, offs=5) -- 1638(line=44, offs=14)
*/
ATSINSmove_list_phead(tmp4, tmp5, atstkind_type(atstype_ptrk)) ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1629(line=44, offs=5) -- 1638(line=44, offs=14)
*/
ATSINSpmove(tmp4, atstkind_type(atstype_ptrk), ATSPMVstring("MPL-2.0")) ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1629(line=44, offs=5) -- 1638(line=44, offs=14)
*/
ATSINSmove_list_ptail(tmp5, tmp5, atstkind_type(atstype_ptrk)) ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1640(line=44, offs=16) -- 1655(line=44, offs=31)
*/
ATSINSpmove_list_cons(tmp5, atstkind_type(atstype_ptrk)) ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1640(line=44, offs=16) -- 1655(line=44, offs=31)
*/
ATSINSmove_list_phead(tmp4, tmp5, atstkind_type(atstype_ptrk)) ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1640(line=44, offs=16) -- 1655(line=44, offs=31)
*/
ATSINSpmove(tmp4, atstkind_type(atstype_ptrk), ATSPMVstring("AGPL-3.0-only")) ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1640(line=44, offs=16) -- 1655(line=44, offs=31)
*/
ATSINSmove_list_ptail(tmp5, tmp5, atstkind_type(atstype_ptrk)) ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1657(line=44, offs=33) -- 1668(line=44, offs=44)
*/
ATSINSpmove_list_cons(tmp5, atstkind_type(atstype_ptrk)) ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1657(line=44, offs=33) -- 1668(line=44, offs=44)
*/
ATSINSmove_list_phead(tmp4, tmp5, atstkind_type(atstype_ptrk)) ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1657(line=44, offs=33) -- 1668(line=44, offs=44)
*/
ATSINSpmove(tmp4, atstkind_type(atstype_ptrk), ATSPMVstring("Unlicense")) ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1657(line=44, offs=33) -- 1668(line=44, offs=44)
*/
ATSINSmove_list_ptail(tmp5, tmp5, atstkind_type(atstype_ptrk)) ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1670(line=44, offs=46) -- 1676(line=44, offs=52)
*/
ATSINSpmove_list_cons(tmp5, atstkind_type(atstype_ptrk)) ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1670(line=44, offs=46) -- 1676(line=44, offs=52)
*/
ATSINSmove_list_phead(tmp4, tmp5, atstkind_type(atstype_ptrk)) ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1670(line=44, offs=46) -- 1676(line=44, offs=52)
*/
ATSINSpmove(tmp4, atstkind_type(atstype_ptrk), ATSPMVstring("0BSD")) ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1670(line=44, offs=46) -- 1676(line=44, offs=52)
*/
ATSINSmove_list_ptail(tmp5, tmp5, atstkind_type(atstype_ptrk)) ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1439(line=39, offs=3) -- 1680(line=45, offs=4)
*/
ATSINSpmove_list_nil(tmp5) ;
ATSfunbody_end()
ATSreturn(tmpret3) ;
} /* end of [spdx_list_1] */

/*
/home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1705(line=47, offs=24) -- 1920(line=54, offs=4)
*/
/*
local: spdx_list_1$0(level=0)
global: spdx_list_1$0(level=0), is_valid_spdx$2$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_t0ype(atstype_bool)
_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_types_056_sats__is_valid_spdx(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret6, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp11, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp12, atstype_boxed) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1692(line=47, offs=11) -- 1920(line=54, offs=4)
*/
ATSINSflab(__patsflab_is_valid_spdx):
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1711(line=47, offs=30) -- 1920(line=54, offs=4)
*/
/*
letpush(beg)
*/
/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1865(line=53, offs=6) -- 1882(line=53, offs=23)
*/
ATSINSmove(tmp11, _057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_utils_057_string_utils_056_sats__string_is_empty(arg0)) ;

/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1862(line=53, offs=3) -- 1916(line=53, offs=57)
*/
ATSif(
tmp11
) ATSthen() {
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1889(line=53, offs=30) -- 1894(line=53, offs=35)
*/
ATSINSmove(tmpret6, ATSPMVbool_false()) ;
} ATSelse() {
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1904(line=53, offs=45) -- 1915(line=53, offs=56)
*/
ATSINSmove(tmp12, spdx_list_1()) ;

/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1900(line=53, offs=41) -- 1916(line=53, offs=57)
*/
ATSINSmove(tmpret6, mem_3(arg0, tmp12)) ;

} /* ATSendif */
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1711(line=47, offs=30) -- 1920(line=54, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret6) ;
} /* end of [_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_types_056_sats__is_valid_spdx] */

/*
/home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1721(line=48, offs=7) -- 1856(line=51, offs=62)
*/
/*
local: mem_3$0(level=1)
global: mem_3$0(level=1)
local: s$4741(1)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk))))
global: s$4741(1)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk))))
*/
ATSstatic()
atstkind_t0ype(atstype_bool)
mem_3(atstkind_type(atstype_ptrk) env0, atstype_boxed arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(apy0, atstype_boxed) ;
ATStmpdec(tmpret7, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp8, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp9, atstype_boxed) ;
ATStmpdec(tmp10, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1721(line=48, offs=7) -- 1856(line=51, offs=62)
*/
ATSINSflab(__patsflab_mem_3):
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1757(line=49, offs=5) -- 1856(line=51, offs=62)
*/
ATScaseof_beg()
/*
** ibranchlst-beg
*/
ATSbranch_beg()
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1775(line=50, offs=7) -- 1785(line=50, offs=17)
*/
ATSINSlab(__atstmplab0):
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1726(line=48, offs=12) -- 1728(line=48, offs=14)
*/
ATSifthen(ATSCKptriscons(arg0)) { ATSINSgoto(__atstmplab3) ; } ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1785(line=50, offs=17) -- 1785(line=50, offs=17)
*/
ATSINSlab(__atstmplab1):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1789(line=50, offs=21) -- 1794(line=50, offs=26)
*/
ATSINSmove(tmpret7, ATSPMVbool_false()) ;
ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1801(line=51, offs=7) -- 1819(line=51, offs=25)
*/
ATSINSlab(__atstmplab2):
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1726(line=48, offs=12) -- 1728(line=48, offs=14)
*/
#if(0)
ATSifthen(ATSCKptrisnull(arg0)) { ATSINSdeadcode_fail() ; } ;
#endif
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1819(line=51, offs=25) -- 1819(line=51, offs=25)
*/
ATSINSlab(__atstmplab3):
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1811(line=51, offs=17) -- 1812(line=51, offs=18)
*/
ATSINSmove(tmp8, ATSSELcon(arg0, postiats_tysum_1, atslab__0)) ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1814(line=51, offs=20) -- 1818(line=51, offs=24)
*/
ATSINSmove(tmp9, ATSSELcon(arg0, postiats_tysum_1, atslab__1)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1826(line=51, offs=32) -- 1831(line=51, offs=37)
*/
ATSINSmove(tmp10, atspre_eq_string_string(tmp8, env0)) ;

/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1823(line=51, offs=29) -- 1856(line=51, offs=62)
*/
ATSif(
tmp10
) ATSthen() {
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1837(line=51, offs=43) -- 1841(line=51, offs=47)
*/
ATSINSmove(tmpret7, ATSPMVbool_true()) ;
} ATSelse() {
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1847(line=51, offs=53) -- 1855(line=51, offs=61)
*/
ATStailcal_beg()
ATSINSmove_tlcal(apy0, tmp9) ;
ATSINSargmove_tlcal(arg0, apy0) ;
ATSINSfgoto(__patsflab_mem_3) ;
ATStailcal_end()

} /* ATSendif */
ATSbranch_end()

/*
** ibranchlst-end
*/
ATScaseof_end()

ATSfunbody_end()
ATSreturn(tmpret7) ;
} /* end of [mem_3] */

/*
/home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1996(line=58, offs=27) -- 2048(line=59, offs=47)
*/
/*
local: 
global: validate_spdx_id$4$0(level=0)
local: 
global: 
*/
ATSextern()
atstype_boxed
_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_types_056_sats__validate_spdx_id(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret13, atstype_boxed) ;
ATStmpdec(tmp14, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 1980(line=58, offs=11) -- 2048(line=59, offs=47)
*/
ATSINSflab(__patsflab_validate_spdx_id):
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 2007(line=59, offs=6) -- 2022(line=59, offs=21)
*/
ATSINSmove(tmp14, _057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_types_056_sats__is_valid_spdx(arg0)) ;

/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 2004(line=59, offs=3) -- 2048(line=59, offs=47)
*/
ATSif(
tmp14
) ATSthen() {
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 2029(line=59, offs=28) -- 2035(line=59, offs=34)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(tmpret13, postiats_tysum_2) ;
#if(0)
ATSINSstore_con1_tag(tmpret13, 0) ;
#endif
ATSINSstore_con1_ofs(tmpret13, postiats_tysum_2, atslab__0, arg0) ;
ATSINSmove_con1_end()
} ATSelse() {
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 2042(line=59, offs=41) -- 2048(line=59, offs=47)
*/

ATSINSmove_nil(tmpret13) ;

} /* ATSendif */
ATSfunbody_end()
ATSreturn(tmpret13) ;
} /* end of [_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_types_056_sats__validate_spdx_id] */

/*
/home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 2077(line=61, offs=28) -- 2134(line=62, offs=52)
*/
/*
local: 
global: validate_nonempty$5$0(level=0)
local: 
global: 
*/
ATSextern()
atstype_boxed
_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_types_056_sats__validate_nonempty(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret15, atstype_boxed) ;
ATStmpdec(tmp16, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 2060(line=61, offs=11) -- 2134(line=62, offs=52)
*/
ATSINSflab(__patsflab_validate_nonempty):
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 2088(line=62, offs=6) -- 2108(line=62, offs=26)
*/
ATSINSmove(tmp16, _057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_utils_057_string_utils_056_sats__string_is_nonempty(arg0)) ;

/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 2085(line=62, offs=3) -- 2134(line=62, offs=52)
*/
ATSif(
tmp16
) ATSthen() {
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 2115(line=62, offs=33) -- 2121(line=62, offs=39)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(tmpret15, postiats_tysum_2) ;
#if(0)
ATSINSstore_con1_tag(tmpret15, 0) ;
#endif
ATSINSstore_con1_ofs(tmpret15, postiats_tysum_2, atslab__0, arg0) ;
ATSINSmove_con1_end()
} ATSelse() {
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 2128(line=62, offs=46) -- 2134(line=62, offs=52)
*/

ATSINSmove_nil(tmpret15) ;

} /* ATSendif */
ATSfunbody_end()
ATSreturn(tmpret15) ;
} /* end of [_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_types_056_sats__validate_nonempty] */

/*
/home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 2390(line=67, offs=31) -- 2497(line=71, offs=4)
*/
/*
local: system_owned_0$0(level=0)
global: system_owned_0$0(level=0), validate_path_exists$6$0(level=0)
local: 
global: 
*/
ATSextern()
atstype_boxed
_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_types_056_sats__validate_path_exists(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret17, atstype_boxed) ;
ATStmpdec(tmp18, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp19, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp47, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 2370(line=67, offs=11) -- 2497(line=71, offs=4)
*/
ATSINSflab(__patsflab_validate_path_exists):
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 2396(line=67, offs=37) -- 2497(line=71, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 2424(line=68, offs=25) -- 2452(line=68, offs=53)
*/
ATSINSmove(tmp19, ATSLIB_056_prelude__string0_append__7__1(ATSPMVstring("test -e "), arg0)) ;

/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 2411(line=68, offs=12) -- 2453(line=68, offs=54)
*/
ATSINSmove(tmp18, system_owned_0(tmp19)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 2462(line=70, offs=6) -- 2468(line=70, offs=12)
*/
ATSINSmove(tmp47, ATSLIB_056_prelude__eq_g0int_int__16__1(tmp18, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 2459(line=70, offs=3) -- 2493(line=70, offs=37)
*/
ATSif(
tmp47
) ATSthen() {
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 2474(line=70, offs=18) -- 2480(line=70, offs=24)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(tmpret17, postiats_tysum_2) ;
#if(0)
ATSINSstore_con1_tag(tmpret17, 0) ;
#endif
ATSINSstore_con1_ofs(tmpret17, postiats_tysum_2, atslab__0, arg0) ;
ATSINSmove_con1_end()
} ATSelse() {
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 2487(line=70, offs=31) -- 2493(line=70, offs=37)
*/

ATSINSmove_nil(tmpret17) ;

} /* ATSendif */
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 2396(line=67, offs=37) -- 2497(line=71, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret17) ;
} /* end of [_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_types_056_sats__validate_path_exists] */

#if(0)
/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats: 14884(line=842, offs=3) -- 15043(line=851, offs=4)
*/
/*
local: 
global: string0_append$7$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = 
tmparg = 
tmpsub = None()
*/
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__string0_append__7(atstkind_type(atstype_ptrk) arg0, atstkind_type(atstype_ptrk) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret20, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp21, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 14867(line=841, offs=1) -- 15043(line=851, offs=4)
*/
ATSINSflab(__patsflab_string0_append):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 14895(line=842, offs=14) -- 15043(line=851, offs=4)
*/
/*
letpush(beg)
*/
/* (*nothing*) */
/* (*nothing*) */
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 14952(line=846, offs=11) -- 14974(line=846, offs=33)
*/
ATSINSmove(tmp21, PMVtmpltcst(string1_append<>)(ATSPMVcastfn(g1ofg0_string, atstkind_type(atstype_ptrk), arg0), ATSPMVcastfn(g1ofg0_string, atstkind_type(atstype_ptrk), arg1))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15019(line=850, offs=3) -- 15038(line=850, offs=22)
*/
ATSINSmove(tmpret20, ATSPMVcastfn(strnptr2strptr, atstkind_type(atstype_ptrk), tmp21)) ;
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 14895(line=842, offs=14) -- 15043(line=851, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret20) ;
} /* end of [ATSLIB_056_prelude__string0_append__7] */
#endif // end of [TEMPLATE]

/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats: 14884(line=842, offs=3) -- 15043(line=851, offs=4)
*/
/*
local: 
global: string0_append$7$1(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = 
tmparg = 
tmpsub = Some()
*/
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__string0_append__7__1(atstkind_type(atstype_ptrk) arg0, atstkind_type(atstype_ptrk) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret20__1, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp21__1, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 14867(line=841, offs=1) -- 15043(line=851, offs=4)
*/
ATSINSflab(__patsflab_string0_append):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 14895(line=842, offs=14) -- 15043(line=851, offs=4)
*/
/*
letpush(beg)
*/
/* (*nothing*) */
/* (*nothing*) */
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 14952(line=846, offs=11) -- 14974(line=846, offs=33)
*/
ATSINSmove(tmp21__1, ATSLIB_056_prelude__string1_append__9__1(ATSPMVcastfn(g1ofg0_string, atstkind_type(atstype_ptrk), arg0), ATSPMVcastfn(g1ofg0_string, atstkind_type(atstype_ptrk), arg1))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15019(line=850, offs=3) -- 15038(line=850, offs=22)
*/
ATSINSmove(tmpret20__1, ATSPMVcastfn(strnptr2strptr, atstkind_type(atstype_ptrk), tmp21__1)) ;
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 14895(line=842, offs=14) -- 15043(line=851, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret20__1) ;
} /* end of [ATSLIB_056_prelude__string0_append__7__1] */

#if(0)
/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats: 15116(line=856, offs=10) -- 15385(line=868, offs=4)
*/
/*
local: 
global: string1_append$9$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = 
tmparg = 
tmpsub = None()
*/
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__string1_append__9(atstkind_type(atstype_ptrk) arg0, atstkind_type(atstype_ptrk) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret24, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp25, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp26, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp27, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp28, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp29, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp30, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp31, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp32, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp33, atstkind_t0ype(atstype_size)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15092(line=855, offs=1) -- 15385(line=868, offs=4)
*/
ATSINSflab(__patsflab_string1_append):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15127(line=856, offs=21) -- 15385(line=868, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15143(line=858, offs=10) -- 15152(line=858, offs=19)
*/
ATSINSmove(tmp25, PMVtmpltcst(string1_length<>)(arg0)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15163(line=858, offs=30) -- 15172(line=858, offs=39)
*/
ATSINSmove(tmp26, PMVtmpltcst(string1_length<>)(arg1)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15187(line=860, offs=11) -- 15194(line=860, offs=18)
*/
ATSINSmove(tmp27, PMVtmpltcst(g1uint_add<S2Eextkind(atstype_size)>)(tmp25, tmp26)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15225(line=861, offs=31) -- 15233(line=861, offs=39)
*/
ATSINSmove(tmp29, PMVtmpltcst(g1uint_succ<S2Eextkind(atstype_size)>)(tmp27)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15215(line=861, offs=21) -- 15235(line=861, offs=41)
*/
ATSINSmove(tmp28, atspre_malloc_gc(tmp29)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15248(line=863, offs=10) -- 15277(line=863, offs=39)
*/
ATSINSmove(tmp30, atspre_string_memcpy(tmp28, ATSPMVcastfn(string2ptr, atstkind_type(atstype_ptrk), arg0), tmp25)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15294(line=864, offs=17) -- 15300(line=864, offs=23)
*/
ATSINSmove(tmp32, atspre_add_ptr1_bsz(tmp28, tmp25)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15318(line=864, offs=41) -- 15325(line=864, offs=48)
*/
ATSINSmove(tmp33, PMVtmpltcst(g1uint_succ<S2Eextkind(atstype_size)>)(tmp26)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15287(line=864, offs=10) -- 15327(line=864, offs=50)
*/
ATSINSmove(tmp31, atspre_string_memcpy(tmp32, ATSPMVcastfn(string2ptr, atstkind_type(atstype_ptrk), arg1), tmp33)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15336(line=867, offs=3) -- 15381(line=867, offs=48)
*/
ATSINSmove(tmpret24, ATSPMVcastfn(castvwtp0, atstkind_type(atstype_ptrk), tmp28)) ;
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15127(line=856, offs=21) -- 15385(line=868, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret24) ;
} /* end of [ATSLIB_056_prelude__string1_append__9] */
#endif // end of [TEMPLATE]

/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats: 15116(line=856, offs=10) -- 15385(line=868, offs=4)
*/
/*
local: 
global: string1_append$9$1(level=2)
local: 
global: 
*/
ATSstatic()
/*
imparg = 
tmparg = 
tmpsub = Some()
*/
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__string1_append__9__1(atstkind_type(atstype_ptrk) arg0, atstkind_type(atstype_ptrk) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret24__1, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp25__1, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp26__1, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp27__1, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp28__1, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp29__1, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp30__1, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp31__1, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp32__1, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp33__1, atstkind_t0ype(atstype_size)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15092(line=855, offs=1) -- 15385(line=868, offs=4)
*/
ATSINSflab(__patsflab_string1_append):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15127(line=856, offs=21) -- 15385(line=868, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15143(line=858, offs=10) -- 15152(line=858, offs=19)
*/
ATSINSmove(tmp25__1, ATSLIB_056_prelude__string1_length__11__1(arg0)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15163(line=858, offs=30) -- 15172(line=858, offs=39)
*/
ATSINSmove(tmp26__1, ATSLIB_056_prelude__string1_length__11__2(arg1)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15187(line=860, offs=11) -- 15194(line=860, offs=18)
*/
ATSINSmove(tmp27__1, atspre_g1uint_add_size(tmp25__1, tmp26__1)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15225(line=861, offs=31) -- 15233(line=861, offs=39)
*/
ATSINSmove(tmp29__1, atspre_g1uint_succ_size(tmp27__1)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15215(line=861, offs=21) -- 15235(line=861, offs=41)
*/
ATSINSmove(tmp28__1, atspre_malloc_gc(tmp29__1)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15248(line=863, offs=10) -- 15277(line=863, offs=39)
*/
ATSINSmove(tmp30__1, atspre_string_memcpy(tmp28__1, ATSPMVcastfn(string2ptr, atstkind_type(atstype_ptrk), arg0), tmp25__1)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15294(line=864, offs=17) -- 15300(line=864, offs=23)
*/
ATSINSmove(tmp32__1, atspre_add_ptr1_bsz(tmp28__1, tmp25__1)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15318(line=864, offs=41) -- 15325(line=864, offs=48)
*/
ATSINSmove(tmp33__1, atspre_g1uint_succ_size(tmp26__1)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15287(line=864, offs=10) -- 15327(line=864, offs=50)
*/
ATSINSmove(tmp31__1, atspre_string_memcpy(tmp32__1, ATSPMVcastfn(string2ptr, atstkind_type(atstype_ptrk), arg1), tmp33__1)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15336(line=867, offs=3) -- 15381(line=867, offs=48)
*/
ATSINSmove(tmpret24__1, ATSPMVcastfn(castvwtp0, atstkind_type(atstype_ptrk), tmp28__1)) ;
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15127(line=856, offs=21) -- 15385(line=868, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret24__1) ;
} /* end of [ATSLIB_056_prelude__string1_append__9__1] */

#if(0)
/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats: 11344(line=638, offs=6) -- 11453(line=644, offs=2)
*/
/*
local: 
global: string1_length$11$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = 
tmparg = 
tmpsub = None()
*/
atstkind_t0ype(atstype_size)
ATSLIB_056_prelude__string1_length__11(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret44, atstkind_t0ype(atstype_size)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 11324(line=637, offs=1) -- 11453(line=644, offs=2)
*/
ATSINSflab(__patsflab_string1_length):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 11354(line=639, offs=3) -- 11453(line=644, offs=2)
*/
/*
letpush(beg)
*/
/*
letpush(end)
*/

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 11354(line=639, offs=3) -- 11368(line=639, offs=17)
*/
ATSINSmove(tmpret44, atspre_strlen(arg0)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 11354(line=639, offs=3) -- 11453(line=644, offs=2)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret44) ;
} /* end of [ATSLIB_056_prelude__string1_length__11] */
#endif // end of [TEMPLATE]

/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats: 11344(line=638, offs=6) -- 11453(line=644, offs=2)
*/
/*
local: 
global: string1_length$11$1(level=3)
local: 
global: 
*/
ATSstatic()
/*
imparg = 
tmparg = 
tmpsub = Some()
*/
atstkind_t0ype(atstype_size)
ATSLIB_056_prelude__string1_length__11__1(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret44__1, atstkind_t0ype(atstype_size)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 11324(line=637, offs=1) -- 11453(line=644, offs=2)
*/
ATSINSflab(__patsflab_string1_length):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 11354(line=639, offs=3) -- 11453(line=644, offs=2)
*/
/*
letpush(beg)
*/
/*
letpush(end)
*/

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 11354(line=639, offs=3) -- 11368(line=639, offs=17)
*/
ATSINSmove(tmpret44__1, atspre_strlen(arg0)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 11354(line=639, offs=3) -- 11453(line=644, offs=2)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret44__1) ;
} /* end of [ATSLIB_056_prelude__string1_length__11__1] */

/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats: 11344(line=638, offs=6) -- 11453(line=644, offs=2)
*/
/*
local: 
global: string1_length$11$2(level=3)
local: 
global: 
*/
ATSstatic()
/*
imparg = 
tmparg = 
tmpsub = Some()
*/
atstkind_t0ype(atstype_size)
ATSLIB_056_prelude__string1_length__11__2(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret44__2, atstkind_t0ype(atstype_size)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 11324(line=637, offs=1) -- 11453(line=644, offs=2)
*/
ATSINSflab(__patsflab_string1_length):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 11354(line=639, offs=3) -- 11453(line=644, offs=2)
*/
/*
letpush(beg)
*/
/*
letpush(end)
*/

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 11354(line=639, offs=3) -- 11368(line=639, offs=17)
*/
ATSINSmove(tmpret44__2, atspre_strlen(arg0)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 11354(line=639, offs=3) -- 11453(line=644, offs=2)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret44__2) ;
} /* end of [ATSLIB_056_prelude__string1_length__11__2] */

#if(0)
/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats: 12259(line=635, offs=3) -- 12298(line=635, offs=42)
*/
/*
local: 
global: eq_g0int_int$16$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = tk(4634)
tmparg = S2Evar(tk(4634))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__16(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret48, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp49, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12244(line=634, offs=1) -- 12298(line=635, offs=42)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12285(line=635, offs=29) -- 12296(line=635, offs=40)
*/
ATSINSmove(tmp49, PMVtmpltcst(g0int2int<S2Eextkind(atstype_int), S2Evar(tk(4634))>)(arg1)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12268(line=635, offs=12) -- 12298(line=635, offs=42)
*/
ATSINSmove(tmpret48, PMVtmpltcst(g0int_eq<S2Evar(tk(4634))>)(arg0, tmp49)) ;

ATSfunbody_end()
ATSreturn(tmpret48) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__16] */
#endif // end of [TEMPLATE]

/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats: 12259(line=635, offs=3) -- 12298(line=635, offs=42)
*/
/*
local: 
global: eq_g0int_int$16$1(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4634)
tmparg = S2Evar(tk(4634))
tmpsub = Some(tk(4634) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__16__1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret48__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp49__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12244(line=634, offs=1) -- 12298(line=635, offs=42)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12285(line=635, offs=29) -- 12296(line=635, offs=40)
*/
ATSINSmove(tmp49__1, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12268(line=635, offs=12) -- 12298(line=635, offs=42)
*/
ATSINSmove(tmpret48__1, atspre_g0int_eq_int(arg0, tmp49__1)) ;

ATSfunbody_end()
ATSreturn(tmpret48__1) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__16__1] */

/*
/home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 2526(line=73, offs=28) -- 2679(line=78, offs=4)
*/
/*
local: system_owned_0$0(level=0)
global: system_owned_0$0(level=0), validate_git_repo$20$0(level=0)
local: 
global: 
*/
ATSextern()
atstype_boxed
_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_types_056_sats__validate_git_repo(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret52, atstype_boxed) ;
ATStmpdec(tmp53, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp54, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp69, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp70, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 2509(line=73, offs=11) -- 2679(line=78, offs=4)
*/
ATSINSflab(__patsflab_validate_git_repo):
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 2532(line=73, offs=34) -- 2679(line=78, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 2579(line=74, offs=44) -- 2604(line=74, offs=69)
*/
ATSINSmove(tmp54, ATSLIB_056_prelude__string0_append__7__2(arg0, ATSPMVstring("/.git"))) ;

/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 2548(line=74, offs=13) -- 2605(line=74, offs=70)
*/
ATSINSmove(tmp53, _057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_utils_057_string_utils_056_sats__strptr_prepend_str(ATSPMVstring("test -d "), tmp54)) ;

/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 2618(line=75, offs=13) -- 2634(line=75, offs=29)
*/
ATSINSmove(tmp69, system_owned_0(tmp53)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 2644(line=77, offs=6) -- 2650(line=77, offs=12)
*/
ATSINSmove(tmp70, ATSLIB_056_prelude__eq_g0int_int__16__2(tmp69, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 2641(line=77, offs=3) -- 2675(line=77, offs=37)
*/
ATSif(
tmp70
) ATSthen() {
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 2656(line=77, offs=18) -- 2662(line=77, offs=24)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(tmpret52, postiats_tysum_2) ;
#if(0)
ATSINSstore_con1_tag(tmpret52, 0) ;
#endif
ATSINSstore_con1_ofs(tmpret52, postiats_tysum_2, atslab__0, arg0) ;
ATSINSmove_con1_end()
} ATSelse() {
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 2669(line=77, offs=31) -- 2675(line=77, offs=37)
*/

ATSINSmove_nil(tmpret52) ;

} /* ATSendif */
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 2532(line=73, offs=34) -- 2679(line=78, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret52) ;
} /* end of [_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_types_056_sats__validate_git_repo] */

/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats: 14884(line=842, offs=3) -- 15043(line=851, offs=4)
*/
/*
local: 
global: string0_append$7$2(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = 
tmparg = 
tmpsub = Some()
*/
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__string0_append__7__2(atstkind_type(atstype_ptrk) arg0, atstkind_type(atstype_ptrk) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret20__2, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp21__2, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 14867(line=841, offs=1) -- 15043(line=851, offs=4)
*/
ATSINSflab(__patsflab_string0_append):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 14895(line=842, offs=14) -- 15043(line=851, offs=4)
*/
/*
letpush(beg)
*/
/* (*nothing*) */
/* (*nothing*) */
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 14952(line=846, offs=11) -- 14974(line=846, offs=33)
*/
ATSINSmove(tmp21__2, ATSLIB_056_prelude__string1_append__9__2(ATSPMVcastfn(g1ofg0_string, atstkind_type(atstype_ptrk), arg0), ATSPMVcastfn(g1ofg0_string, atstkind_type(atstype_ptrk), arg1))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15019(line=850, offs=3) -- 15038(line=850, offs=22)
*/
ATSINSmove(tmpret20__2, ATSPMVcastfn(strnptr2strptr, atstkind_type(atstype_ptrk), tmp21__2)) ;
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 14895(line=842, offs=14) -- 15043(line=851, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret20__2) ;
} /* end of [ATSLIB_056_prelude__string0_append__7__2] */

/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats: 15116(line=856, offs=10) -- 15385(line=868, offs=4)
*/
/*
local: 
global: string1_append$9$2(level=2)
local: 
global: 
*/
ATSstatic()
/*
imparg = 
tmparg = 
tmpsub = Some()
*/
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__string1_append__9__2(atstkind_type(atstype_ptrk) arg0, atstkind_type(atstype_ptrk) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret24__2, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp25__2, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp26__2, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp27__2, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp28__2, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp29__2, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp30__2, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp31__2, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp32__2, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp33__2, atstkind_t0ype(atstype_size)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15092(line=855, offs=1) -- 15385(line=868, offs=4)
*/
ATSINSflab(__patsflab_string1_append):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15127(line=856, offs=21) -- 15385(line=868, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15143(line=858, offs=10) -- 15152(line=858, offs=19)
*/
ATSINSmove(tmp25__2, ATSLIB_056_prelude__string1_length__11__3(arg0)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15163(line=858, offs=30) -- 15172(line=858, offs=39)
*/
ATSINSmove(tmp26__2, ATSLIB_056_prelude__string1_length__11__4(arg1)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15187(line=860, offs=11) -- 15194(line=860, offs=18)
*/
ATSINSmove(tmp27__2, atspre_g1uint_add_size(tmp25__2, tmp26__2)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15225(line=861, offs=31) -- 15233(line=861, offs=39)
*/
ATSINSmove(tmp29__2, atspre_g1uint_succ_size(tmp27__2)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15215(line=861, offs=21) -- 15235(line=861, offs=41)
*/
ATSINSmove(tmp28__2, atspre_malloc_gc(tmp29__2)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15248(line=863, offs=10) -- 15277(line=863, offs=39)
*/
ATSINSmove(tmp30__2, atspre_string_memcpy(tmp28__2, ATSPMVcastfn(string2ptr, atstkind_type(atstype_ptrk), arg0), tmp25__2)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15294(line=864, offs=17) -- 15300(line=864, offs=23)
*/
ATSINSmove(tmp32__2, atspre_add_ptr1_bsz(tmp28__2, tmp25__2)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15318(line=864, offs=41) -- 15325(line=864, offs=48)
*/
ATSINSmove(tmp33__2, atspre_g1uint_succ_size(tmp26__2)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15287(line=864, offs=10) -- 15327(line=864, offs=50)
*/
ATSINSmove(tmp31__2, atspre_string_memcpy(tmp32__2, ATSPMVcastfn(string2ptr, atstkind_type(atstype_ptrk), arg1), tmp33__2)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15336(line=867, offs=3) -- 15381(line=867, offs=48)
*/
ATSINSmove(tmpret24__2, ATSPMVcastfn(castvwtp0, atstkind_type(atstype_ptrk), tmp28__2)) ;
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 15127(line=856, offs=21) -- 15385(line=868, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret24__2) ;
} /* end of [ATSLIB_056_prelude__string1_append__9__2] */

/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats: 11344(line=638, offs=6) -- 11453(line=644, offs=2)
*/
/*
local: 
global: string1_length$11$3(level=3)
local: 
global: 
*/
ATSstatic()
/*
imparg = 
tmparg = 
tmpsub = Some()
*/
atstkind_t0ype(atstype_size)
ATSLIB_056_prelude__string1_length__11__3(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret44__3, atstkind_t0ype(atstype_size)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 11324(line=637, offs=1) -- 11453(line=644, offs=2)
*/
ATSINSflab(__patsflab_string1_length):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 11354(line=639, offs=3) -- 11453(line=644, offs=2)
*/
/*
letpush(beg)
*/
/*
letpush(end)
*/

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 11354(line=639, offs=3) -- 11368(line=639, offs=17)
*/
ATSINSmove(tmpret44__3, atspre_strlen(arg0)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 11354(line=639, offs=3) -- 11453(line=644, offs=2)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret44__3) ;
} /* end of [ATSLIB_056_prelude__string1_length__11__3] */

/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats: 11344(line=638, offs=6) -- 11453(line=644, offs=2)
*/
/*
local: 
global: string1_length$11$4(level=3)
local: 
global: 
*/
ATSstatic()
/*
imparg = 
tmparg = 
tmpsub = Some()
*/
atstkind_t0ype(atstype_size)
ATSLIB_056_prelude__string1_length__11__4(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret44__4, atstkind_t0ype(atstype_size)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 11324(line=637, offs=1) -- 11453(line=644, offs=2)
*/
ATSINSflab(__patsflab_string1_length):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 11354(line=639, offs=3) -- 11453(line=644, offs=2)
*/
/*
letpush(beg)
*/
/*
letpush(end)
*/

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 11354(line=639, offs=3) -- 11368(line=639, offs=17)
*/
ATSINSmove(tmpret44__4, atspre_strlen(arg0)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 11354(line=639, offs=3) -- 11453(line=644, offs=2)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret44__4) ;
} /* end of [ATSLIB_056_prelude__string1_length__11__4] */

/*
/usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats: 12259(line=635, offs=3) -- 12298(line=635, offs=42)
*/
/*
local: 
global: eq_g0int_int$16$2(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4634)
tmparg = S2Evar(tk(4634))
tmpsub = Some(tk(4634) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__16__2(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret48__2, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp49__2, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12244(line=634, offs=1) -- 12298(line=635, offs=42)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12285(line=635, offs=29) -- 12296(line=635, offs=40)
*/
ATSINSmove(tmp49__2, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /usr/lib/ats2-postiats-0.4.2/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12268(line=635, offs=12) -- 12298(line=635, offs=42)
*/
ATSINSmove(tmpret48__2, atspre_g0int_eq_int(arg0, tmp49__2)) ;

ATSfunbody_end()
ATSreturn(tmpret48__2) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__16__2] */

/*
/home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 2751(line=82, offs=22) -- 2762(line=82, offs=33)
*/
/*
local: 
global: spdx_unwrap$26$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_type(atstype_ptrk)
_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_types_056_sats__spdx_unwrap(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret73, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 2740(line=82, offs=11) -- 2762(line=82, offs=33)
*/
ATSINSflab(__patsflab_spdx_unwrap):
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 2761(line=82, offs=32) -- 2762(line=82, offs=33)
*/
ATSINSmove(tmpret73, arg0) ;
ATSfunbody_end()
ATSreturn(tmpret73) ;
} /* end of [_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_types_056_sats__spdx_unwrap] */

/*
/home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 2788(line=83, offs=26) -- 2795(line=83, offs=33)
*/
/*
local: 
global: nonempty_unwrap$27$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_type(atstype_ptrk)
_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_types_056_sats__nonempty_unwrap(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret74, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 2773(line=83, offs=11) -- 2795(line=83, offs=33)
*/
ATSINSflab(__patsflab_nonempty_unwrap):
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 2794(line=83, offs=32) -- 2795(line=83, offs=33)
*/
ATSINSmove(tmpret74, arg0) ;
ATSfunbody_end()
ATSreturn(tmpret74) ;
} /* end of [_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_types_056_sats__nonempty_unwrap] */

/*
/home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 2817(line=84, offs=22) -- 2828(line=84, offs=33)
*/
/*
local: 
global: path_unwrap$28$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_type(atstype_ptrk)
_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_types_056_sats__path_unwrap(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret75, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 2806(line=84, offs=11) -- 2828(line=84, offs=33)
*/
ATSINSflab(__patsflab_path_unwrap):
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 2827(line=84, offs=32) -- 2828(line=84, offs=33)
*/
ATSINSmove(tmpret75, arg0) ;
ATSfunbody_end()
ATSreturn(tmpret75) ;
} /* end of [_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_types_056_sats__path_unwrap] */

/*
/home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 2853(line=85, offs=25) -- 2861(line=85, offs=33)
*/
/*
local: 
global: gitrepo_unwrap$29$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_type(atstype_ptrk)
_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_types_056_sats__gitrepo_unwrap(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret76, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 2839(line=85, offs=11) -- 2861(line=85, offs=33)
*/
ATSINSflab(__patsflab_gitrepo_unwrap):
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 2860(line=85, offs=32) -- 2861(line=85, offs=33)
*/
ATSINSmove(tmpret76, arg0) ;
ATSfunbody_end()
ATSreturn(tmpret76) ;
} /* end of [_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_types_056_sats__gitrepo_unwrap] */

/*
/home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 2931(line=89, offs=25) -- 3015(line=93, offs=22)
*/
/*
local: 
global: result_message$30$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_type(atstype_ptrk)
_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_types_056_sats__result_message(atstype_boxed arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret77, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp78, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp79, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp80, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 2917(line=89, offs=11) -- 3015(line=93, offs=22)
*/
ATSINSflab(__patsflab_result_message):
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 2939(line=90, offs=3) -- 3015(line=93, offs=22)
*/
ATScaseof_beg()
/*
** ibranchlst-beg
*/
ATSbranch_beg()
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 2954(line=91, offs=5) -- 2965(line=91, offs=16)
*/
ATSINSlab(__atstmplab4):
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 2932(line=89, offs=26) -- 2933(line=89, offs=27)
*/
ATSifnthen(ATSCKpat_con1(arg0, 0)) { ATSINSgoto(__atstmplab6) ; } ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 2965(line=91, offs=16) -- 2965(line=91, offs=16)
*/
ATSINSlab(__atstmplab5):
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 2964(line=91, offs=15) -- 2965(line=91, offs=16)
*/
ATSINSmove(tmp78, ATSSELcon(arg0, postiats_tysum_3, atslab__0)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 2970(line=91, offs=21) -- 2971(line=91, offs=22)
*/
ATSINSmove(tmpret77, tmp78) ;
ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 2976(line=92, offs=5) -- 2987(line=92, offs=16)
*/
ATSINSlab(__atstmplab6):
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 2932(line=89, offs=26) -- 2933(line=89, offs=27)
*/
ATSifnthen(ATSCKpat_con1(arg0, 1)) { ATSINSgoto(__atstmplab8) ; } ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 2987(line=92, offs=16) -- 2987(line=92, offs=16)
*/
ATSINSlab(__atstmplab7):
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 2986(line=92, offs=15) -- 2987(line=92, offs=16)
*/
ATSINSmove(tmp79, ATSSELcon(arg0, postiats_tysum_3, atslab__0)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 2992(line=92, offs=21) -- 2993(line=92, offs=22)
*/
ATSINSmove(tmpret77, tmp79) ;
ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 2998(line=93, offs=5) -- 3009(line=93, offs=16)
*/
ATSINSlab(__atstmplab8):
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 2932(line=89, offs=26) -- 2933(line=89, offs=27)
*/
#if(0)
ATSifnthen(ATSCKpat_con1(arg0, 2)) { ATSINSdeadcode_fail() ; } ;
#endif
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 3009(line=93, offs=16) -- 3009(line=93, offs=16)
*/
ATSINSlab(__atstmplab9):
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 3008(line=93, offs=15) -- 3009(line=93, offs=16)
*/
ATSINSmove(tmp80, ATSSELcon(arg0, postiats_tysum_3, atslab__0)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 3014(line=93, offs=21) -- 3015(line=93, offs=22)
*/
ATSINSmove(tmpret77, tmp80) ;
ATSbranch_end()

/*
** ibranchlst-end
*/
ATScaseof_end()

ATSfunbody_end()
ATSreturn(tmpret77) ;
} /* end of [_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_types_056_sats__result_message] */

/*
/home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 3039(line=95, offs=23) -- 3096(line=98, offs=15)
*/
/*
local: 
global: result_is_ok$31$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_t0ype(atstype_bool)
_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_types_056_sats__result_is_ok(atstype_boxed arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret81, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 3027(line=95, offs=11) -- 3096(line=98, offs=15)
*/
ATSINSflab(__patsflab_result_is_ok):
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 3047(line=96, offs=3) -- 3096(line=98, offs=15)
*/
ATScaseof_beg()
/*
** ibranchlst-beg
*/
ATSbranch_beg()
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 3062(line=97, offs=5) -- 3073(line=97, offs=16)
*/
ATSINSlab(__atstmplab10):
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 3040(line=95, offs=24) -- 3041(line=95, offs=25)
*/
ATSifnthen(ATSCKpat_con1(arg0, 0)) { ATSINSgoto(__atstmplab12) ; } ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 3073(line=97, offs=16) -- 3073(line=97, offs=16)
*/
ATSINSlab(__atstmplab11):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 3077(line=97, offs=20) -- 3081(line=97, offs=24)
*/
ATSINSmove(tmpret81, ATSPMVbool_true()) ;
ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 3087(line=98, offs=6) -- 3087(line=98, offs=6)
*/
ATSINSlab(__atstmplab12):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 3091(line=98, offs=10) -- 3096(line=98, offs=15)
*/
ATSINSmove(tmpret81, ATSPMVbool_false()) ;
ATSbranch_end()

/*
** ibranchlst-end
*/
ATScaseof_end()

ATSfunbody_end()
ATSreturn(tmpret81) ;
} /* end of [_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_types_056_sats__result_is_ok] */

/*
/home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 3119(line=100, offs=22) -- 3210(line=105, offs=2)
*/
/*
local: 
global: empty_batch$32$0(level=0)
local: 
global: 
*/
ATSextern()
postiats_tyrec_0
_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_types_056_sats__empty_batch(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret82, postiats_tyrec_0) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 3108(line=100, offs=11) -- 3210(line=105, offs=2)
*/
ATSINSflab(__patsflab_empty_batch):
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 3127(line=100, offs=30) -- 3210(line=105, offs=2)
*/
ATSINSmove_fltrec_beg()
ATSINSstore_fltrec_ofs(tmpret82, postiats_tyrec_0, atslab__success_count, ATSPMVi0nt(0)) ;
ATSINSstore_fltrec_ofs(tmpret82, postiats_tyrec_0, atslab__failure_count, ATSPMVi0nt(0)) ;
ATSINSstore_fltrec_ofs(tmpret82, postiats_tyrec_0, atslab__skipped_count, ATSPMVi0nt(0)) ;
ATSINSstore_fltrec_ofs(tmpret82, postiats_tyrec_0, atslab__message, arg0) ;
ATSINSmove_fltrec_end()
ATSfunbody_end()
ATSreturn(tmpret82) ;
} /* end of [_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_types_056_sats__empty_batch] */

/*
/home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 3231(line=107, offs=20) -- 3791(line=123, offs=30)
*/
/*
local: 
global: batch_add$33$0(level=0)
local: 
global: 
*/
ATSextern()
postiats_tyrec_0
_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_types_056_sats__batch_add(postiats_tyrec_0 arg0, atstype_boxed arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret83, postiats_tyrec_0) ;
ATStmpdec(tmp84, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp85, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp86, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 3222(line=107, offs=11) -- 3791(line=123, offs=30)
*/
ATSINSflab(__patsflab_batch_add):
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 3244(line=108, offs=3) -- 3791(line=123, offs=30)
*/
ATScaseof_beg()
/*
** ibranchlst-beg
*/
ATSbranch_beg()
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 3259(line=109, offs=5) -- 3270(line=109, offs=16)
*/
ATSINSlab(__atstmplab13):
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 3237(line=107, offs=26) -- 3238(line=107, offs=27)
*/
ATSifnthen(ATSCKpat_con1(arg1, 0)) { ATSINSgoto(__atstmplab15) ; } ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 3270(line=109, offs=16) -- 3270(line=109, offs=16)
*/
ATSINSlab(__atstmplab14):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 3299(line=110, offs=23) -- 3320(line=110, offs=44)
*/
ATSINSmove(tmp84, atspre_g0int_add_int(ATSSELfltrec(arg0, postiats_tyrec_0, atslab__success_count), ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 3274(line=109, offs=20) -- 3433(line=113, offs=30)
*/
ATSINSmove_fltrec_beg()
ATSINSstore_fltrec_ofs(tmpret83, postiats_tyrec_0, atslab__success_count, tmp84) ;
ATSINSstore_fltrec_ofs(tmpret83, postiats_tyrec_0, atslab__failure_count, ATSSELfltrec(arg0, postiats_tyrec_0, atslab__failure_count)) ;
ATSINSstore_fltrec_ofs(tmpret83, postiats_tyrec_0, atslab__skipped_count, ATSSELfltrec(arg0, postiats_tyrec_0, atslab__skipped_count)) ;
ATSINSstore_fltrec_ofs(tmpret83, postiats_tyrec_0, atslab__message, ATSSELfltrec(arg0, postiats_tyrec_0, atslab__message)) ;
ATSINSmove_fltrec_end()
ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 3438(line=114, offs=5) -- 3449(line=114, offs=16)
*/
ATSINSlab(__atstmplab15):
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 3237(line=107, offs=26) -- 3238(line=107, offs=27)
*/
ATSifnthen(ATSCKpat_con1(arg1, 1)) { ATSINSgoto(__atstmplab17) ; } ;
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 3449(line=114, offs=16) -- 3449(line=114, offs=16)
*/
ATSINSlab(__atstmplab16):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 3519(line=116, offs=23) -- 3540(line=116, offs=44)
*/
ATSINSmove(tmp85, atspre_g0int_add_int(ATSSELfltrec(arg0, postiats_tyrec_0, atslab__failure_count), ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 3453(line=114, offs=20) -- 3612(line=118, offs=30)
*/
ATSINSmove_fltrec_beg()
ATSINSstore_fltrec_ofs(tmpret83, postiats_tyrec_0, atslab__success_count, ATSSELfltrec(arg0, postiats_tyrec_0, atslab__success_count)) ;
ATSINSstore_fltrec_ofs(tmpret83, postiats_tyrec_0, atslab__failure_count, tmp85) ;
ATSINSstore_fltrec_ofs(tmpret83, postiats_tyrec_0, atslab__skipped_count, ATSSELfltrec(arg0, postiats_tyrec_0, atslab__skipped_count)) ;
ATSINSstore_fltrec_ofs(tmpret83, postiats_tyrec_0, atslab__message, ATSSELfltrec(arg0, postiats_tyrec_0, atslab__message)) ;
ATSINSmove_fltrec_end()
ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 3617(line=119, offs=5) -- 3628(line=119, offs=16)
*/
ATSINSlab(__atstmplab17):
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 3237(line=107, offs=26) -- 3238(line=107, offs=27)
*/
#if(0)
ATSifnthen(ATSCKpat_con1(arg1, 2)) { ATSINSdeadcode_fail() ; } ;
#endif
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 3628(line=119, offs=16) -- 3628(line=119, offs=16)
*/
ATSINSlab(__atstmplab18):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 3739(line=122, offs=23) -- 3760(line=122, offs=44)
*/
ATSINSmove(tmp86, atspre_g0int_add_int(ATSSELfltrec(arg0, postiats_tyrec_0, atslab__skipped_count), ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /home/hyperpolymath/dev/repos/.rb56-fix/scaffoldia/repo-batcher/src/ats2/operations/types.dats: 3632(line=119, offs=20) -- 3791(line=123, offs=30)
*/
ATSINSmove_fltrec_beg()
ATSINSstore_fltrec_ofs(tmpret83, postiats_tyrec_0, atslab__success_count, ATSSELfltrec(arg0, postiats_tyrec_0, atslab__success_count)) ;
ATSINSstore_fltrec_ofs(tmpret83, postiats_tyrec_0, atslab__failure_count, ATSSELfltrec(arg0, postiats_tyrec_0, atslab__failure_count)) ;
ATSINSstore_fltrec_ofs(tmpret83, postiats_tyrec_0, atslab__skipped_count, tmp86) ;
ATSINSstore_fltrec_ofs(tmpret83, postiats_tyrec_0, atslab__message, ATSSELfltrec(arg0, postiats_tyrec_0, atslab__message)) ;
ATSINSmove_fltrec_end()
ATSbranch_end()

/*
** ibranchlst-end
*/
ATScaseof_end()

ATSfunbody_end()
ATSreturn(tmpret83) ;
} /* end of [_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_types_056_sats__batch_add] */

/*
** for initialization(dynloading)
*/
ATSextern()
atsvoid_t0ype
_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_types_056_dats__dynload()
{
ATSfunbody_beg()
ATSdynload(/*void*/)
ATSdynloadflag_ext(
_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_types_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_types_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_home_057_hyperpolymath_057_dev_057_repos_057__056_rb56_055_fix_057_scaffoldia_057_repo_055_batcher_057_src_057_ats2_057_operations_057_types_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} /* end of [*_dynload] */

/* ****** ****** */

/* end-of-compilation-unit */
