#!/bin/bash
# SPDX-License-Identifier: MPL-2.0
# Batch processor for apply-ci-fixes.sh
# Processes repos in batches to avoid rate limiting

set -euo pipefail

ESTATE_ROOT="/home/hyperpolymath/developer"
BATCH_SIZE=${1:-10}  # Default batch size of 10 repos
DRY_RUN=${2:-false}

# Get list of all repos that need fixing
get_repos_needing_fixes() {
    find "$ESTATE_ROOT/hyper-repos" "$ESTATE_ROOT/meta-repos" -maxdepth 2 -name ".git" -type d | while read git_dir; do
        repo_path=$(dirname "$git_dir")
        # Check if codeql.yml exists and has tag-based refs
        codeql_file="$repo_path/.github/workflows/codeql.yml"
        if [[ -f "$codeql_file" ]] && (grep -q "codeql-action.*@v" "$codeql_file" 2>/dev/null || grep -q "actions/checkout@v" "$codeql_file" 2>/dev/null); then
            echo "$repo_path"
        fi
    done | sort
}

# Process a batch of repos
process_batch() {
    local batch_file="$1"
    local batch_name="$2"
    
    echo ""
    echo "=========================================="
    echo "Processing batch: $batch_name"
    echo "=========================================="
    
    while IFS= read -r repo_path; do
        echo "Processing: $(basename "$repo_path")"
        
        local codeql_file="$repo_path/.github/workflows/codeql.yml"
        if [[ -f "$codeql_file" ]]; then
            # Backup
            cp "$codeql_file" "$codeql_file.bak"
            
            # Update to SHA-pinned with persist-credentials: false
            ACTIONS_CHECKOUT_SHA="3d3c42e5aac5ba805825da76410c181273ba90b1"
            CODEQL_INIT_SHA="cdf488f595d80d6e07e03d4674febd5ab45fa938"
            CODEQL_ANALYZE_SHA="cdf488f595d80d6e07e03d4674febd5ab45fa938"
            
            sed -i \
                -e "s|actions/checkout@v[0-9].*\+|actions/checkout@$ACTIONS_CHECKOUT_SHA # v7.0.1\n        with:\n          persist-credentials: false|g" \
                -e "s|github/codeql-action/init@v[0-9].*\+|github/codeql-action/init@$CODEQL_INIT_SHA # v3|g" \
                -e "s|github/codeql-action/analyze@v[0-9].*\+|github/codeql-action/analyze@$CODEQL_ANALYZE_SHA # v3|g" \
                "$codeql_file"
            
            if $DRY_RUN; then
                mv "$codeql_file.bak" "$codeql_file"
                echo "  [DRY-RUN] Would fix codeql.yml"
            else
                rm "$codeql_file.bak"
                echo "  Fixed codeql.yml"
            fi
        fi
        
        # Check governance.yml
        local governance_file="$repo_path/.github/workflows/governance.yml"
        if [[ -f "$governance_file" ]]; then
            GOVERNANCE_REUSABLE_SHA="8f31a5a4ba591d544b65f91f6d78b136e07756f0"
            current_sha=$(grep "governance-reusable.yml@" "$governance_file" 2>/dev/null | grep -oE '[a-f0-9]{40}' | head -1 || true)
            if [[ -n "$current_sha" && "$current_sha" != "$GOVERNANCE_REUSABLE_SHA" ]]; then
                sed -i "s|governance-reusable.yml@[a-f0-9]\{40\}|governance-reusable.yml@$GOVERNANCE_REUSABLE_SHA|g" "$governance_file"
                echo "  Fixed governance.yml"
            fi
        fi
        
        if ! $DRY_RUN; then
            # Commit and push
            cd "$repo_path"
            if git status --porcelain | grep -q ".yml"; then
                git add -A
                git commit -m "fix(ci): apply foundation CI/CD security fixes

- Update CodeQL workflow to SHA-pinned actions with persist-credentials: false
- Update reusable workflow pins to current standards main SHAs

Generated by Mistral Vibe.
Co-Authored-By: Mistral Vibe <vibe@mistral.ai>" 2>&1 | head -5 || true
                
                # Pull and rebase if behind remote
                git pull --rebase origin HEAD 2>&1 | tail -3 || true
                
                # Try push again
                git push origin HEAD 2>&1 | tail -3 || echo "  Push may have failed - check manually"
                echo "  Committed and pushed for $(basename "$repo_path")"
            else
                echo "  No changes to commit for $(basename "$repo_path")"
            fi
        fi
        
    done < "$batch_file"
}

# Main
TOTAL_REPOS=$(get_repos_needing_fixes | wc -l)
echo "Total repos needing fixes: $TOTAL_REPOS"

if $DRY_RUN; then
    echo "Running in DRY-RUN mode - no changes will be made"
fi

# Create batches
BATCH_NUM=0
REMAINDER=0

while read -r repo_path; do
    echo "$repo_path" >> /tmp/batch_$BATCH_NUM.txt
    REMAINDER=$((REMAINDER + 1))
    
    if [[ $REMAINDER -ge $BATCH_SIZE ]]; then
        BATCH_NUM=$((BATCH_NUM + 1))
        REMAINDER=0
    fi
done < <(get_repos_needing_fixes)

# Process batches
for ((i=0; i<=BATCH_NUM; i++)); do
    BATCH_FILE="/tmp/batch_$i.txt"
    if [[ -f "$BATCH_FILE" ]]; then
        process_batch "$BATCH_FILE" "batch-$i"
        rm "$BATCH_FILE"
    fi
done

echo ""
echo "=========================================="
echo "Batch processing complete!"
echo "=========================================="
