#!/bin/bash
# SPDX-License-Identifier: MPL-2.0
# Apply CI/CD fixes to a single repository

set -euo pipefail

REPO_PATH="$1"
DRY_RUN="$2"

if [[ -z "$REPO_PATH" ]]; then
    echo "Usage: $0 <repo-path> [dry-run]"
    exit 1
fi

cd "$REPO_PATH"

echo "Processing: $(basename "$REPO_PATH")"

# Ensure we're on main branch
CURRENT_BRANCH=$(git branch --show-current 2>/dev/null || echo "detached")

if [[ "$CURRENT_BRANCH" != "main" ]]; then
    echo "  Not on main branch, checking out main..."
    git checkout main 2>/dev/null || true
fi

# Pull latest changes
if ! $DRY_RUN; then
    echo "  Pulling latest changes..."
    git pull origin main 2>&1 | tail -2 || true
fi

# Fix codeql.yml
CODEQL_FILE=".github/workflows/codeql.yml"
if [[ -f "$CODEQL_FILE" ]]; then
    if grep -q "codeql-action.*@v" "$CODEQL_FILE" 2>/dev/null || grep -q "actions/checkout@v" "$CODEQL_FILE" 2>/dev/null; then
        echo "  Fixing codeql.yml..."
        
        # Backup
        cp "$CODEQL_FILE" "$CODEQL_FILE.bak"
        
        ACTIONS_CHECKOUT_SHA="3d3c42e5aac5ba805825da76410c181273ba90b1"
        CODEQL_INIT_SHA="cdf488f595d80d6e07e03d4674febd5ab45fa938"
        CODEQL_ANALYZE_SHA="cdf488f595d80d6e07e03d4674febd5ab45fa938"
        
        # Replace checkout
        sed -i "s|uses: actions/checkout@v[0-9].*|uses: actions/checkout@$ACTIONS_CHECKOUT_SHA # v7.0.1|g" "$CODEQL_FILE"
        
        # Add persist-credentials: false to checkout step
        # This is tricky with sed, let's use a Python one-liner instead
        python3 -c "
import re, sys

with open('$CODEQL_FILE', 'r') as f:
    content = f.read()

# Add persist-credentials after checkout uses line
content = re.sub(
    r'(uses: actions/checkout@[a-f0-90-]+ \# v7\.0\.1)',
    r'\\1\n        with:\n          persist-credentials: false',
    content
)

with open('$CODEQL_FILE', 'w') as f:
    f.write(content)
" 2>/dev/null || true
        
        # Replace codeql actions
        sed -i "s|uses: github/codeql-action/init@v[0-9].*|uses: github/codeql-action/init@$CODEQL_INIT_SHA # v3|g" "$CODEQL_FILE"
        sed -i "s|uses: github/codeql-action/analyze@v[0-9].*|uses: github/codeql-action/analyze@$CODEQL_ANALYZE_SHA # v3|g" "$CODEQL_FILE"
        
        if $DRY_RUN; then
            mv "$CODEQL_FILE.bak" "$CODEQL_FILE"
            echo "  [DRY-RUN] Would fix codeql.yml"
        else
            rm "$CODEQL_FILE.bak"
            echo "  Fixed codeql.yml"
        fi
    fi
fi

# Fix governance.yml
GOVERNANCE_FILE=".github/workflows/governance.yml"
if [[ -f "$GOVERNANCE_FILE" ]]; then
    GOVERNANCE_REUSABLE_SHA="8f31a5a4ba591d544b65f91f6d78b136e07756f0"
    CURRENT_SHA=$(grep "governance-reusable.yml@" "$GOVERNANCE_FILE" 2>/dev/null | grep -oE '[a-f0-9]{40}' | head -1 || true)
    if [[ -n "$CURRENT_SHA" && "$CURRENT_SHA" != "$GOVERNANCE_REUSABLE_SHA" ]]; then
        echo "  Fixing governance.yml..."
        sed -i "s|governance-reusable.yml@[a-f0-9]\{40\}|governance-reusable.yml@$GOVERNANCE_REUSABLE_SHA|g" "$GOVERNANCE_FILE"
        echo "  Fixed governance.yml"
    fi
fi

# Fix scorecard.yml
SCORECARD_FILE=".github/workflows/scorecard.yml"
if [[ -f "$SCORECARD_FILE" ]]; then
    SCORECARD_REUSABLE_SHA="8750b94ac1bbe8c51ad13fe106669b13478f0b62"
    CURRENT_SHA=$(grep "scorecard-reusable.yml@" "$SCORECARD_FILE" 2>/dev/null | grep -oE '[a-f0-9]{40}' | head -1 || true)
    if [[ -n "$CURRENT_SHA" && "$CURRENT_SHA" != "$SCORECARD_REUSABLE_SHA" ]]; then
        echo "  Fixing scorecard.yml..."
        sed -i "s|scorecard-reusable.yml@[a-f0-9]\{40\}|scorecard-reusable.yml@$SCORECARD_REUSABLE_SHA|g" "$SCORECARD_FILE"
        echo "  Fixed scorecard.yml"
    fi
fi

# Fix hypatia-scan.yml
HYPATIA_FILE=".github/workflows/hypatia-scan.yml"
if [[ -f "$HYPATIA_FILE" ]]; then
    HYPATIA_REUSABLE_SHA="cc58c0cb23f73fc2019ce85a56a468e5248a93b3"
    CURRENT_SHA=$(grep "hypatia-scan-reusable.yml@" "$HYPATIA_FILE" 2>/dev/null | grep -oE '[a-f0-9]{40}' | head -1 || true)
    if [[ -n "$CURRENT_SHA" && "$CURRENT_SHA" != "$HYPATIA_REUSABLE_SHA" ]]; then
        echo "  Fixing hypatia-scan.yml..."
        sed -i "s|hypatia-scan-reusable.yml@[a-f0-9]\{40\}|hypatia-scan-reusable.yml@$HYPATIA_REUSABLE_SHA|g" "$HYPATIA_FILE"
        echo "  Fixed hypatia-scan.yml"
    fi
fi

# Commit and push if not dry run
if ! $DRY_RUN; then
    if git status --porcelain | grep -q ".yml"; then
        echo "  Committing changes..."
        git add -A
        git commit -m "fix(ci): apply foundation CI/CD security fixes

- Update CodeQL workflow to SHA-pinned actions with persist-credentials: false
- Update reusable workflow pins to current standards main SHAs

Generated by Mistral Vibe.
Co-Authored-By: Mistral Vibe <vibe@mistral.ai>" 2>&1 | tail -2 || true
        
        echo "  Pushing to origin..."
        git push origin main 2>&1 | tail -3 || echo "  Push failed - manual intervention needed"
        echo "  Done: $(basename "$REPO_PATH")"
    else
        echo "  No changes to commit for $(basename "$REPO_PATH")"
    fi
fi

echo ""
