#!/bin/bash
# SPDX-License-Identifier: MPL-2.0
# Audit Language CI Workflows
# Checks if repos have language-specific CI workflows that match their actual language usage

set -euo pipefail

# Language workflows to check
LANGUAGE_WORKFLOWS=(
    "rust-ci.yml:Rust:Cargo.toml|Cargo.lock|rust-toolchain.toml|\.rs$"
    "zig-ci.yml:Zig:\.zig$|zig.build|zonsh$"
    "idris2-ci.yml:Idris2:\.idr$|idris2\.ipkg$"
    "idris-ci.yml:Idris:\.idr$|\.lidr$"
    "haskell-ci.yml:Haskell:\.hs$|stack\.yaml|cabal\.project$"
    "elixir-ci.yml:Elixir:\.ex$|\.exs$|mix\.exs$"
    "gleam-ci.yml:Gleam:\.gleam$"
    "ocaml-ci.yml:OCaml:\.ml$|\.mli$|dune|opam$"
    "ada-ci.yml:Ada:\.ads$|\.adb$|\.gpr$"
    "ada-spark-ci.yml:SPARK:\.ads$|\.adb$|\.gpr$"
    "chapel-ci.yml:Chapel:\.chpl$"
    "d-ci.yml:D:\.d$|dub\.json|dub\.sdl$"
    "deno-ci.yml:Deno:deno\.json|\.ts$|\.js$"
    "docker-ci.yml:Docker:Dockerfile|docker-compose\.yml$"
    "container-ci.yml:Container:Dockerfile|docker-compose\.yml$"
)

# Find all repos
REPOS_ROOT="/home/hyperpolymath/developer/hyper-repos"
META_REPOS_ROOT="/home/hyperpolymath/developer/meta-repos"

# Output files
OUTPUT_DIR="/tmp/language_ci_audit"
mkdir -p "$OUTPUT_DIR"

REPORT_FILE="$OUTPUT_DIR/LANGUAGE_CI_AUDIT_REPORT_2026-09-11.md"
MISMATCH_FILE="$OUTPUT_DIR/LANGUAGE_CI_MISMATCHES.txt"

# Initialize report
echo "# Language CI Workflow Audit Report" > "$REPORT_FILE"
echo "**SPDX-License-Identifier: MPL-2.0**" >> "$REPORT_FILE"
echo "**Date: $(date -u +%Y-%m-%d)**" >> "$REPORT_FILE"
echo "**Generated by: Mistral Vibe**" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

TOTAL_REPOS=0
REPOS_WITH_MISMATCHES=0
MISMATCH_COUNT=0

# Function to check if a repo has files matching a pattern
has_language_files() {
    local repo_path="$1"
    local pattern="$2"
    
    # Use find with regex or glob patterns
    # For simple extensions, use -name
    # For complex patterns, use -regex
    
    # Try to find files matching the pattern
    if [[ "$pattern" == *"$"* ]]; then
        # It's a regex pattern (ends with $)
        # Convert to find -regex format
        pattern="${pattern%\$}"  # Remove trailing $
        find "$repo_path" -type f -regex ".*${pattern}" 2>/dev/null | grep -q .
    else
        # Use as glob pattern
        find "$repo_path" -type f | grep -E "${pattern}" >/dev/null 2>&1
    fi
    return $?
}

# Process each language workflow
echo "## Audit Results by Language" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

# Clear mismatch file
> "$MISMATCH_FILE"

# Find all repos with workflow directories
while IFS= read -r workflow_file; do
    repo_path=$(dirname "$(dirname "$workflow_file")")
    workflow_name=$(basename "$workflow_file")
    
    # Skip if we've already processed this repo
    if [[ -f "$OUTPUT_DIR/processed_$(basename "$repo_path").txt" ]]; then
        continue
    fi
    
    touch "$OUTPUT_DIR/processed_$(basename "$repo_path").txt"
    TOTAL_REPOS=$((TOTAL_REPOS + 1))
    
    REPO_LANGUAGES=()
    REPO_WORKFLOWS=()
    
    # Check for all language indicators
    for lang_spec in "${LANGUAGE_WORKFLOWS[@]}"; do
        IFS=":" read -r workflow_file pattern <<< "$lang_spec"
        if [[ "$workflow_file" == "$workflow_name" ]]; then
            REPO_WORKFLOWS+=("$lang_spec")
        fi
        
        # Check if repo has this language
        if has_language_files "$repo_path" "$pattern"; then
            REPO_LANGUAGES+=("$lang_spec")
        fi
    done
    
    # Check if there are mismatches
    HAS_MISMATCH=false
    
    for lang_spec in "${REPO_WORKFLOWS[@]}"; do
        IFS=":" read -r wf lang pattern <<< "$lang_spec"
        
        # Check if repo has this language
        if ! has_language_files "$repo_path" "$pattern"; then
            HAS_MISMATCH=true
            MISMATCH_COUNT=$((MISMATCH_COUNT + 1))
            echo "$repo_path: WORKFLOW $wf EXISTS but no $lang files found" >> "$MISMATCH_FILE"
        fi
    done
    
    for lang_spec in "${REPO_LANGUAGES[@]}"; do
        IFS=":" read -r wf lang pattern <<< "$lang_spec"
        
        # Check if repo has the workflow
        if [[ ! -f "$repo_path/.github/workflows/$wf" ]]; then
            HAS_MISMATCH=true
            MISMATCH_COUNT=$((MISMATCH_COUNT + 1))
            echo "$repo_path: $lang files EXISTS but workflow $wf MISSING" >> "$MISMATCH_FILE"
        fi
    done
    
    if $HAS_MISMATCH; then
        REPOS_WITH_MISMATCHES=$((REPOS_WITH_MISMATCHES + 1))
    fi
    
done < <(find "$REPOS_ROOT" "$META_REPOS_ROOT" -name "*.yml" -path "*/.github/workflows/*" -type f 2>/dev/null)

echo "## Summary" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"
echo "- **Total repos checked**: $TOTAL_REPOS" >> "$REPORT_FILE"
echo "- **Repos with mismatches**: $REPOS_WITH_MISMATCHES" >> "$REPORT_FILE"
echo "- **Total mismatches found**: $MISMATCH_COUNT" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

# Add mismatch details
echo "## Detailed Mismatches" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"
echo "See: $MISMATCH_FILE" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

# Display report
cat "$REPORT_FILE"

if [[ -s "$MISMATCH_FILE" ]]; then
    echo ""
    echo "=== MISMATCHES FOUND ==="
    head -50 "$MISMATCH_FILE"
    if [[ $(wc -l < "$MISMATCH_FILE") -gt 50 ]]; then
        echo "... and more (see $MISMATCH_FILE)"
    fi
else
    echo ""
    echo "✅ No mismatches found!"
fi

echo ""
echo "Report saved to: $REPORT_FILE"
echo "Mismatches saved to: $MISMATCH_FILE"
