#!/bin/bash
# SPDX-License-Identifier: MPL-2.0
# Create and merge PRs for CI/CD fixes

set -euo pipefail

BRANCH_NAME="chore/apply-foundation-ci-fixes-20260911"
PR_TITLE="fix(ci): apply foundation CI/CD security fixes"
PR_BODY="Apply foundational CI/CD security fixes

- Update CodeQL workflow to SHA-pinned actions with persist-credentials: false
- Update reusable workflow pins to current standards main SHAs
- Add persist-credentials: false to all checkout actions

Generated by Mistral Vibe
Co-Authored-By: Mistral Vibe <vibe@mistral.ai>"

# Get list of repos with the fix branch
REPO_LIST_FILE="/tmp/repo-list-with-fix-branch-$(date +%s).txt"

find "/home/hyperpolymath/developer/hyper-repos" "/home/hyperpolymath/developer/meta-repos" \
    -maxdepth 3 \
    -type d \
    -name ".git" | \
    while read git_dir; do
        repo_path="$(dirname "$git_dir")"
        cd "$repo_path"
        if git branch -r | grep -q "origin/$BRANCH_NAME" 2>/dev/null; then
            echo "$repo_path"
        fi
    done > "$REPO_LIST_FILE"

TOTAL=$(wc -l < "$REPO_LIST_FILE" | tr -d ' ')
echo "Total repos with fix branch: $TOTAL"
echo ""

SUCCESS=0
FAILED=0
SKIPPED=0
PROCESSED=0

while IFS= read -r repo_path; do
    ((PROCESSED++))
    repo_name=$(basename "$repo_path")
    
    if [[ "$repo_path" == *"hyper-repos/"* ]]; then
        org="hyperpolymath"
    elif [[ "$repo_path" == *"meta-repos/"* ]]; then
        org="metadatastician"
    else
        ((SKIPPED++))
        echo "[$PROCESSED] $repo_name: Unknown org, skipping"
        continue
    fi
    
    echo "[$PROCESSED] Processing: $org/$repo_name"
    cd "$repo_path"
    
    EXISTING_PR=$(gh pr list --head "$BRANCH_NAME" --json number --jq '.[] | .number' 2>/dev/null || true)
    
    if [[ -n "$EXISTING_PR" ]]; then
        echo "  PR #$EXISTING_PR already exists"
        echo "  Attempting to merge..."
        MERGE_OUTPUT=$(gh pr merge "$EXISTING_PR" --squash --auto 2>&1 || true)
        if echo "$MERGE_OUTPUT" | grep -q "Merged"; then
            echo "  MERGED"
            ((SUCCESS++))
        else
            echo "  Merge failed: $(echo "$MERGE_OUTPUT" | tail -1)"
            ((FAILED++))
        fi
    else
        echo "  Creating new PR..."
        PR_OUTPUT=$(gh pr create --base main --head "$BRANCH_NAME" --title "$PR_TITLE" --body "$PR_BODY" 2>&1 || true)
        if echo "$PR_OUTPUT" | grep -q "Pull request"; then
            PR_NUM=$(echo "$PR_OUTPUT" | grep -oE 'pull/[0-9]+' | grep -oE '[0-9]+' | head -1)
            if [[ -n "$PR_NUM" ]]; then
                echo "  PR #$PR_NUM created"
                gh pr merge "$PR_NUM" --squash --auto 2>&1 | grep -E "Enabled|already" || true
                ((SUCCESS++))
            else
                echo "  Could not get PR number"
                ((FAILED++))
            fi
        else
            echo "  PR creation failed"
            ((FAILED++))
        fi
    fi
    echo ""
done < "$REPO_LIST_FILE"

rm -f "$REPO_LIST_FILE"

echo "=========================================="
echo "Summary: $TOTAL total, $SUCCESS success, $FAILED failed, $SKIPPED skipped"
echo "=========================================="
