#!/bin/bash
# fix_all_token_permissions_v2.sh - Improved version with better detection and fixing

set -euo pipefail

# Configuration
REPO_ROOTS=("/home/hyperpolymath/developer/hyper-repos" "/home/hyperpolymath/developer/meta-repos")
GIT_USER_NAME="Mistral Vibe"
GIT_USER_EMAIL="vibe@mistral.ai"
MAX_ITERATIONS=5

# Counters
TOTAL_FIXED=0
TOTAL_SCANNED=0
TOTAL_REPOS=0
ITERATION=1

# Initialize git config
git config --global user.name "$GIT_USER_NAME"
git config --global user.email "$GIT_USER_EMAIL"

# Function to check if a workflow has top-level permissions issues
has_permissions_issue() {
    local file="$1"
    
    # Check for top-level contents: write (with or without trailing comma)
    if awk '/^permissions:/{found=1; next} found && /^  contents: write/{exit 0} found && /^  write-all: true/{exit 0} {found=0}' "$file" 2>/dev/null; then
        return 0
    fi
    
    # Check for permissions: write-all
    if grep -q "^permissions: write-all" "$file" 2>/dev/null; then
        return 0
    fi
    
    return 1
}

# Function to fix a single workflow file
fix_workflow_file() {
    local file="$1"
    local backup="${file}.wh002_backup"
    local temp="${file}.wh002_tmp"
    
    # Check if file has issues
    if ! has_permissions_issue "$file"; then
        return 0
    fi
    
    cp "$file" "$backup"
    
    # Use Python for more reliable YAML manipulation
    # Since we don't have python3 available, use awk with better logic
    
    awk '
    /^permissions: / {
        print "permissions:"
        in_perms=1
        next
    }
    in_perms && /^  contents: / {
        # Change any contents: value to read
        print "  contents: read"
        in_perms=1
        next
    }
    in_perms && /^  write-all: / {
        # Change write-all to false
        print "  write-all: false"
        in_perms=1
        next
    }
    in_perms && /^permissions: write-all/ {
        # Handle inline write-all
        print "permissions: read-all"
        in_perms=0
        next
    }
    /^[a-zA-Z]/ && !/^permissions:/ && in_perms {
        in_perms=0
    }
    { print }
    ' "$file" > "$temp"
    
    # Verify the fix
    if ! has_permissions_issue "$temp"; then
        mv "$temp" "$file"
        rm "$backup"
        TOTAL_FIXED=$((TOTAL_FIXED + 1))
        return 0
    else
        mv "$backup" "$file"
        rm -f "$temp"
        return 1
    fi
}

# Function to process a single repo
process_repo() {
    local repo="$1"
    local repo_name=$(basename "$repo")
    local workflow_dir="$repo/.github/workflows"
    local has_changes=false
    local repo_fixed=0
    
    if [ ! -d "$workflow_dir" ]; then
        return 0
    fi
    
    # Find all workflow files
    while IFS= read -r -d $'\0' file; do
        TOTAL_SCANNED=$((TOTAL_SCANNED + 1))
        if fix_workflow_file "$file"; then
            has_changes=true
            repo_fixed=$((repo_fixed + 1))
        fi
    done < <(find "$workflow_dir" -maxdepth 1 -type f \( -name "*.yml" -o -name "*.yaml" \) -print0 2>/dev/null)
    
    # Commit changes if any
    if $has_changes; then
        echo "  Committing $repo_fixed changes for $repo_name..."
        cd "$repo"
        
        if ! git diff --quiet .github/workflows/ 2>/dev/null; then
            git add .github/workflows/
            git commit -m "Fix TokenPermissionsID: apply least-privilege permissions

Apply principle of least privilege for GITHUB_TOKEN:
- Change top-level permissions to read-only
- Jobs inherit read permissions, can escalate as needed

This resolves Scorecard TokenPermissionsID alerts.

Generated by Mistral Vibe.
Co-Authored-By: Mistral Vibe <vibe@mistral.ai>"
            echo "    ✓ Committed"
        else
            echo "    No changes to commit"
        fi
        
        cd /home/hyperpolymath/developer
    fi
    
    TOTAL_REPOS=$((TOTAL_REPOS + 1))
}

# Main loop
echo "=========================================="
echo "TokenPermissionsID Bulk Fix Process v2"
echo "=========================================="
echo ""

while [ $ITERATION -le $MAX_ITERATIONS ]; do
    echo "Iteration $ITERATION/$MAX_ITERATIONS"
    echo "--------------------------------------"
    
    local iteration_fixed=0
    local iteration_start=$TOTAL_FIXED
    
    # Process all repos
    for repo_root in "${REPO_ROOTS[@]}"; do
        # Find all repos in this root
        while IFS= read -r -d $'\0' repo; do
            process_repo "$repo"
        done < <(find "$repo_root" -type d -name ".git" -printf "%h\0" 2>/dev/null)
    done
    
    iteration_fixed=$((TOTAL_FIXED - iteration_start))
    
    echo ""
    echo "Iteration $ITERATION results:"
    echo "  Files scanned: $TOTAL_SCANNED"
    echo "  Files fixed this iteration: $iteration_fixed"
    echo "  Total files fixed: $TOTAL_FIXED"
    echo "  Repos processed: $TOTAL_REPOS"
    
    if [ $iteration_fixed -eq 0 ]; then
        echo ""
        echo "✓ No more issues found! All TokenPermissionsID issues resolved."
        exit 0
    fi
    
    ITERATION=$((ITERATION + 1))
    echo ""
done

echo ""
echo "Reached maximum iterations ($MAX_ITERATIONS). Some issues may remain."
echo "Total fixed: $TOTAL_FIXED files"
