#!/bin/bash
# fix_all_token_permissions.sh - Comprehensive fix for all TokenPermissionsID issues
# This script will iteratively find and fix all workflows with overly permissive top-level permissions

set -euo pipefail

# Configuration
REPO_ROOTS=("/home/hyperpolymath/developer/hyper-repos" "/home/hyperpolymath/developer/meta-repos")
GIT_USER_NAME="Mistral Vibe"
GIT_USER_EMAIL="vibe@mistral.ai"
DRY_RUN=false
MAX_ITERATIONS=10

# Counters
TOTAL_FIXED=0
TOTAL_SCANNED=0
TOTAL_REPOS=0

# Initialize git config
if ! git config --global user.name >/dev/null 2>&1; then
    git config --global user.name "$GIT_USER_NAME"
fi
if ! git config --global user.email >/dev/null 2>&1; then
    git config --global user.email "$GIT_USER_EMAIL"
fi

# Function to fix a single workflow file
fix_workflow_file() {
    local file="$1"
    local backup="${file}.wh002_backup"
    local temp="${file}.wh002_tmp"
    
    # Check if file has top-level permissions issues
    local has_issue=false
    
    # Check for top-level contents: write
    if awk '/^permissions:/{getline; if($0 ~ /^  contents: write($|,)/) exit 0; else exit 1}' "$file" 2>/dev/null; then
        has_issue=true
    fi
    
    # Check for top-level write-all: true
    if awk '/^permissions:/{getline; if($0 ~ /^  write-all: true($|,)/) exit 0; else exit 1}' "$file" 2>/dev/null; then
        has_issue=true
    fi
    
    if ! $has_issue; then
        return 0
    fi
    
    echo "  Fixing: $file"
    
    # Create backup
    cp "$file" "$backup"
    
    # Strategy: Change top-level to read-all, let jobs inherit or add job-level permissions
    # This is a safe default that won't break workflows
    awk '
    /^permissions:/ {
        print "permissions:"
        print "  contents: read"
        # Skip the next lines until we hit a non-permission line
        while (getline > 0 && ($0 ~ /^  [a-zA-Z-]+:/ || $0 ~ /^  #/)) {
            # Keep comments and other permission keys
            if ($0 ~ /^  #/ || $0 ~ /^  actions:/ || $0 ~ /^  pull-requests:/ || $0 ~ /^  repository-projects:/) {
                print
            }
            # Skip contents: write and write-all: true
            if (!($0 ~ /^  contents: write/ || $0 ~ /^  write-all: true/)) {
                print
            }
        }
        print
        next
    }
    { print }
    ' "$file" > "$temp"
    
    # Verify the fix
    if ! awk '/^permissions:/{getline; if($0 ~ /^  contents: write($|,)/) exit 0; else if($0 ~ /^  write-all: true($|,)/) exit 0; else exit 1}' "$temp" 2>/dev/null; then
        mv "$temp" "$file"
        rm "$backup"
        TOTAL_FIXED=$((TOTAL_FIXED + 1))
        echo "    ✓ Fixed"
        return 0
    else
        echo "    ✗ Verification failed, restored backup"
        mv "$backup" "$file"
        rm -f "$temp"
        return 1
    fi
}

# Function to process a single repo
process_repo() {
    local repo="$1"
    local repo_name=$(basename "$repo")
    local workflow_dir="$repo/.github/workflows"
    local has_changes=false
    
    if [ ! -d "$workflow_dir" ]; then
        return 0
    fi
    
    echo "Processing: $repo_name"
    
    # Find all workflow files
    find "$workflow_dir" -maxdepth 1 -type f \( -name "*.yml" -o -name "*.yaml" \) -print 2>/dev/null | while read -r file; do
        TOTAL_SCANNED=$((TOTAL_SCANNED + 1))
        if fix_workflow_file "$file"; then
            has_changes=true
        fi
    done
    
    # Commit changes if any
    if $has_changes; then
        echo "  Committing changes for $repo_name..."
        cd "$repo"
        
        # Check if there are any changes
        if ! git diff --quiet; then
            git add .github/workflows/
            git commit -m "Fix TokenPermissionsID: apply least-privilege permissions

Apply principle of least privilege for GITHUB_TOKEN:
- Change top-level permissions to read-only
- Jobs inherit read permissions, can escalate as needed

This resolves Scorecard TokenPermissionsID alerts.

Generated by Mistral Vibe.
Co-Authored-By: Mistral Vibe <vibe@mistral.ai>"
            echo "    ✓ Committed"
        else
            echo "    No changes to commit"
        fi
        
        cd /home/hyperpolymath/developer
    fi
    
    TOTAL_REPOS=$((TOTAL_REPOS + 1))
}

# Main loop - iterate until no more issues found
echo "=========================================="
echo "TokenPermissionsID Bulk Fix Process"
echo "=========================================="
echo ""

for iteration in $(seq 1 $MAX_ITERATIONS); do
    echo "Iteration $iteration/$MAX_ITERATIONS"
    echo "--------------------------------------"
    
    TOTAL_FIXED_ITERATION=0
    
    # Process all repos
    for repo_root in "${REPO_ROOTS[@]}"; do
        # Find all repos in this root
        find "$repo_root" -type d -name ".git" -printf "%h\n" 2>/dev/null | while read -r repo; do
            process_repo "$repo"
        done
    done
    
    echo ""
    echo "Iteration $iteration results:"
    echo "  Files scanned: $TOTAL_SCANNED"
    echo "  Files fixed: $TOTAL_FIXED"
    echo "  Repos processed: $TOTAL_REPOS"
    
    if [ $TOTAL_FIXED_ITERATION -eq 0 ]; then
        echo ""
        echo "✓ No more issues found! All TokenPermissionsID issues resolved."
        exit 0
    fi
    
    echo ""
done

echo ""
echo "Reached maximum iterations ($MAX_ITERATIONS). Some issues may remain."
