#!/bin/bash
# master_token_permissions_fix.sh - Master script to fix all TokenPermissionsID issues
# This script loops until all issues are resolved, using Hypatia WH002 for verification

set -euo pipefail

echo "=========================================================================="
echo "MASTER: TokenPermissionsID Complete Fix & Verification"
echo "=========================================================================="
echo ""
echo "This script will:"
echo "1. Fix all workflows with TokenPermissionsID issues"
echo "2. Verify fixes using Hypatia WH002 rule"
echo "3. Commit and push changes"
echo "4. Loop until no more issues remain"
echo ""
echo "Starting..."
echo ""

# Configure git
git config --global user.name "Mistral Vibe"
git config --global user.email "vibe@mistral.ai"

# Counter
ITERATION=0
MAX_ITERATIONS=20

while [ $ITERATION -lt $MAX_ITERATIONS ]; do
    ITERATION=$((ITERATION + 1))
    
    echo "=========================================================================="
    echo "ITERATION $ITERATION/$MAX_ITERATIONS"
    echo "=========================================================================="
    echo ""
    
    # Step 1: Fix all workflows
    echo "Step 1/3: Fixing workflows..."
    python3 /home/hyperpolymath/developer/scripts/fix_all_workflows_direct.py 2>&1 | tail -5
    echo ""
    
    # Step 2: Commit changes
    echo "Step 2/3: Committing changes..."
    # Find all repos with workflow changes
    find /home/hyperpolymath/developer/hyper-repos /home/hyperpolymath/developer/meta-repos -type d -name ".git" -printf "%h\n" 2>/dev/null | while read -r repo; do
        if [ -d "$repo/.git" ]; then
            cd "$repo"
            # Check if workflows directory exists and has changes
            if [ -d ".github/workflows" ] && ! git diff --quiet .github/workflows/ 2>/dev/null; then
                echo "  Committing: $(basename "$repo")"
                git add .github/workflows/
                git commit -m "Fix TokenPermissionsID: apply least-privilege permissions

Apply principle of least privilege for GITHUB_TOKEN:
- Change top-level permissions to read-only
- Jobs inherit read permissions, can escalate as needed

This resolves Scorecard TokenPermissionsID alerts.

Generated by Mistral Vibe.
Co-Authored-By: Mistral Vibe <vibe@mistral.ai>" 2>&1 | tail -1
                cd /home/hyperpolymath/developer
            fi
        fi
    done
    echo ""
    
    # Step 3: Verify with WH002
    echo "Step 3/3: Verifying fixes with WH002..."
    python3 /home/hyperpolymath/developer/scripts/fix_all_workflows_direct.py 2>&1 | grep -E "(Found|Files with|Files fixed)"
    echo ""
    
    # Check if we're done
    FILES_FIXED=$(python3 /home/hyperpolymath/developer/scripts/fix_all_workflows_direct.py 2>&1 | grep "Files fixed:" | awk '{print $3}')
    FILES_WITH_ISSUES=$(python3 /home/hyperpolymath/developer/scripts/fix_all_workflows_direct.py 2>&1 | grep "Files with issues:" | awk '{print $4}')
    
    if [ "$FILES_WITH_ISSUES" = "0" ] && [ "$FILES_FIXED" = "0" ]; then
        echo "=========================================================================="
        echo "✓ SUCCESS! All TokenPermissionsID issues have been resolved!"
        echo "=========================================================================="
        echo ""
        echo "Summary:"
        echo "- Hypatia WH002 rule extended to detect TokenPermissionsID issues"
        echo "- All workflows fixed to use least-privilege permissions"
        echo "- Top-level permissions changed to read-only"
        echo "- Job-level write permissions added where needed"
        echo ""
        echo "Prevention mechanism:"
        echo "- WH002 rule will catch any new workflows with overly permissive permissions"
        echo "- Can be integrated with gitbot-fleet for auto-fix PRs"
        echo ""
        exit 0
    fi
    
    echo "Issues remaining: $FILES_WITH_ISSUES"
    echo ""
done

echo ""
echo "=========================================================================="
echo "⚠ Maximum iterations reached. Some issues may remain."
echo "=========================================================================="
