#!/bin/bash

# Script to update all repos to use the reusable Central Estate CI/CD Audit workflow
# from cicd-suite instead of local copies.
#
# This script will:
# 1. Find all repos with a local main-estate-audit.yml
# 2. Replace it with a calling workflow that uses cicd-suite
# 3. Commit the change
#
# Usage: ./update-main-estate-audit.sh [--dry-run] [--force]

DRY_RUN=false
FORCE=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        --dry-run)
            DRY_RUN=true
            shift
            ;;
        --force)
            FORCE=true
            shift
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
done

# The calling workflow content
CALLING_WORKFLOW='name: Central Estate CI/CD Audit

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:

jobs:
  call-estate-audit:
    uses: hyperpolymath/cicd-suite/.github/workflows/main-estate-audit.yml@feat/cicd-workflow-call'

# Find all main-estate-audit.yml files
echo "Finding all main-estate-audit.yml files..."

# Use a temp file to store the list
TMPFILE=$(mktemp)
find /home/hyperpolymath/developer/hyper-repos /home/hyperpolymath/developer/meta-repos \
    -name "main-estate-audit.yml" \
    -type f \
    -path "*/.github/workflows/*" \
    > "$TMPFILE"

# Filter out tmp directories and other non-repo paths
FILTERED_TMP=$(mktemp)
grep -v ".tmp" "$TMPFILE" | grep -v "/\.git$" | grep -v "/worktrees/" > "$FILTERED_TMP"

TOTAL=$(wc -l < "$FILTERED_TMP")
echo "Found $TOTAL workflow files to update"

if [[ "$DRY_RUN" == true ]]; then
    echo "Dry run - would update the following files:"
    cat "$FILTERED_TMP"
    rm "$TMPFILE" "$FILTERED_TMP"
    exit 0
fi

# Process each file
UPDATED=0
SKIPPED=0
FAILED=0

while IFS= read -r workflow_file; do
    # Get the repo directory
    repo_dir=$(dirname $(dirname $(dirname "$workflow_file")))
    
    # Check if this is a git repo
    if [[ ! -d "$repo_dir/.git" ]]; then
        echo "Skipping $workflow_file - not in a git repo"
        ((SKIPPED++))
        continue
    fi
    
    # Check if the file is already the calling workflow
    if grep -q "uses: hyperpolymath/cicd-suite" "$workflow_file" 2>/dev/null; then
        echo "Skipping $workflow_file - already using calling workflow"
        ((SKIPPED++))
        continue
    fi
    
    # Check if the file is tracked
    cd "$repo_dir"
    if ! git ls-files "$workflow_file" >/dev/null 2>&1; then
        echo "Skipping $workflow_file - not tracked in git"
        ((SKIPPED++))
        continue
    fi
    
    # Backup the original file
    cp "$workflow_file" "$workflow_file.bak"
    
    # Write the new calling workflow
    echo "$CALLING_WORKFLOW" > "$workflow_file"
    
    # Check if the file changed
    if diff -q "$workflow_file.bak" "$workflow_file" >/dev/null 2>&1; then
        echo "No change needed for $workflow_file"
        rm "$workflow_file.bak"
        ((SKIPPED++))
        continue
    fi
    
    # Commit the change
    git add "$workflow_file"
    git commit -m "chore(ci): use reusable Central Estate CI/CD Audit from cicd-suite

Replace local copy with call to hyperpolymath/cicd-suite workflow
for single-source maintenance.

Generated by Mistral Vibe.
Co-Authored-By: Mistral Vibe <vibe@mistral.ai>"
    
    echo "Updated $workflow_file"
    ((UPDATED++))
    
    rm "$workflow_file.bak"
    
done < "$FILTERED_TMP"

echo ""
echo "Summary:"
echo "  Updated: $UPDATED"
echo "  Skipped: $SKIPPED"
echo "  Failed: $FAILED"

rm "$TMPFILE" "$FILTERED_TMP"

echo ""
echo "Done!"
