#!/bin/sh
# SPDX-License-Identifier: PMPL-1.0-or-later
# SPDX-FileCopyrightText: 2026 Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
#
# sync-aggregator.sh — regenerate the published superproject as an artifact.
#
# repos-monorepo is OUTPUT, never a workspace: its submodule pointers are an
# auto-bumped index of the flat clones' pushed HEADs. This keeps GitHub Pages,
# the GitLab/Bitbucket mirror and the governance workflows working without
# anyone hand-resolving submodule conflicts.
#
# Default is DRY-RUN (show what would change). Add --commit to record the bump,
# --push to also push (which triggers Pages + mirror). Never force-pushes.
#
# Usage: sync-aggregator.sh [--commit] [--push] [AGGREGATOR_DIR]
set -eu

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
do_commit=no; do_push=no; AGG=""
for a in "$@"; do
  case "$a" in
    --commit) do_commit=yes ;;
    --push)   do_commit=yes; do_push=yes ;;
    --*)      echo "sync-aggregator: unknown flag $a" >&2; exit 2 ;;
    *)        AGG=$a ;;
  esac
done
AGG=${AGG:-"$ROOT/../repos-monorepo"}
[ -d "$AGG/.git" ] || { echo "sync-aggregator: not a git repo: $AGG" >&2; exit 1; }

echo "aggregator: $AGG"
echo "mode: $( [ $do_push = yes ] && echo push || { [ $do_commit = yes ] && echo commit || echo dry-run; } )"

# Bump every submodule pointer to its remote-tracked HEAD, ONE AT A TIME.
# A single `git submodule update --recursive` aborts on the first URL-less
# entry (.git-private-farm) — the hazard documented in scripts/gitlink-drift.jl.
# So we walk declared paths from .gitmodules and skip any without a url.
git -C "$AGG" config -f .gitmodules --get-regexp '^submodule\..*\.path$' \
  | while read -r key path; do
      sm=$(echo "$key" | sed -e 's/^submodule\.//' -e 's/\.path$//')
      if ! git -C "$AGG" config -f .gitmodules --get "submodule.$sm.url" >/dev/null 2>&1; then
        echo "  skip $path (no url in .gitmodules)"; continue
      fi
      git -C "$AGG" submodule update --init --remote -- "$path" >/dev/null 2>&1 \
        && echo "  ok   $path" \
        || echo "  warn $path (update failed — left as-is)"
    done

changed=$(git -C "$AGG" status --porcelain | grep -c '^ M \|^M ' || true)
echo "submodule pointers changed: $changed"

if [ "$changed" -eq 0 ]; then
  echo "nothing to sync — aggregator already current."
  exit 0
fi

if [ "$do_commit" = no ]; then
  echo
  echo "DRY-RUN. Pointers that would be bumped:"
  git -C "$AGG" status --porcelain | grep '^ M \|^M ' | sed 's/^/  /'
  echo
  echo "Re-run with --commit (record) or --push (record + trigger Pages/mirror)."
  exit 0
fi

git -C "$AGG" add -A
git -C "$AGG" commit -m "chore(sync): bump submodule index $(date -I)

Generated by reposystem/scripts/sync-aggregator.sh. Source of truth is the
flat clones; this records their pushed HEADs for Pages/mirror/governance CI." \
  --trailer "Co-Authored-By: Claude Opus 4.7 (1M context) <noreply@anthropic.com>"
echo "committed."

if [ "$do_push" = yes ]; then
  git -C "$AGG" push
  echo "pushed — Pages deploy + GitLab/Bitbucket mirror will trigger."
else
  echo "not pushed (add --push when ready)."
fi
